import type { Answer, AnswerSet } from "@/lib/types";

// Answer key for y11-economics-essay-scaffold. NO "server-only" import here (the
// validator reads it); only re-exported via content/answers/index.ts, which is
// server-only. Never import from a client component.

const U = "y11-economics-essay-scaffold";
const p2 = (n: number) => String(n).padStart(2, "0");

// Grading directive passed to the examiner LLM (via the answer key's `notes`).
const DIRECTIVE =
  "This is an essay SCAFFOLD (a plan), not a full essay. Mark each of the five parts out of 1, for 5 marks total. " +
  "Award a part's mark if the student sets up that section with relevant, accurate economic content: " +
  "a clear thesis and the right key terms to define (Part 1); a sound core concept or context (Part 2); " +
  "a clear cause-and-effect economic mechanism, ideally with theory/a diagram and evidence (Part 3); " +
  "genuine trade-offs, limitations or conflicting objectives (Part 4); a synthesis that ties back to the thesis with no new content (Part 5). " +
  "Judge the economic reasoning and structural logic (the STEEL method — Statement, Theory, Evidence, Explanation, Link) rather than the phrasing. " +
  "Give full credit for alternative valid economic arguments, for different but accurate recent Australian data, and for diagrams correctly described in words. " +
  "Do not penalise appropriate brevity in a plan, and do not penalise the omission of content that belongs in a different part.";

function ea(n: number, model: string, rubric: [string, string, string, string, string]): [string, Answer] {
  return [`${U}.e${p2(n)}`, { modelAnswer: model, rubric, notes: DIRECTIVE }];
}

const answerList: Array<[string, Answer]> = [
  ea(1,
    "Part 1 (Introduction): Thesis — the free market allocates most resources efficiently through the price mechanism, but it fails in several predictable ways, giving a strong case for targeted government intervention. Key terms to define: free market, price mechanism, allocative efficiency, market failure, government intervention.\n" +
    "Part 2 (Point 1 — core concept): Explain how a free market normally works — the signalling, incentive and rationing functions of relative prices coordinate the decisions of self-interested buyers and sellers and push markets toward equilibrium, which can be allocatively efficient. Note the institutions markets need: rule of law, property rights, enforceable contracts.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the main failures: negative externalities (overproduction of goods like electricity from fossil fuels, shown on a supply-demand diagram where marginal social cost exceeds marginal private cost); under-provision of public goods and merit goods; abuse of market power in concentrated industries; asymmetric information; and income and wealth inequality. In each case the market price does not capture the full social costs or benefits, so the quantity produced is not socially optimal.\n" +
    "Part 4 (Point 3 — trade-offs): Government intervention (taxes, subsidies, regulation, direct provision, price controls) can move outcomes toward the social optimum, but it has limits: information problems, administrative and compliance costs, unintended consequences (e.g. rent controls causing housing shortages), regulatory capture and rent-seeking, and the risk of government failure where the cure is worse than the disease.\n" +
    "Part 5 (Conclusion): Synthesise — markets are a powerful but imperfect allocator; a mixed economy uses government intervention to correct clear cases of market failure while preserving the efficiency gains from markets. The thesis holds: intervention is justified where the benefits of correcting a failure outweigh the costs of intervening.",
    [
      "Introduction: clear thesis (markets are efficient but fail predictably, justifying targeted intervention) and names key terms (price mechanism, allocative efficiency, market failure)",
      "Body 1: explains how the price mechanism normally coordinates a market toward an efficient equilibrium (signalling / incentive / rationing)",
      "Body 2: analyses specific types of market failure with a cause-and-effect mechanism (externalities, public goods, market power, asymmetric information, inequality), ideally with a diagram",
      "Body 3: identifies real limitations of government intervention (information, cost, unintended consequences, government failure / rent-seeking)",
      "Conclusion: synthesises to a mixed-economy position and restates the thesis without new content",
    ]),
  ea(2,
    "Part 1 (Introduction): Thesis — the price mechanism fails in several distinct ways, and the Australian government has a legitimate but limited role in correcting each. Key terms: market failure, allocative efficiency, externality, public good, merit/demerit good, government intervention.\n" +
    "Part 2 (Point 1 — core concept): Define market failure as any situation where the free market does not achieve an efficient (or, more broadly, a socially desirable) allocation of resources. Establish the benchmark — a competitive market at equilibrium equates marginal social benefit and marginal social cost.\n" +
    "Part 3 (Point 2 — mechanism): Work through the types: (i) externalities — negative production externalities cause overproduction (MSC > MPC), positive consumption externalities cause underconsumption (MSB > MPB), shown on demand-supply diagrams; (ii) public goods — non-excludability and non-rivalry cause the free-rider problem and zero private provision; (iii) market power — monopolies and oligopolies restrict output and raise price; (iv) asymmetric information — e.g. adverse selection in insurance; (v) inequality and social exclusion.\n" +
    "Part 4 (Point 3 — trade-offs): Evaluate government tools: Pigouvian taxes and subsidies, regulation, direct provision (defence, roads), competition law (ACCC), disclosure rules (ASIC). Each has costs — deadweight loss from taxes, difficulty valuing externalities, compliance burden, capture, and government failure. Judge effectiveness case by case.\n" +
    "Part 5 (Conclusion): Synthesise — government can improve on market outcomes where a failure is clear and the intervention is well designed, but it cannot achieve a perfect allocation; the goal is net improvement in efficiency and equity.",
    [
      "Introduction: thesis that the price mechanism fails in distinct ways requiring government correction, with key terms named",
      "Body 1: defines market failure against the efficient-market benchmark (MSB = MSC)",
      "Body 2: analyses the main types of market failure with mechanisms/diagrams (externalities, public goods, market power, asymmetric information, inequality)",
      "Body 3: evaluates specific government tools and their limitations / risk of government failure",
      "Conclusion: synthesises to a 'net improvement, not perfection' position and links to the thesis",
    ]),
  ea(3,
    "Part 1 (Introduction): Thesis — negative production externalities cause a market to overproduce a good and impose uncompensated costs on society; taxes and regulation can each reduce the problem, but neither is a complete solution. Key terms: negative externality, marginal private cost, marginal social cost, market failure, Pigouvian tax, regulation.\n" +
    "Part 2 (Point 1 — core concept): Define a negative externality from production as a cost of producing a good borne by third parties, not by the producer or consumer (e.g. air pollution, carbon emissions). Because the producer only pays private costs, the market ignores the social cost.\n" +
    "Part 3 (Point 2 — mechanism): Draw the demand-supply diagram: the private supply curve (MPC) sits below the true social supply curve (MSC); the market equilibrium quantity is greater, and the price lower, than the socially optimal point where MSB = MSC. The shaded area between MSC and MPC up to the market quantity is the welfare loss. A per-unit tax equal to the marginal external cost shifts supply from MPC toward MSC, cutting output to the optimum and 'internalising' the externality; regulation (emissions caps, standards) directly limits the quantity of the pollutant.\n" +
    "Part 4 (Point 3 — trade-offs): A tax is efficient and raises revenue but the correct rate is hard to estimate, it can be regressive, and firms may relocate ('carbon leakage'). Regulation gives more certainty about the quantity but is blunt, costly to monitor, and gives firms no incentive to cut emissions below the standard. Both face political resistance and business lobbying.\n" +
    "Part 5 (Conclusion): Synthesise — negative externalities are a clear case of market failure; a well-set tax or a firm regulatory cap can move the market toward the social optimum, but measurement, distributional and political limits mean the correction is partial. Thesis confirmed.",
    [
      "Introduction: thesis that negative externalities cause overproduction and that taxes/regulation partly fix it, with key terms (externality, MPC, MSC)",
      "Body 1: defines a negative production externality as a third-party cost not paid by producer or consumer, with an example",
      "Body 2: uses the MPC/MSC demand-supply diagram to show overproduction and welfare loss, and explains how a tax or regulation moves output toward the optimum",
      "Body 3: evaluates the trade-offs of taxes vs regulation (measurement, regression, leakage, monitoring cost, political resistance)",
      "Conclusion: synthesises to 'partial correction of a clear market failure' and restates the thesis",
    ]),
  ea(4,
    "Part 1 (Introduction): Thesis — because public goods are non-excludable and non-rival, private markets will not supply them, so government provision funded by taxation is needed to avoid a serious under-allocation of resources. Key terms: public good, non-excludability, non-rivalry, free-rider problem, market failure, direct provision.\n" +
    "Part 2 (Point 1 — core concept): Define the two properties. Non-excludable: a person who does not pay cannot be prevented from consuming the good (national defence, street lighting). Non-rival: one person's consumption does not reduce the amount available to others. Contrast with a private good (excludable and rival).\n" +
    "Part 3 (Point 2 — mechanism): Explain the free-rider problem: since non-payers cannot be excluded, each individual has an incentive to let others pay, so willing payment is far below the true collective benefit, market demand is understated, and profit-seeking firms supply little or none. The efficient quantity (where the sum of everyone's marginal benefit equals marginal cost) is not reached.\n" +
    "Part 4 (Point 3 — trade-offs): Government solves this by providing the good directly and funding it through compulsory taxation, or by contracting private firms to build it. Limitations: governments must estimate the socially desired quantity without market signals, so there is a risk of over- or under-provision; there are opportunity costs and political influence over what gets funded; and some goods are only partly non-excludable (toll roads), blurring the case.\n" +
    "Part 5 (Conclusion): Synthesise — public goods are a textbook market failure caused by non-excludability and non-rivalry; government provision funded by tax is the standard remedy, accepting that the quantity chosen is a political judgement rather than a market outcome. Thesis holds.",
    [
      "Introduction: thesis that non-excludability/non-rivalry prevent private provision, requiring tax-funded government provision, with key terms",
      "Body 1: defines non-excludability and non-rivalry with valid examples, contrasting with private goods",
      "Body 2: explains the free-rider problem and why it leads to zero/under-provision by private markets (mechanism)",
      "Body 3: discusses how government provides public goods and the limitations (estimating quantity without market signals, opportunity cost, political choice)",
      "Conclusion: synthesises to 'clear market failure, standard tax-funded remedy' and links to the thesis",
    ]),
  ea(5,
    "Part 1 (Introduction): Thesis — asymmetric information and market-power abuse both prevent markets from allocating resources efficiently, and the government intervenes mainly through disclosure rules and competition law. Key terms: asymmetric information, adverse selection, moral hazard, market power, predatory pricing, collusion.\n" +
    "Part 2 (Point 1 — core concept): Define asymmetric information as one party to a transaction having more or better information than the other (e.g. a used-car seller, a borrower). Define market power as the ability of a firm to set price above the competitive level because of high barriers to entry.\n" +
    "Part 3 (Point 2 — mechanism): Asymmetric information causes adverse selection (good risks leave the market, e.g. healthy people drop private health insurance, raising premiums, driving more out — a spiral) and moral hazard (insured parties take more risk). Market power lets a monopolist restrict output and raise price above marginal cost, transferring surplus from consumers to the firm and creating deadweight loss; concentrated markets can also reduce quality and innovation. Predatory pricing and collusion entrench this.\n" +
    "Part 4 (Point 3 — trade-offs): Government responses: mandatory disclosure and licensing (ASIC in financial markets, product standards, food labelling), community rating and mandates in insurance; and the Competition and Consumer Act enforced by the ACCC, which prohibits price fixing, misuse of market power and anti-competitive mergers. Limits: regulators have less information than firms, enforcement is slow and costly, and heavy regulation can deter entry and innovation.\n" +
    "Part 5 (Conclusion): Synthesise — both failures stem from a breakdown in the conditions for competitive markets; targeted rules on information and conduct can improve outcomes, but regulators face their own information and resourcing constraints. Thesis confirmed.",
    [
      "Introduction: thesis linking asymmetric information and market-power abuse to inefficiency and government response, with key terms",
      "Body 1: defines asymmetric information and market power (barriers to entry, price above competitive level)",
      "Body 2: explains the mechanisms — adverse selection/moral hazard, and a monopolist restricting output (deadweight loss), predatory pricing/collusion",
      "Body 3: discusses government tools (disclosure/licensing, competition law/ACCC) and their limitations",
      "Conclusion: synthesises to 'both are breakdowns of competitive conditions, remedied imperfectly' and links to the thesis",
    ]),
  ea(6,
    "Part 1 (Introduction): Thesis — the Australian government carries out reallocation, redistribution and stabilisation using a mix of Budget and regulatory tools, and each function involves trade-offs with efficiency. Key terms: reallocation, redistribution, stabilisation, market failure, progressive tax, transfer payment, fiscal policy.\n" +
    "Part 2 (Point 1 — core concept): Explain reallocation: shifting resources toward goods and services society values more highly, through taxes on demerit goods, subsidies for merit goods, direct provision of public goods, and regulation. Correcting market failure sits here.\n" +
    "Part 3 (Point 2 — mechanism): Explain redistribution: the progressive personal income tax takes a larger share of higher incomes, while transfer payments (Age Pension, JobSeeker, family and rent assistance) and services (public health, education) raise the real incomes of lower-income households, compressing the after-tax-and-transfer income distribution (a Lorenz curve pulled toward the line of equality). Then stabilisation: using the Budget — discretionary changes to G and T, plus automatic stabilisers — to dampen the business cycle, e.g. running a larger deficit in a downturn to support aggregate demand.\n" +
    "Part 4 (Point 3 — trade-offs): Each function can reduce efficiency: high marginal tax rates and generous transfers can weaken incentives to work, save and invest (the equity-efficiency trade-off); reallocation depends on the government correctly identifying the social optimum; stabilisation faces time lags, forecasting error and the political difficulty of tightening policy in good times.\n" +
    "Part 5 (Conclusion): Synthesise — the three functions describe why a mixed economy has a government sector at all; the tools are effective within limits, and the central tension is between improving equity and preserving the incentives that drive efficiency. Thesis holds.",
    [
      "Introduction: thesis that government does reallocation, redistribution and stabilisation with trade-offs, and names key terms",
      "Body 1: explains reallocation (taxes/subsidies/direct provision/regulation to correct market failure and shift resources)",
      "Body 2: explains redistribution (progressive tax + transfers + services compress the income distribution) and stabilisation (Budget dampens the business cycle) with mechanisms",
      "Body 3: identifies the equity-efficiency trade-off and the limits of each function (incentives, identifying the optimum, lags)",
      "Conclusion: synthesises to 'why a mixed economy has a government sector' and restates the thesis",
    ]),
  ea(7,
    "Part 1 (Introduction): Thesis — the tax and transfer system substantially reduces income inequality in Australia, but doing more involves a real trade-off with the incentives that support efficiency and growth. Key terms: income inequality, Lorenz curve, Gini coefficient, progressive tax, transfer payment, equity, efficiency.\n" +
    "Part 2 (Point 1 — core concept): Explain how income inequality is measured (the Lorenz curve and Gini coefficient) and establish that market (pre-tax) income is quite unequally distributed, mainly because of differences in wages, capital income and employment.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the two channels. The progressive income tax scale means average tax rates rise with income, so high earners contribute proportionally more. Transfer payments — the Age Pension, JobSeeker, family payments, rent assistance — are targeted (means-tested) at lower-income households, and government services in kind (Medicare, public schooling) are worth relatively more to them. Together these move Australia's Gini coefficient markedly lower after tax and transfers than before.\n" +
    "Part 4 (Point 3 — trade-offs): Evaluate the limits: very high marginal rates and steep means-test taper rates create effective marginal tax rates that can discourage extra work, especially for second earners; generous, poorly targeted transfers are costly and can create welfare dependency; and redistribution does nothing about the underlying causes (skills, opportunity). There are also value judgements about how much inequality is acceptable.\n" +
    "Part 5 (Conclusion): Synthesise — the tax-transfer system is the government's main and most effective redistributive tool and clearly narrows inequality; pushing further runs into the equity-efficiency trade-off, so the debate is about the right balance, not whether to redistribute at all. Thesis confirmed.",
    [
      "Introduction: thesis that tax-transfers cut inequality but with an equity-efficiency trade-off, and names key terms (Lorenz curve, Gini)",
      "Body 1: explains how inequality is measured and that market income is unequally distributed",
      "Body 2: analyses the redistributive mechanism — progressive tax + targeted transfers + services lower the after-tax-and-transfer Gini",
      "Body 3: identifies the trade-offs / limits (effective marginal tax rates, cost, dependency, doesn't fix root causes, value judgements)",
      "Conclusion: synthesises to 'effective main tool, balance is the real question' and links to the thesis",
    ]),
  ea(8,
    "Part 1 (Introduction): Thesis — there is a genuine economic debate about redistributing income: intervention can improve equity, social cohesion and even long-run growth, but it can also blunt incentives, so the answer depends on how it is designed. Key terms: equity (horizontal and vertical), efficiency, incentive, transfer payment, progressive tax, poverty.\n" +
    "Part 2 (Point 1 — core concept): Set out the starting point: a market economy distributes income according to the ownership and productivity of factors of production, which produces large inequalities and, for some, poverty and social exclusion. Government redistribution is a deliberate departure from that outcome.\n" +
    "Part 3 (Point 2 — mechanism): Arguments for: reducing poverty and its social costs; diminishing marginal utility of income means a dollar is worth more to a poor household, so redistribution can raise total wellbeing; more equal societies can have stronger demand, better health and education outcomes and more social mobility, supporting growth; and fairness / the social contract.\n" +
    "Part 4 (Point 3 — trade-offs): Arguments against / limits: high taxes and withdrawal of benefits reduce the reward for effort, skill acquisition, saving and entrepreneurship (the equity-efficiency trade-off and the 'leaky bucket'); redistribution can create dependency and discourage workforce participation; it treats symptoms rather than causes; and there is disagreement over what 'fair' means and how much inequality is acceptable.\n" +
    "Part 5 (Conclusion): Synthesise — both sides have force; most economists accept some redistribution to relieve poverty and support opportunity, while designing it to minimise damage to incentives. The thesis holds: the case turns on design and degree.",
    [
      "Introduction: thesis that redistribution has real benefits and real costs, so design matters, with key terms (equity, efficiency, incentive)",
      "Body 1: sets the context — the market distributes income by factor ownership/productivity, producing large inequality/poverty",
      "Body 2: develops arguments FOR redistribution (poverty relief, diminishing marginal utility, growth/cohesion, fairness)",
      "Body 3: develops arguments AGAINST / limits (incentive effects, dependency, treats symptoms, value judgements) — the equity-efficiency trade-off",
      "Conclusion: synthesises to a balanced position on design and degree, linking to the thesis",
    ]),
  ea(9,
    "Part 1 (Introduction): Thesis — efficiency and equity are both legitimate goals of government, but pursuing one often comes at some cost to the other, so policy is a search for an acceptable balance rather than a way to maximise both. Key terms: allocative/productive efficiency, equity (horizontal, vertical), equity-efficiency trade-off, incentive.\n" +
    "Part 2 (Point 1 — core concept): Define the two. Efficiency: resources are used to produce the goods society values most (allocative) at lowest cost (productive), maximising the size of the economic 'pie'. Equity: the fairness of how the pie is shared — horizontal equity (treating like cases alike) and vertical equity (asking more of those with more capacity to pay).\n" +
    "Part 3 (Point 2 — mechanism): Explain the trade-off: policies that improve equity — a more progressive income tax, higher transfer payments, a higher minimum wage — can reduce the incentive to work, save, invest or hire, shrinking output (the 'leaky bucket': some value is lost in transferring income). Conversely, efficiency-focused reforms (deregulation, lower taxes) can widen inequality. But note complements: spending on education and health can raise both equity and long-run efficiency.\n" +
    "Part 4 (Point 3 — trade-offs / limitations): The size of the trade-off is contested and depends on how responsive behaviour is to incentives; there are political and value judgements about the acceptable level of inequality; and there is a time dimension — some equity spending pays off in efficiency only in the long run.\n" +
    "Part 5 (Conclusion): Synthesise — the government cannot escape choosing a point on the equity-efficiency frontier; good policy aims for interventions that are 'less leaky' or that raise both, and accepts a trade-off elsewhere. Thesis confirmed.",
    [
      "Introduction: thesis that efficiency and equity both matter but trade off, so policy seeks a balance, with key terms",
      "Body 1: defines allocative/productive efficiency and horizontal/vertical equity",
      "Body 2: explains the trade-off mechanism (equity-improving policies can blunt incentives / the leaky bucket) and notes possible complements",
      "Body 3: discusses limitations — the size of the trade-off is contested, value judgements, the time dimension",
      "Conclusion: synthesises to 'choosing a point on the frontier' and links to the thesis",
    ]),
  ea(10,
    "Part 1 (Introduction): Thesis — the Budget outcome and stance are the government's main fiscal signals, and the choice between surplus and deficit is a trade-off between supporting households and demand now and building fiscal buffers and controlling debt for the future. Key terms: Budget outcome, Budget stance (expansionary/contractionary/neutral), fiscal policy, automatic stabilisers, public debt, cost-of-living relief.\n" +
    "Part 2 (Point 1 — core concept): Define the Budget outcome as revenue minus expenditure over the year (surplus, deficit or balanced), and the stance as the effect of the Budget on aggregate demand relative to the previous year, stripping out cyclical (automatic) effects. Note the difference between the headline and structural (cyclically adjusted) balance.\n" +
    "Part 3 (Point 2 — mechanism): A deficit / expansionary stance injects money into the circular flow: higher G or lower T raises disposable income and demand, which through the multiplier supports output and employment — appropriate in a downturn. A surplus / contractionary stance withdraws demand, helps cool inflation, reduces or repays debt, and rebuilds capacity to respond to the next shock. Recent Australian Budgets have tried to do both — bank commodity-revenue windfalls into surplus while funding targeted cost-of-living relief.\n" +
    "Part 4 (Point 3 — trade-offs): Running deficits adds to public debt and interest payments, can add to demand when the RBA is trying to reduce it (fiscal-monetary conflict), and may crowd out private investment. Running surpluses can weaken a fragile economy, and cutting spending on services or infrastructure has social and long-run growth costs. There are also political incentives to spend and forecasting uncertainty.\n" +
    "Part 5 (Conclusion): Synthesise — the surplus-versus-deficit choice is fundamentally about timing and buffers: deficits are justified to stabilise a weak economy, surpluses to consolidate in good times; the tension in recent Budgets is doing cost-of-living support without adding to inflation. Thesis holds.",
    [
      "Introduction: thesis on the surplus/deficit trade-off (support now vs buffers/debt for later), with key terms (Budget outcome, stance)",
      "Body 1: defines the Budget outcome and Budget stance (and headline vs structural balance)",
      "Body 2: explains the mechanism — a deficit/expansionary stance injects demand via the multiplier; a surplus withdraws demand, cuts debt, rebuilds buffers — with reference to recent Budgets",
      "Body 3: identifies the trade-offs (debt and interest, fiscal-monetary conflict, crowding out; vs weakening the economy, service/infrastructure cuts)",
      "Conclusion: synthesises to 'timing and buffers' and links to the thesis",
    ]),
  ea(11,
    "Part 1 (Introduction): Thesis — structurally rising spending pressures mean the government's Budget choices are increasingly about raising revenue, restraining spending growth or accepting persistent deficits, each with significant economic effects. Key terms: recurrent spending, structural deficit, fiscal sustainability, public debt, tax reform, opportunity cost.\n" +
    "Part 2 (Point 1 — core concept): Set the context: several large programs (health, aged care, the NDIS, defence, and interest on debt) are growing faster than the economy and are hard to cut because they meet essential needs or legal commitments. This creates a structural gap between spending and revenue that will not close as the cycle improves.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the choices and their effects. (i) Raise revenue — higher or broader taxes fund the spending but reduce private disposable income and can blunt incentives. (ii) Restrain spending — reprioritising or means-testing controls the deficit but has social costs and can weaken demand. (iii) Borrow — deficits support demand and let spending continue, but add to debt and future interest, and can conflict with the RBA if inflation is high. Through the circular flow, each option changes leakages (T) or injections (G).\n" +
    "Part 4 (Point 3 — trade-offs): The core trade-offs are present-versus-future (services now vs debt burden later), equity-versus-efficiency in how revenue is raised, and fiscal-versus-monetary coordination. Political constraints make tax increases and spending cuts hard, so deficits are the path of least resistance.\n" +
    "Part 5 (Conclusion): Synthesise — the Budget is being squeezed by structural spending growth; sustainable options require either tax reform or spending restraint, and continued reliance on deficits shifts the cost to the future. Thesis confirmed.",
    [
      "Introduction: thesis that structural spending pressures force a choice between more revenue, spending restraint or persistent deficits, with key terms (structural deficit, fiscal sustainability)",
      "Body 1: sets the context — specific programs growing faster than GDP create a structural gap",
      "Body 2: analyses the three options (raise revenue / restrain spending / borrow) and their effects through the circular flow (T and G)",
      "Body 3: identifies the trade-offs (present vs future, equity vs efficiency, fiscal-monetary coordination, political constraints)",
      "Conclusion: synthesises to 'sustainable options need reform or restraint; deficits defer the cost' and links to the thesis",
    ]),
  ea(12,
    "Part 1 (Introduction): Thesis — changes in G and T move the level of economic activity in a predictable direction through the circular flow and the multiplier, but lags, uncertainty and offsetting behaviour limit the Budget as a stabilisation tool. Key terms: circular flow of income, injections (G), leakages (T), multiplier, marginal propensity to consume, fiscal policy.\n" +
    "Part 2 (Point 1 — core concept): Explain the circular flow: income flows between households, firms, and the financial, government and overseas sectors. The economy is in equilibrium when total leakages (S + T + M) equal total injections (I + G + X). Government spending is an injection; taxation is a leakage.\n" +
    "Part 3 (Point 2 — mechanism): An increase in G (or a cut in T that raises disposable income) is a net injection: the initial spending becomes someone's income, part of which is spent again, and so on — the multiplier process — so the final increase in economic activity is larger than the initial change. The size depends on the marginal propensity to consume (and how much leaks to savings, tax and imports). A rise in T works in reverse.\n" +
    "Part 4 (Point 3 — trade-offs / limitations): Limitations: recognition, decision and implementation lags mean policy can arrive after the economy has already turned; forecasting error; the political difficulty of raising taxes or cutting spending in booms; deficits add to debt; crowding out of private investment; and Ricardian-type behaviour where households save a tax cut expecting future taxes. Fiscal policy can also clash with monetary policy.\n" +
    "Part 5 (Conclusion): Synthesise — the direction of the effect is clear (more G or less T expands activity via the multiplier), but the Budget is a slow and politically constrained instrument, which is why it is often paired with faster-acting monetary policy. Thesis holds.",
    [
      "Introduction: thesis that G and T move activity via the circular flow/multiplier but with real limits, and names key terms",
      "Body 1: explains the circular flow and the equilibrium condition S + T + M = I + G + X (G as injection, T as leakage)",
      "Body 2: explains the multiplier mechanism — an increase in G / cut in T raises activity by more than the initial amount, depending on the MPC/leakages",
      "Body 3: identifies limitations (lags, forecasting error, political constraints, debt, crowding out, offsetting saving, fiscal-monetary clash)",
      "Conclusion: synthesises to 'clear direction, slow and constrained instrument' and links to the thesis",
    ]),
  ea(13,
    "Part 1 (Introduction): Thesis — cost-of-living relief lifts the real incomes of households under pressure and can be well targeted, but broad or poorly designed relief adds to demand and can work against the fight against inflation. Key terms: cost of living, real income, disposable income, aggregate demand, inflation, targeting, fiscal stimulus.\n" +
    "Part 2 (Point 1 — core concept): Context: a sustained rise in the prices of essentials (energy, rent, groceries, insurance) alongside higher interest rates has squeezed household budgets, especially for low-income and mortgaged households. Governments have responded with energy rebates, cheaper medicines, increased rent assistance and income-tax cuts.\n" +
    "Part 3 (Point 2 — mechanism): Analyse effects. Relief raises households' disposable and real incomes, supporting consumption and easing hardship and inequality. Some measures directly lower measured inflation (e.g. an energy bill rebate reduces the CPI energy component). But relief is also a fiscal injection that raises aggregate demand; if demand is already strong relative to supply, this adds to underlying inflationary pressure and can offset the RBA's tightening — the fiscal-monetary tension.\n" +
    "Part 4 (Point 3 — trade-offs): Trade-offs: targeted, temporary relief (means-tested payments) helps the neediest at lower budget cost and less demand impact; broad, permanent relief (across-the-board tax cuts) is politically popular but costly, adds to the structural deficit and stimulates demand more. There is also the risk that subsidising a price weakens the incentive to reduce consumption of, say, energy.\n" +
    "Part 5 (Conclusion): Synthesise — cost-of-living relief is justified to protect vulnerable households and can even reduce headline inflation mechanically, but it must be targeted and temporary to avoid adding to demand and the deficit. Thesis confirmed.",
    [
      "Introduction: thesis that relief helps pressured households but broad relief adds to demand/inflation, with key terms (real income, aggregate demand, targeting)",
      "Body 1: sets the context — rising essential prices + higher rates squeeze households; lists the relief measures",
      "Body 2: analyses the effects — raises real/disposable income and can lower headline CPI, but is also a fiscal injection that can add to underlying inflation (fiscal-monetary tension)",
      "Body 3: evaluates the targeted-and-temporary vs broad-and-permanent trade-off (budget cost, demand impact, structural deficit, price-signal distortion)",
      "Conclusion: synthesises to 'justified but must be targeted and temporary' and links to the thesis",
    ]),
  ea(14,
    "Part 1 (Introduction): Thesis — automatic stabilisers built into the Budget smooth the business cycle quickly and without political decisions, complementing but not replacing discretionary fiscal policy. Key terms: discretionary fiscal policy, automatic (non-discretionary) fiscal policy, automatic stabilisers, progressive tax, transfer payments, business cycle.\n" +
    "Part 2 (Point 1 — core concept): Distinguish the two. Discretionary policy is a deliberate change in G or T announced by the government (a stimulus package, a tax cut). Automatic policy is the change in the Budget that happens on its own as the economy moves through the cycle, with no new decision.\n" +
    "Part 3 (Point 2 — mechanism): Explain how automatic stabilisers work. In a downturn, incomes and profits fall, so progressive tax collections fall (and some taxpayers drop into lower brackets), while unemployment benefits and other transfers rise automatically — the Budget moves toward deficit, cushioning the fall in disposable income and aggregate demand. In a boom the reverse happens: tax revenue surges and transfers fall, moving the Budget toward surplus and restraining demand. The effect is counter-cyclical and immediate.\n" +
    "Part 4 (Point 3 — trade-offs / limitations): Limitations: automatic stabilisers dampen the cycle but do not reverse a deep recession — discretionary action may still be needed; their strength depends on how progressive the tax system and how generous the welfare system are; and the deficits they create in downturns still add to debt. There is also a tension with a strict surplus rule.\n" +
    "Part 5 (Conclusion): Synthesise — automatic stabilisers are the fast, non-political part of fiscal policy that leans against the cycle; discretionary policy handles larger or structural shocks. Thesis holds.",
    [
      "Introduction: thesis that automatic stabilisers smooth the cycle quickly and complement discretionary policy, with key terms",
      "Body 1: distinguishes discretionary (deliberate change to G/T) from automatic (change with no new decision) fiscal policy",
      "Body 2: explains the counter-cyclical mechanism — in a downturn, tax falls and transfers rise automatically, cushioning demand; the reverse in a boom",
      "Body 3: identifies limitations (do not reverse a deep recession, depend on tax progressivity/welfare generosity, still add to debt, tension with surplus rules)",
      "Conclusion: synthesises to 'the fast, non-political part of fiscal policy' and links to the thesis",
    ]),
  ea(15,
    "Part 1 (Introduction): Thesis — taxation serves several essential purposes, and a 'good' tax balances simplicity, equity and efficiency; in practice these criteria conflict, so tax design is a compromise. Key terms: taxation, revenue, resource reallocation, redistribution, direct/indirect tax, equity (horizontal, vertical), efficiency, simplicity.\n" +
    "Part 2 (Point 1 — core concept): Explain the purposes of taxation: to raise revenue to fund government spending; to redistribute income (progressive taxes); to reallocate resources (taxes on demerit goods like tobacco, alcohol and fuel); and to influence economic activity as part of fiscal policy.\n" +
    "Part 3 (Point 2 — mechanism): Set out the features of a good tax. Simplicity: easy to understand, comply with and administer, minimising compliance and collection costs. Equity: horizontal (like taxpayers treated alike) and vertical (those with greater capacity to pay contribute more). Efficiency: raising revenue with the least distortion of decisions to work, save and invest — a tax creates deadweight loss by driving a wedge between the price buyers pay and sellers receive.\n" +
    "Part 4 (Point 3 — trade-offs): Analyse the conflicts. A highly progressive income tax scores well on vertical equity but can reduce efficiency (weaker work and investment incentives) and adds complexity (deductions, avoidance). A broad-based consumption tax (GST) is simple and efficient but regressive. Land tax is efficient but politically unpopular. Every real tax system trades some equity for efficiency or simplicity.\n" +
    "Part 5 (Conclusion): Synthesise — tax exists to fund government and shape the economy; the 'good tax' criteria are a useful benchmark, but because they pull against each other, a real tax mix is a negotiated balance. Thesis confirmed.",
    [
      "Introduction: thesis that tax has several purposes and a good tax balances simplicity/equity/efficiency, which conflict, with key terms",
      "Body 1: explains the purposes of taxation (revenue, redistribution, reallocation, fiscal-policy influence)",
      "Body 2: sets out the features of a good tax — simplicity, equity (horizontal/vertical), efficiency (deadweight loss)",
      "Body 3: analyses the trade-offs between the criteria using examples (progressive income tax vs GST vs land tax)",
      "Conclusion: synthesises to 'a negotiated balance against conflicting criteria' and links to the thesis",
    ]),
  ea(16,
    "Part 1 (Introduction): Thesis — Australia relies on a mix of direct and indirect taxes; the direct taxes (mainly progressive income tax) reduce inequality, while the indirect taxes (mainly the GST) are regressive, so the net redistributive effect depends on the balance of the mix. Key terms: direct tax, indirect tax, tax incidence, progressive, proportional, regressive tax, distribution of income.\n" +
    "Part 2 (Point 1 — core concept): Distinguish the categories. A direct tax is levied on and paid by the same entity and cannot be passed on (personal income tax, company tax) — legal and economic incidence coincide. An indirect tax is levied on producers/sellers but passed on to consumers in the price (GST, excise) — the incidence shifts. Progressive: average rate rises with income; proportional: constant; regressive: average rate falls as income rises.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the effect on the income distribution. The progressive income tax scale means higher earners pay a larger share of income, compressing the after-tax distribution (Lorenz curve pulled toward equality). The GST takes the same percentage of spending regardless of income, but because low-income households spend a larger share of their income, it takes a larger share of their income — it is regressive and widens inequality.\n" +
    "Part 4 (Point 3 — trade-offs): Australia's tax mix is relatively reliant on income tax, which is redistributive but efficiency-costly and exposed to bracket creep and avoidance; shifting toward the GST would be more efficient and stable but more regressive, requiring compensation for low-income households. The net effect on inequality is a policy choice about the balance.\n" +
    "Part 5 (Conclusion): Synthesise — direct taxes narrow inequality and indirect taxes widen it; Australia's mix, weighted toward progressive income tax, is net redistributive, but any rebalancing toward consumption taxes trades equity for efficiency. Thesis confirmed.",
    [
      "Introduction: thesis that the direct/indirect mix determines the net redistributive effect, with key terms (incidence, progressive/regressive)",
      "Body 1: distinguishes direct vs indirect taxes (incidence) and progressive/proportional/regressive",
      "Body 2: analyses the effect on the income distribution — progressive income tax compresses it; the GST is regressive because low-income households spend a larger income share",
      "Body 3: evaluates Australia's actual mix and the equity-efficiency trade-off of rebalancing toward the GST (with compensation)",
      "Conclusion: synthesises to 'net redistributive mix, rebalancing trades equity for efficiency' and links to the thesis",
    ]),
  ea(17,
    "Part 1 (Introduction): Thesis — there is a strong economic case for reforming Australia's tax system to make it simpler, more efficient and more sustainable, but entrenched interests, transition costs and distributional concerns make reform politically very hard. Key terms: tax reform, tax base, efficiency, equity, bracket creep, tax expenditure (concession), fiscal sustainability.\n" +
    "Part 2 (Point 1 — core concept): Context: the system leans heavily on personal income tax, which is eroded by bracket creep and by a narrowing base of concessions; the GST base has shrunk over time; and large tax concessions (on superannuation, capital gains, negative gearing) cost tens of billions and mainly benefit higher-income households. This threatens revenue adequacy as spending pressures grow.\n" +
    "Part 3 (Point 2 — mechanism): The case for reform: broadening the base and lowering rates reduces distortions and deadweight loss (efficiency), improves fairness by removing concessions that favour the wealthy, and provides more stable revenue. Shifting the mix toward efficient bases (consumption, land) and away from income and transaction taxes would raise long-run growth.\n" +
    "Part 4 (Point 3 — obstacles / trade-offs): Obstacles: every concession has a constituency that mobilises against change (retirees, property investors); increasing the GST is regressive and needs costly compensation; states and the Commonwealth share tax powers, complicating agreement; and 'losers' from reform are visible while 'winners' are diffuse, so governments face electoral risk. Past attempts have often stalled.\n" +
    "Part 5 (Conclusion): Synthesise — the economic arguments for reform (efficiency, equity, sustainability) are widely accepted, but the political economy of reform — concentrated losers, compensation costs, federal complexity — explains why it rarely happens. Thesis confirmed.",
    [
      "Introduction: thesis that there is a strong economic case for reform but severe political obstacles, with key terms (tax base, bracket creep, tax concession)",
      "Body 1: sets the context — reliance on income tax, bracket creep, shrinking GST base, costly concessions, revenue adequacy",
      "Body 2: develops the case for reform (broaden base / lower rates → efficiency, equity, revenue stability, growth)",
      "Body 3: analyses the obstacles / trade-offs (concentrated losers, regressive GST needing compensation, federal complexity, electoral risk)",
      "Conclusion: synthesises the economics vs the political economy of reform and links to the thesis",
    ]),
  ea(18,
    "Part 1 (Introduction): Thesis — bracket creep is a hidden, automatic tax increase that raises the average tax burden and government revenue over time, and governments periodically cut tax thresholds or rates to return this 'over-collection'. Key terms: bracket creep (fiscal drag), marginal tax rate, average tax rate, nominal vs real income, progressive tax, indexation.\n" +
    "Part 2 (Point 1 — core concept): Explain bracket creep: with a progressive income tax and unindexed thresholds, when wages rise (even just to keep pace with inflation), more income is taxed at higher marginal rates and some taxpayers move into higher brackets, so the average tax rate rises without any legislated change.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the effects. For taxpayers: real (inflation-adjusted) disposable income falls even if pre-tax real income is unchanged — a decline in living standards and a rising effective tax burden that hits middle-income earners hardest. For government: revenue grows faster than the economy, which quietly improves the Budget balance and can fund spending or 'give back' tax cuts. It also weakens work incentives at the margin.\n" +
    "Part 4 (Point 3 — trade-offs): Why governments adjust thresholds: to prevent a permanent, unlegislated rise in the tax burden and to deliver politically popular tax cuts. Trade-offs: full indexation would remove a source of automatic Budget repair and a flexible fiscal lever; periodic discretionary cuts let governments time relief but create uncertainty and can be poorly targeted.\n" +
    "Part 5 (Conclusion): Synthesise — bracket creep steadily transfers purchasing power from taxpayers to government; periodic threshold changes correct this, trading a reliable revenue source for lower and more transparent taxation. Thesis confirmed.",
    [
      "Introduction: thesis that bracket creep is a hidden automatic tax rise that governments periodically return, with key terms (fiscal drag, marginal vs average rate)",
      "Body 1: explains how bracket creep works — progressive tax + unindexed thresholds + rising nominal wages → higher average tax rate with no legislated change",
      "Body 2: analyses the effects on taxpayers (falling real disposable income, rising effective burden) and on government (revenue grows faster than GDP, Budget repair)",
      "Body 3: discusses why governments adjust thresholds and the trade-offs (indexation vs a flexible lever / Budget repair; discretionary timing vs uncertainty)",
      "Conclusion: synthesises to 'a steady transfer to government, periodically corrected' and links to the thesis",
    ]),
  ea(19,
    "Part 1 (Introduction): Thesis — the distinction between recurrent and capital spending, and between purchases and transfers, matters because they have different effects on the economy and are chosen under competing pressures of need, cost and politics. Key terms: recurrent spending, capital spending, government purchases, transfer payments, opportunity cost, fiscal sustainability.\n" +
    "Part 2 (Point 1 — core concept): Define the categories. Recurrent spending: ongoing day-to-day costs — public sector wages, welfare payments, running schools and hospitals. Capital spending: one-off outlays on long-lived assets — roads, rail, hospitals, defence equipment. Government purchases buy a good or service and count directly in GDP; transfer payments (pensions, JobSeeker, family payments) redistribute income and only affect activity when the recipient spends them.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the effects. Capital spending adds to the economy's productive capacity and can raise long-run growth, but is 'lumpy' and slow. Recurrent spending on services supports current living standards and jobs but grows automatically with an ageing population and rising health costs. Transfers are the main redistributive tool and are strong automatic stabilisers.\n" +
    "Part 4 (Point 3 — trade-offs / priorities): Priorities are shaped by demographic pressures (ageing → health, aged care, pensions), election commitments, the state of the Budget, and the desire to be seen to invest in the future. Every dollar has an opportunity cost; recurrent spending is politically hard to unwind; and there is a temptation to favour visible capital projects over less visible service quality.\n" +
    "Part 5 (Conclusion): Synthesise — recurrent spending sustains today's services and equity, capital spending builds tomorrow's capacity, and transfers redistribute; the government's mix reflects demographic and political pressures within a Budget constraint. Thesis confirmed.",
    [
      "Introduction: thesis that the spending categories differ in economic effect and are set under competing pressures, with key terms",
      "Body 1: defines recurrent vs capital spending and government purchases vs transfer payments",
      "Body 2: analyses the different effects (capital → productive capacity/long-run growth; recurrent → current services/jobs; transfers → redistribution/automatic stabiliser)",
      "Body 3: discusses what drives priorities and the trade-offs (ageing, politics, Budget constraint, opportunity cost, visible vs invisible spending)",
      "Conclusion: synthesises the roles of the three types within a Budget constraint and links to the thesis",
    ]),
  ea(20,
    "Part 1 (Introduction): Thesis — public infrastructure investment can raise productivity, correct market failure and support demand, but the benefits must be weighed against the cost of funding it and the risk of poorly chosen projects. Key terms: infrastructure, public good, positive externality, productivity, crowding in/out, opportunity cost, public debt.\n" +
    "Part 2 (Point 1 — core concept): Context: transport, energy, water and communications networks have public-good or natural-monopoly characteristics and large positive externalities, so private markets under-invest. Governments fund them directly, through government business enterprises, or via public-private partnerships.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the economic case. Well-chosen infrastructure lowers business costs, reduces congestion, connects workers to jobs and expands the economy's productive capacity — a rightward shift of long-run aggregate supply and higher potential growth. In the short run, construction spending is a fiscal injection that supports demand and employment (and can 'crowd in' private investment).\n" +
    "Part 4 (Point 3 — trade-offs): Funding it means higher taxes, cutting other spending, or borrowing (adding to debt and interest). Projects can be chosen for political rather than economic reasons, suffer cost blowouts and delays, or duplicate capacity. User charges (tolls) improve efficiency but can be regressive. There is also the timing risk of adding to demand when the economy is already at capacity.\n" +
    "Part 5 (Conclusion): Synthesise — there is a solid economic case for government infrastructure investment on productivity and market-failure grounds, conditional on rigorous project selection and a funding approach that does not undermine fiscal sustainability. Thesis confirmed.",
    [
      "Introduction: thesis that infrastructure investment has strong benefits but real funding and selection risks, with key terms (public good, positive externality, productivity)",
      "Body 1: sets the context — infrastructure has public-good / natural-monopoly features and externalities, so markets under-invest",
      "Body 2: develops the economic case (raises productivity / potential output; short-run demand support / crowding in)",
      "Body 3: analyses the trade-offs (funding via tax/cuts/debt; political project selection and cost blowouts; regressive user charges; demand timing)",
      "Conclusion: synthesises to 'solid case, conditional on good selection and sustainable funding' and links to the thesis",
    ]),
  ea(21,
    "Part 1 (Introduction): Thesis — the RBA raises the cash rate to slow demand and bring inflation back to its 2–3% target, and a rate rise reduces spending and investment across the economy, with the burden falling unevenly. Key terms: Reserve Bank of Australia, monetary policy, cash rate, transmission mechanism, aggregate demand, inflation targeting.\n" +
    "Part 2 (Point 1 — core concept): Explain the RBA's role: it is Australia's central bank and sets monetary policy to achieve price stability (2–3% inflation on average), full employment and the economic prosperity and welfare of Australians. It changes the cash rate — the interest rate on overnight loans between banks — which flows through to the interest rates households and businesses face.\n" +
    "Part 3 (Point 2 — mechanism): Analyse a cash rate increase through the transmission mechanism. Higher lending rates raise mortgage repayments, cutting the disposable income of borrowers and their consumption (the cash-flow channel); saving becomes more attractive; the cost of business borrowing rises, so investment falls; asset prices (housing, shares) soften, reducing wealth and confidence; and higher rates tend to appreciate the dollar, making imports cheaper and exports dearer. Lower aggregate demand relative to supply reduces inflationary pressure — but with a lag of 12–18 months.\n" +
    "Part 4 (Point 3 — trade-offs): Costs: rate rises hit recent borrowers and low-income mortgaged households hardest while benefiting savers, so they are regressive in the short run; they can push the economy toward recession and higher unemployment if overdone; renters are affected indirectly through investor costs; and monetary policy is a blunt tool that cannot target particular regions or sectors.\n" +
    "Part 5 (Conclusion): Synthesise — a cash rate increase is the RBA's main tool for controlling inflation, working by dampening demand through several channels, but it operates with a lag and imposes uneven costs, which is the central dilemma of monetary policy. Thesis confirmed.",
    [
      "Introduction: thesis that the RBA raises the cash rate to slow demand and curb inflation, with uneven effects, and names key terms",
      "Body 1: explains the RBA's role and objectives and what the cash rate is",
      "Body 2: analyses a rate rise through the transmission mechanism (cash-flow/consumption, saving, investment, asset prices/wealth, exchange rate) and the lag",
      "Body 3: identifies the trade-offs (regressive short-run impact, recession risk, bluntness, renters affected indirectly)",
      "Conclusion: synthesises to 'main inflation tool, lagged and uneven' and links to the thesis",
    ]),
  ea(22,
    "Part 1 (Introduction): Thesis — with inflation still above target (around 3.5–3.8%) the RBA has held the cash rate at a restrictive 4.35% to keep demand growth below supply growth until inflation is sustainably back in the 2–3% band, accepting the cost of weaker growth. Key terms: restrictive/contractionary monetary policy, neutral cash rate, inflation target, real interest rate, output gap, soft landing.\n" +
    "Part 2 (Point 1 — core concept): Context: after the post-pandemic inflation surge, the RBA lifted the cash rate rapidly. Inflation has fallen from its peak but remains 'sticky' above 3%, particularly in services, rents and insurance, so the RBA judges policy needs to stay restrictive (above the estimated neutral rate) rather than easing prematurely.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the effects of holding rates high. Mortgage rates stay elevated, so borrowers' disposable incomes and consumption remain squeezed; business investment is subdued; the housing market and construction are constrained; and a relatively high interest rate supports the dollar, dampening imported inflation. Keeping demand growth below the economy's supply capacity gradually reduces underlying inflation, ideally without a large rise in unemployment (a 'soft landing').\n" +
    "Part 4 (Point 3 — trade-offs): The RBA faces a real dilemma. Ease too soon and inflation becomes entrenched, forcing harsher tightening later; keep policy tight too long and the economy tips into recession with rising unemployment. The burden is uneven — mortgaged households vs savers, and cost-of-living pressure persists. Fiscal cost-of-living support can also work against the RBA's tightening.\n" +
    "Part 5 (Conclusion): Synthesise — holding the cash rate at 4.35% reflects the RBA prioritising getting inflation sustainably back to target over short-term growth, a judgement about the risks of moving too early versus too late. Thesis confirmed.",
    [
      "Introduction: thesis that the RBA holds rates restrictive at 4.35% to return inflation to 2-3%, accepting weaker growth, with key terms (restrictive policy, neutral rate)",
      "Body 1: sets the context — post-pandemic inflation surge, rates lifted quickly, inflation now sticky above target (services/rents/insurance)",
      "Body 2: analyses the effects of holding rates high (subdued consumption/investment/housing; higher AUD dampening imported inflation; demand kept below supply → falling underlying inflation)",
      "Body 3: identifies the dilemma / trade-offs (ease too soon vs too late, uneven burden, fiscal support working against tightening)",
      "Conclusion: synthesises to 'prioritising inflation over short-term growth; a risk-management judgement' and links to the thesis",
    ]),
  ea(23,
    "Part 1 (Introduction): Thesis — a cash rate change reaches the wider economy through several channels that together move aggregate demand and, eventually, inflation, but the process takes 12–18 months, which makes monetary policy hard to time. Key terms: cash rate, transmission mechanism, cash-flow channel, cost of credit, wealth effect, exchange rate channel, monetary policy lag.\n" +
    "Part 2 (Point 1 — core concept): Explain that the cash rate is the RBA's operational target; changes in it flow through to the interest rates banks charge and pay, and from there to the spending and saving decisions of households and firms.\n" +
    "Part 3 (Point 2 — mechanism): Work through the channels for a rate rise: (i) cash-flow / consumption — higher mortgage repayments cut borrowers' disposable income and spending; (ii) cost of credit — dearer borrowing reduces household purchases of durables and housing and reduces business investment; (iii) asset prices / wealth — lower house and share prices reduce wealth and confidence, further cutting consumption; (iv) exchange rate — higher relative rates attract capital inflow, appreciating the dollar, so exports fall and imports (and imported inflation) fall; (v) savings — a higher return encourages saving over spending. The net effect is lower aggregate demand and, with a lag, lower inflation.\n" +
    "Part 4 (Point 3 — the lag / limitations): The lags arise because loans reprice gradually, households and firms adjust plans slowly, and price and wage setting responds over time. This means the RBA must act on forecasts; if it waits for actual inflation data, it will be too late, and it risks over- or under-tightening. Policy can also be blunted if confidence or fiscal policy pulls the other way.\n" +
    "Part 5 (Conclusion): Synthesise — a cash rate change is amplified across the economy through the cash-flow, credit, wealth and exchange-rate channels, all pointing the same way, but the 12–18-month lag is the core difficulty of using it to stabilise the economy. Thesis confirmed.",
    [
      "Introduction: thesis that a cash rate change moves demand and inflation through several channels, but with a long lag that complicates timing, with key terms",
      "Body 1: explains that the cash rate is the operational target and flows through to the rates households and firms face",
      "Body 2: works through the transmission channels (cash-flow/consumption, cost of credit/investment, wealth, exchange rate, saving) for a rate change",
      "Body 3: explains why the lag exists (gradual loan repricing, slow plan adjustment, staggered price/wage setting) and its implications (act on forecasts; over/under-shoot risk)",
      "Conclusion: synthesises to 'amplified but lagged' and links to the thesis",
    ]),
  ea(24,
    "Part 1 (Introduction): Thesis — a cash rate cut is expansionary: it lifts spending and investment, raises asset prices, lowers the dollar and supports economic activity, but it also cuts returns to savers and can inflate asset prices. Key terms: expansionary monetary policy, cash rate, transmission mechanism, wealth effect, exchange rate, aggregate demand.\n" +
    "Part 2 (Point 1 — core concept): Explain that the RBA cuts the cash rate when it wants to stimulate a weak economy or lift below-target inflation, and that the cut passes through to lower lending and deposit rates across the economy.\n" +
    "Part 3 (Point 2 — mechanism): Analyse the effects. Borrowers: lower mortgage and business loan rates raise disposable income and cut the cost of investment, so consumption and investment rise. Savers: lower deposit rates reduce interest income, encouraging spending over saving. Asset prices: cheaper credit and lower discount rates push up house and share prices, raising wealth and confidence (the wealth effect). Exchange rate: lower relative returns cause capital outflow and a depreciation, making exports more competitive and imports dearer, boosting net exports (but adding to imported inflation). Net effect: higher aggregate demand and upward pressure on inflation and employment.\n" +
    "Part 4 (Point 3 — trade-offs): Trade-offs: a cut redistributes toward borrowers and away from retirees and savers; it can fuel excessive borrowing and house-price rises, worsening affordability and financial stability risk; near the 'zero lower bound' further cuts have little effect; and if inflation is already near target, easing risks overshooting.\n" +
    "Part 5 (Conclusion): Synthesise — a cash rate decrease works through the same channels as an increase but in reverse, supporting activity; the main costs are the hit to savers and the risk of inflating asset prices and household debt. Thesis confirmed.",
    [
      "Introduction: thesis that a cash rate cut is expansionary but hurts savers and can inflate asset prices, with key terms",
      "Body 1: explains why/when the RBA cuts and that the cut passes through to lower lending and deposit rates",
      "Body 2: analyses the effects through the channels — borrowers, savers, asset prices/wealth, exchange rate — leading to higher aggregate demand",
      "Body 3: identifies the trade-offs (redistribution to borrowers, asset-price/debt risk, financial stability, zero lower bound, overshoot risk)",
      "Conclusion: synthesises to 'same channels in reverse; costs to savers and asset prices' and links to the thesis",
    ]),
  ea(25,
    "Part 1 (Introduction): Thesis — monetary policy is a flexible, fast-acting stabilisation tool controlled by an independent central bank, but it is blunt, works with long lags and has uneven distributional effects, so it cannot manage the economy alone. Key terms: monetary policy, cash rate, RBA independence, transmission lag, blunt instrument, aggregate demand.\n" +
    "Part 2 (Point 1 — core concept): Explain how monetary policy works: the RBA adjusts the cash rate to move interest rates, spending and investment, and hence aggregate demand and inflation, aiming for 2–3% inflation over time.\n" +
    "Part 3 (Point 2 — strengths): Analyse the strengths: it can be changed quickly and frequently (monthly Board meetings), unlike the annual Budget; it is decided by an independent, technically focused central bank, insulating it from the political cycle; it is countercyclical and has a broad reach across the whole economy; and clear inflation targeting anchors expectations.\n" +
    "Part 4 (Point 3 — limitations): Analyse the limitations: the 12–18-month transmission lag means the RBA must act on uncertain forecasts; it is a blunt instrument that cannot target specific regions or sectors; its effects are uneven (mortgaged households vs savers vs renters); it is less effective near the zero lower bound or when confidence is very weak ('pushing on a string'); and it can be undermined by fiscal policy or global forces (commodity prices, exchange rate).\n" +
    "Part 5 (Conclusion): Synthesise — monetary policy is the primary short-term stabilisation tool because of its speed and independence, but its lags, bluntness and distributional effects mean it works best alongside fiscal policy rather than on its own. Thesis confirmed.",
    [
      "Introduction: thesis that monetary policy is fast and flexible but blunt, lagged and uneven, so it cannot act alone, with key terms",
      "Body 1: explains how monetary policy works (cash rate → rates → demand → inflation; 2-3% target)",
      "Body 2: analyses the strengths (speed/flexibility, RBA independence from politics, broad reach, expectations anchoring)",
      "Body 3: analyses the limitations (transmission lag, bluntness, uneven distributional effects, zero lower bound, undermined by fiscal/global forces)",
      "Conclusion: synthesises to 'primary short-term tool, best used with fiscal policy' and links to the thesis",
    ]),
  ea(26,
    "Part 1 (Introduction): Thesis — inflation is a sustained rise in the general price level with several possible causes, and when it persists it erodes real incomes and savings, redistributes wealth and creates uncertainty, hurting some groups far more than others. Key terms: inflation, CPI, demand-pull inflation, cost-push inflation, inflationary expectations, real income, real interest rate.\n" +
    "Part 2 (Point 1 — core concept): Define inflation and how it is measured (the percentage change in the Consumer Price Index). Distinguish headline from underlying (trimmed mean) inflation.\n" +
    "Part 3 (Point 2 — causes and mechanism): Outline the causes. Demand-pull: aggregate demand grows faster than the economy's capacity to supply, so prices are bid up (e.g. strong spending after stimulus). Cost-push: rising input costs — wages, energy, imported goods after a currency depreciation, supply-chain disruptions — push firms' costs and prices up. Inflationary expectations: if people expect high inflation, they build it into wage claims and price setting, making it self-perpetuating.\n" +
    "Part 4 (Point 3 — effects / who is hurt): Analyse the distributional effects. Real wages fall where nominal wages lag prices, hitting lower-income and award-reliant workers hardest. Savers and people on fixed incomes (retirees) lose purchasing power; borrowers with fixed-rate debt gain as the real value of debt falls. Uncertainty discourages investment and long-term contracts, and 'bracket creep' quietly raises the tax burden. If Australia's inflation exceeds its trading partners', export competitiveness falls.\n" +
    "Part 5 (Conclusion): Synthesise — inflation can be driven by demand, costs or expectations, and persistent inflation is costly because it erodes real incomes and savings unevenly and distorts decisions; this is why price stability is a central objective of policy. Thesis confirmed.",
    [
      "Introduction: thesis that inflation has several causes and persistent inflation erodes real incomes/savings unevenly, with key terms (CPI, demand-pull, cost-push, expectations)",
      "Body 1: defines inflation and its measurement (CPI; headline vs underlying)",
      "Body 2: outlines the causes with mechanisms (demand-pull, cost-push, inflationary expectations)",
      "Body 3: analyses the distributional effects (real wages, savers/retirees vs borrowers, uncertainty/investment, bracket creep, export competitiveness)",
      "Conclusion: synthesises to 'costly and uneven; hence price stability is a policy objective' and links to the thesis",
    ]),
  ea(27,
    "Part 1 (Introduction): Thesis — 'sticky' prices — services, rents, insurance and administered prices — adjust slowly, so inflation can stay above target long after the initial shock, which forces the RBA to keep policy restrictive for longer than it would like. Key terms: sticky prices, services inflation, administered prices, underlying inflation, inflation persistence, wage-price dynamics.\n" +
    "Part 2 (Point 1 — core concept): Context: after the initial burst of goods and energy inflation faded, Australian inflation stopped falling as quickly because the remaining pressure is concentrated in services and housing costs, which move slowly.\n" +
    "Part 3 (Point 2 — why some prices are sticky): Explain the mechanisms. Services are labour-intensive, so their prices track wages, which are set in annual rounds and enterprise agreements and are slow to adjust. Rents adjust only at lease renewal and follow a tight housing market with a lag. Insurance premiums reset annually and reflect past claims and reinsurance costs. Many prices are 'administered' (set by regulators or contracts) or are only reviewed periodically ('menu costs'). Firms are also reluctant to cut prices for fear of signalling weakness.\n" +
    "Part 4 (Point 3 — the challenge for the RBA): Analyse the dilemma. Because the last part of the inflation fight is slow, the RBA must keep the cash rate restrictive for an extended period, squeezing households and risking a downturn, or accept inflation settling above 2–3% and losing credibility. Sticky prices also mean the effects of past rate rises are still working through, so there is a risk of over-tightening. Wage-price feedback can prolong the process further.\n" +
    "Part 5 (Conclusion): Synthesise — price stickiness in services and housing explains why the 'last mile' of disinflation is hard; it obliges the RBA to hold policy tight for longer, extending the cost-of-living squeeze, in order to protect the inflation target. Thesis confirmed.",
    [
      "Introduction: thesis that sticky services/rents/insurance prices keep inflation above target for longer, forcing prolonged restrictive policy, with key terms",
      "Body 1: sets the context — goods/energy inflation faded but services and housing costs kept inflation elevated",
      "Body 2: explains WHY these prices are sticky (labour-intensive services track annually-set wages; rents reset at lease renewal; insurance resets yearly; administered prices; menu costs; reluctance to cut)",
      "Body 3: analyses the RBA's dilemma (hold rates restrictive for longer and risk a downturn vs accept above-target inflation and lose credibility; over-tightening risk; wage-price feedback)",
      "Conclusion: synthesises to 'sticky prices make the last mile hard and prolong tight policy' and links to the thesis",
    ]),
  ea(28,
    "Part 1 (Introduction): Thesis — the cost-of-living crisis has not affected all Australians equally: renters and recent mortgage holders have been hit hardest, while outright home owners and net savers have been more insulated, so the crisis has widened effective inequality. Key terms: cost of living, real disposable income, housing tenure, real interest rate, distributional effect, wealth effect.\n" +
    "Part 2 (Point 1 — core concept): Context: from the early 2020s, prices of essentials (energy, food, rent, insurance) rose sharply while the RBA lifted the cash rate to 4.35%. The combined squeeze on household budgets is felt through both higher prices and, for borrowers, higher interest costs.\n" +
    "Part 3 (Point 2 — mechanism, group by group): Analyse. Mortgage holders (especially those who borrowed near the peak) face large repayment increases that cut disposable income sharply — the cash-flow channel. Renters face rapid rent growth in a tight market with little buffer and no offsetting asset. Low-income earners spend a larger share of income on essentials, so a given rate of inflation cuts their real income more, and they have fewer savings to draw on. Retirees and net savers on fixed incomes lose purchasing power to inflation but gain from higher deposit rates; outright owners avoid both rent and mortgage shocks.\n" +
    "Part 4 (Point 3 — implications / limitations of policy): The crisis has increased financial stress, mortgage arrears and rental hardship concentrated among younger and lower-income households, effectively widening inequality even though measured wage inequality changed little. Government cost-of-living relief (energy rebates, rent assistance, tax cuts) has cushioned some of this but is partly untargeted and risks adding to demand.\n" +
    "Part 5 (Conclusion): Synthesise — the same macro shock (high inflation plus higher rates) produces very different outcomes depending on housing tenure, income and savings, concentrating the pain on renters and recent borrowers and widening effective inequality. Thesis confirmed.",
    [
      "Introduction: thesis that the crisis hit renters and recent mortgage holders hardest, widening effective inequality, with key terms (real disposable income, housing tenure)",
      "Body 1: sets the context — sharp rises in essential prices plus the cash rate at 4.35% squeezing budgets through prices and interest costs",
      "Body 2: analyses the impact group by group (mortgage holders, renters, low-income earners, retirees/savers, outright owners) with mechanisms",
      "Body 3: discusses the implications (concentrated financial stress, effective inequality widening) and the limits of cost-of-living relief",
      "Conclusion: synthesises to 'same shock, very different outcomes by tenure/income/savings' and links to the thesis",
    ]),
  ea(29,
    "Part 1 (Introduction): Thesis — interest rates are the key short-term driver of housing affordability, but the deeper affordability problem is structural (demand outstripping a slow supply), so monetary policy and short-term government schemes can only do so much. Key terms: housing affordability, interest rates, borrowing capacity, price-to-income ratio, housing supply elasticity, demand-side subsidy.\n" +
    "Part 2 (Point 1 — core concept): Explain the interest-rate link. Most Australian home loans are variable-rate; a lower cash rate raises borrowing capacity (a given repayment services a larger loan), boosting demand and prices, while a higher cash rate does the reverse for buyers but raises repayments (and rents, via investor costs) for existing borrowers and tenants. So affordability has both a 'purchase' and a 'servicing' dimension.\n" +
    "Part 3 (Point 2 — the structural problem / mechanism): Analyse why affordability keeps deteriorating over the long run: population growth and smaller households raise demand; tax settings (capital gains discount, negative gearing) and superannuation encourage housing investment; and the supply of well-located housing is price-inelastic because of planning restrictions, infrastructure limits and construction lead times. On a demand-supply diagram with steep supply, demand growth raises price far more than quantity.\n" +
    "Part 4 (Point 3 — policy effectiveness / trade-offs): Evaluate policy. RBA rate changes move affordability up and down but cannot fix the trend and impose costs on borrowers. Demand-side help (first-home buyer grants, shared-equity schemes) mostly adds to demand and prices unless matched by supply. Supply-side reform (planning, social and affordable housing, infrastructure) is the durable fix but is slow, faces local resistance, and is split across levels of government. Tax reform is politically hard.\n" +
    "Part 5 (Conclusion): Synthesise — interest rates set the short-term cycle in affordability, but lasting improvement requires increasing housing supply and reforming demand-side tax incentives; central-bank and short-term government measures cannot substitute for that. Thesis confirmed.",
    [
      "Introduction: thesis that interest rates drive short-term affordability but the core problem is structural (demand vs inelastic supply), so policy is limited, with key terms",
      "Body 1: explains the interest-rate link (variable rates, borrowing capacity, purchase vs servicing dimensions)",
      "Body 2: analyses the structural drivers (population/household size, tax incentives, planning/supply inelasticity) — ideally with a steep-supply diagram",
      "Body 3: evaluates the effectiveness of policy (RBA rates; demand-side grants add to prices; supply-side reform is durable but slow; tax reform politically hard)",
      "Conclusion: synthesises to 'rates set the cycle; supply and tax reform set the trend' and links to the thesis",
    ]),
  ea(30,
    "Part 1 (Introduction): Thesis — declining housing affordability results from strong, sustained demand meeting a slow, inelastic supply, so effective policy must work on both sides, and the most durable responses are supply-side and tax reform. Key terms: housing affordability, demand determinants, price elasticity of supply, planning restrictions, negative gearing, price-to-income ratio.\n" +
    "Part 2 (Point 1 — core concept): Establish the framework: house prices are set by the demand for and supply of housing; affordability is measured by the price-to-income and repayment-to-income ratios, both of which have risen over decades.\n" +
    "Part 3 (Point 2 — the mechanism, demand vs supply): Demand-side factors: population growth and immigration; smaller average household size; low interest rates over the 2010s expanding borrowing capacity; tax concessions (capital gains discount, negative gearing) and superannuation making housing an attractive investment; and the cultural and financial preference for home ownership. Supply-side factors: planning and zoning restrictions, limited well-located land, infrastructure constraints, construction costs and labour shortages, and long build times — making supply price-inelastic, so demand pressure flows mostly into prices.\n" +
    "Part 4 (Point 3 — policy responses / trade-offs): Evaluate options. Supply-side: planning reform, releasing land, government investment in social and affordable housing, infrastructure. Demand-side: reforming tax concessions; managing immigration; macro-prudential limits on risky lending. First-home buyer grants and stamp-duty concessions mostly add to demand and raise prices. Trade-offs: reform creates visible losers (investors, existing owners), planning changes face local opposition, and responsibilities are split between federal, state and local government.\n" +
    "Part 5 (Conclusion): Synthesise — affordability has fallen because demand has grown while supply has not kept pace; lasting improvement needs faster housing supply and reform of demand-side tax settings, whereas grants alone tend to be capitalised into higher prices. Thesis confirmed.",
    [
      "Introduction: thesis that affordability has fallen due to strong demand vs inelastic supply, needing action on both sides (esp. supply and tax), with key terms",
      "Body 1: establishes the demand-supply framework and how affordability is measured (price-to-income, repayment-to-income)",
      "Body 2: analyses the demand-side factors and the supply-side (inelasticity) factors as the mechanism",
      "Body 3: evaluates policy responses and trade-offs (supply reform / tax reform vs first-home grants capitalised into prices; visible losers; split responsibilities)",
      "Conclusion: synthesises to 'demand outran supply; fix supply and tax settings, not grants' and links to the thesis",
    ]),
  ea(31,
    "Part 1 (Introduction): Thesis — monetary policy is the primary short-term stabilisation tool because of its speed and independence, while fiscal policy is better for structural support and severe shocks; they are most effective when coordinated and can undermine each other when they pull in opposite directions. Key terms: monetary policy, fiscal policy, stabilisation, aggregate demand, policy lag, fiscal-monetary coordination.\n" +
    "Part 2 (Point 1 — core concept): Explain both. Monetary policy: the RBA sets the cash rate to move interest rates, spending and investment, targeting 2–3% inflation. Fiscal policy: the government uses the Budget (G and T, plus automatic stabilisers) to influence aggregate demand and the composition of activity.\n" +
    "Part 3 (Point 2 — effectiveness / mechanism): Compare. Monetary policy can be adjusted quickly and often, is set by an independent central bank free of the electoral cycle, and has broad reach — but it acts with a 12–18-month lag, is blunt, and is weak near the zero lower bound. Fiscal policy can be targeted at particular groups, regions or infrastructure, is powerful in a deep downturn (large multipliers when interest rates are low), and includes automatic stabilisers that act immediately — but discretionary changes face recognition and political lags, add to public debt, and can be hard to reverse.\n" +
    "Part 4 (Point 3 — coordination / conflict): Analyse the interaction. Coordinated (both easing in a recession, both tightening in a boom) they reinforce each other. In conflict — e.g. the RBA tightening to curb inflation while the government provides broad cost-of-living support and runs deficits — fiscal policy adds to the demand the RBA is trying to reduce, so the RBA must raise rates higher or hold them longer, worsening the burden on borrowers. RBA independence helps but does not remove the tension.\n" +
    "Part 5 (Conclusion): Synthesise — both policies can stabilise activity, with monetary policy leading in normal times and fiscal policy essential for large shocks and targeting; their combined effectiveness depends on coordination, and recent experience shows the cost when they diverge. Thesis confirmed.",
    [
      "Introduction: thesis on the complementary roles of monetary and fiscal policy and the importance of coordination, with key terms",
      "Body 1: explains how monetary policy (cash rate → demand → inflation) and fiscal policy (Budget, G/T, automatic stabilisers) each work",
      "Body 2: compares effectiveness (monetary: fast, independent, broad, but lagged/blunt/ZLB; fiscal: targeted, powerful in deep downturns, automatic stabilisers, but political lags/debt)",
      "Body 3: analyses coordination vs conflict (reinforcing when aligned; fiscal support undermining RBA tightening; RBA independence)",
      "Conclusion: synthesises to 'both can stabilise; monetary leads normally, fiscal for shocks; coordination matters' and links to the thesis",
    ]),
  ea(32,
    "Part 1 (Introduction): Thesis — when the RBA is tightening to reduce inflation while the government provides cost-of-living support, fiscal and monetary policy work against each other, forcing the RBA to keep interest rates higher for longer and shifting the burden onto borrowers. Key terms: fiscal-monetary conflict, restrictive monetary policy, fiscal stimulus/support, aggregate demand, inflation, RBA independence.\n" +
    "Part 2 (Point 1 — core concept): Context: after the inflation surge the RBA lifted and held the cash rate (around 4.35%) to slow demand, while the government continued energy rebates, rent assistance and tax cuts to ease household hardship. Both are responses to the same problem — high living costs — but through opposite mechanisms.\n" +
    "Part 3 (Point 2 — the mechanism of the tension): Analyse. The RBA is trying to reduce aggregate demand relative to supply so that underlying inflation falls. Cost-of-living support raises households' disposable income and, to the extent it is spent, adds to aggregate demand — offsetting part of the RBA's tightening. Some measures (an energy rebate) mechanically lower measured CPI in the short term but do not reduce underlying demand pressure. The net result: the RBA may need a higher peak cash rate or a longer hold to achieve the same disinflation.\n" +
    "Part 4 (Point 3 — trade-offs / resolution): The government faces a genuine dilemma: withhold support and accept real hardship among vulnerable households, or provide it and make the RBA's job harder and the eventual squeeze on borrowers deeper. Ways to reduce the conflict: make relief tightly targeted and temporary (so it eases hardship with minimal demand impact), fund it by reprioritising rather than borrowing, and design measures that ease supply-side costs rather than boost demand. RBA independence keeps monetary policy focused on inflation despite the political pressure.\n" +
    "Part 5 (Conclusion): Synthesise — fiscal support and monetary tightening pull demand in opposite directions; the tension is real but can be limited by targeting relief narrowly and funding it without adding to the deficit. Thesis confirmed.",
    [
      "Introduction: thesis that fiscal support and RBA tightening work against each other, forcing higher/longer rates and burdening borrowers, with key terms",
      "Body 1: sets the context — RBA holding rates ~4.35% to slow demand while the government provides cost-of-living support; both target high living costs by opposite means",
      "Body 2: analyses the mechanism of the tension (support raises disposable income/demand, offsetting the RBA's tightening; rebates lower headline CPI without cutting underlying demand; higher/longer peak rate needed)",
      "Body 3: discusses the government's dilemma and ways to reduce the conflict (targeted/temporary relief, fund by reprioritising, supply-side measures, RBA independence)",
      "Conclusion: synthesises to 'real tension, limitable by targeting and funding choices' and links to the thesis",
    ]),
  ea(33,
    "Part 1 (Introduction): Thesis — financial markets and intermediaries raise economic welfare by channelling savings into productive investment, spreading risk and providing liquidity, but because failures in this sector are so damaging, it is heavily regulated. Key terms: financial markets, financial intermediaries, savings and investment, liquidity, risk, primary/secondary markets, regulation.\n" +
    "Part 2 (Point 1 — core concept): Explain what the financial sector does: it connects those with surplus funds (savers, including through superannuation) to those who need funds (households, businesses, government), via banks and other intermediaries and via debt and equity markets.\n" +
    "Part 3 (Point 2 — mechanism / contribution): Analyse the benefits. Intermediation: pooling small savings and lending them in larger amounts, transforming maturity and size. Risk management: diversification, insurance and derivatives let households and firms reduce exposure to risk. Liquidity: secondary markets (the ASX, the bond market) let investors sell assets quickly, which makes people willing to fund long-term investment in the first place. Price discovery: market prices and interest rates signal where capital is most valued. For individuals this means access to home loans, returns on saving and retirement income; for firms, funds to invest and grow, raising productivity and output.\n" +
    "Part 4 (Point 3 — why regulation / trade-offs): Explain the case for regulation: information asymmetries and the risk of misconduct (ASIC — disclosure, licensing, market integrity); the systemic risk that a bank failure or a credit crunch can spread and cause a deep recession (APRA — prudential rules, capital requirements); and the need for stable payments and a lender of last resort (the RBA). Trade-offs: too little regulation risks crises and consumer harm; too much raises the cost of credit and can stifle competition and innovation (e.g. fintech).\n" +
    "Part 5 (Conclusion): Synthesise — financial markets improve welfare by turning savings into investment, managing risk and providing liquidity; regulation exists because the social cost of financial failure is so high, and the aim is a stable but competitive system. Thesis confirmed.",
    [
      "Introduction: thesis that financial markets/intermediaries raise welfare (savings→investment, risk, liquidity) but are heavily regulated because failure is so costly, with key terms",
      "Body 1: explains what the financial sector does (connects surplus to deficit units via intermediaries and debt/equity markets)",
      "Body 2: analyses the contribution to welfare (intermediation, risk management, liquidity, price discovery) for individuals and firms",
      "Body 3: explains the case for regulation (asymmetric information/misconduct → ASIC; systemic risk → APRA; payments/lender of last resort → RBA) and the trade-off (stability vs cost of credit/innovation)",
      "Conclusion: synthesises to 'welfare gains from intermediation; regulation because failure is catastrophic' and links to the thesis",
    ]),
  ea(34,
    "Part 1 (Introduction): Thesis — Australia's financial regulators (the RBA, APRA and ASIC) each address a different type of market failure in finance — systemic risk, institutional soundness and market conduct — and their combined oversight is necessary because financial failures impose large costs on the whole economy. Key terms: financial regulation, systemic risk, prudential regulation, market integrity, asymmetric information, moral hazard.\n" +
    "Part 2 (Point 1 — core concept): Establish why finance is special: it runs on confidence and information, it is highly interconnected, and a loss of confidence in one institution can trigger runs and a credit crunch that spreads to the real economy (as in the GFC). Left unregulated, private incentives do not fully account for these system-wide risks.\n" +
    "Part 3 (Point 2 — the roles / mechanism): Set out each regulator. The RBA maintains overall financial system stability and the payments system, and acts as lender of last resort to solvent banks facing a liquidity crisis. APRA is the prudential regulator: it sets capital, liquidity and governance standards for banks, insurers and superannuation funds so that they can meet their obligations to depositors and policyholders, reducing the chance and cost of failure. ASIC is the conduct and disclosure regulator: it licenses financial firms, enforces disclosure, and polices misconduct such as insider trading, misleading advice and market manipulation, protecting consumers and market integrity. The Council of Financial Regulators coordinates them.\n" +
    "Part 4 (Point 3 — why necessary / trade-offs): Explain the rationale: asymmetric information means consumers cannot assess a bank's soundness or an adviser's honesty; moral hazard from deposit guarantees needs prudential limits; and negative externalities from failure justify system-wide rules. Trade-offs: heavier regulation raises compliance costs, can reduce competition and lending, and can create a false sense of security; gaps between regulators can also let risks fall through the cracks.\n" +
    "Part 5 (Conclusion): Synthesise — the three regulators together cover stability, soundness and conduct because no single body could address all the market failures in finance, and the high social cost of financial crises makes this oversight necessary despite its costs. Thesis confirmed.",
    [
      "Introduction: thesis that the RBA/APRA/ASIC each tackle a different financial market failure and their combined oversight is necessary, with key terms (systemic risk, prudential regulation, market integrity)",
      "Body 1: explains why finance is special (confidence, information, interconnection, contagion to the real economy)",
      "Body 2: sets out each regulator's role (RBA: system stability/payments/lender of last resort; APRA: prudential soundness; ASIC: conduct/disclosure/integrity)",
      "Body 3: explains why regulation is necessary (asymmetric information, moral hazard, externalities from failure) and the trade-offs (compliance cost, competition, gaps, false security)",
      "Conclusion: synthesises to 'three failures, three regulators; necessary because crises are so costly' and links to the thesis",
    ]),
];

export const answers: AnswerSet = Object.fromEntries(answerList);
