import type { Answer, AnswerSet } from "@/lib/types";

// Answer key for y11-economics-preliminary. NO "server-only" import here (the
// validator reads it); only re-exported via content/answers/index.ts, which is
// server-only. Never import from a client component.

const U = "y11-economics-preliminary";
const p2 = (n: number) => String(n).padStart(2, "0");

function ma(n: number, correctText: string, why: string): [string, Answer] {
  return [`${U}.m${p2(n)}`, { correctText, rubric: [why] }];
}

function sa(n: number, model: string, rubric: string[]): [string, Answer] {
  return [`${U}.s${p2(n)}`, { modelAnswer: model, rubric }];
}

const mcAnswers: Array<[string, Answer]> = [
  ma(1, "unlimited wants must be satisfied using scarce (limited) resources.", "Scarcity — limited resources against unlimited wants — is the fundamental economic problem that forces choice."),
  ma(2, "the value of the next best alternative that is given up.", "Opportunity cost is the value of the next best alternative forgone when a choice is made."),
  ma(3, "Land, labour, capital and enterprise.", "The four factors of production are natural resources (land), labour, capital and entrepreneurship."),
  ma(4, "interest.", "Capital earns interest; land earns rent, labour earns wages, and enterprise earns profit."),
  ma(5, "the price mechanism — the interaction of buyers and sellers.", "In a market economy, decentralised prices set by demand and supply answer the key economic questions."),
  ma(6, "resources are unemployed or not being used efficiently.", "A point inside the PPF is attainable but wasteful — some resources are idle or misallocated."),
  ma(7, "Savings, taxation and imports.", "Leakages (S, T, M) withdraw income from the domestic circular flow; injections are I, G and X."),
  ma(8, "S + T + M = I + G + X (total leakages equal total injections).", "Equilibrium in the circular flow occurs when total leakages equal total injections, so the level of activity is stable."),
  ma(9, "rising unemployment and slowing or falling economic activity.", "A contraction means output growth slows or falls, so firms hire fewer workers and unemployment rises."),
  ma(10, "incentive function.", "A higher price raises potential profit, giving producers an incentive to expand output."),
  ma(11, "a rightward shift of the demand curve.", "Income is a non-price factor, so a change in it shifts the whole demand curve (right, for a normal good)."),
  ma(12, "a higher price and a higher quantity.", "An increase in demand against unchanged supply raises both the equilibrium price and quantity."),
  ma(13, "0.5 — demand is relatively inelastic.", "PED = %ΔQd ÷ %ΔP = 5 ÷ 10 = 0.5; a value below 1 is relatively inelastic."),
  ma(14, "is a necessity with few close substitutes.", "Necessities with no substitutes must be bought almost regardless of price, so demand barely responds."),
  ma(15, "monopoly.", "One seller, no close substitutes and very high barriers to entry defines a monopoly."),
  ma(16, "many small firms selling identical products, with no barriers to entry and no pricing power.", "Perfect competition: many price-taking firms, homogeneous product, free entry and exit."),
  ma(17, "a negative externality from production.", "The pollution is a cost imposed on third parties that is not reflected in the market price."),
  ma(18, "non-excludable and non-rival in consumption.", "A public good cannot exclude non-payers and one person's use does not reduce another's — leading to the free-rider problem."),
  ma(19, "a persistent shortage of rental housing.", "A binding ceiling holds rent below equilibrium, so quantity demanded exceeds quantity supplied."),
  ma(20, "as a person consumes more units of a good, the extra satisfaction from each additional unit falls.", "Diminishing marginal utility: each successive unit adds less to total satisfaction."),
  ma(21, "0.8.", "MPC = change in consumption ÷ change in income = 80 ÷ 100 = 0.8."),
  ma(22, "1.", "Every extra dollar of income is either consumed or saved, so MPC + MPS = 1."),
  ma(23, "falls as consumer incomes rise.", "For an inferior good, higher income leads consumers to switch to preferred alternatives, reducing demand."),
  ma(24, "consumers, through their spending decisions, ultimately determine what is produced.", "Consumer sovereignty: producers respond to consumers' purchasing choices."),
  ma(25, "the opportunity cost of the resources the owner supplies (such as their own labour and capital).", "Economic profit subtracts implicit (opportunity) costs as well as explicit costs; accounting profit subtracts only explicit costs."),
  ma(26, "long-run average cost falls as the scale of production increases.", "Economies of scale mean per-unit cost falls as output rises, up to the technical optimum."),
  ma(27, "the demand for the goods and services that the labour is used to produce.", "Labour is wanted to produce output, so its demand is derived from the demand for that output."),
  ma(28, "More people gaining the qualifications the occupation requires.", "More qualified people willing to do the work increases labour supply to that occupation."),
  ma(29, "channel funds from savers to borrowers, facilitating saving and investment.", "The financial sector's core role is intermediation between surplus and deficit units."),
  ma(30, "primary market.", "New securities issued to raise funds are a primary-market transaction; the secondary market trades existing securities."),
  ma(31, "Australia's central bank, responsible for monetary policy.", "The RBA is the central bank; it conducts monetary policy and issues currency."),
  ma(32, "the price of money — the cost of borrowing and the reward for saving.", "The interest rate is the price of credit and the return to lenders/savers."),
  ma(33, "lower the equilibrium interest rate.", "More funds supplied at each rate shifts supply right, reducing the equilibrium price of funds (the interest rate)."),
  ma(34, "lending money to the government in return for interest payments.", "A bond is a debt security; the buyer lends to the issuer and receives interest (coupons)."),
  ma(35, "less affordable, because mortgage repayments increase.", "Higher rates raise the cost of servicing a mortgage, reducing borrowing capacity and affordability."),
  ma(36, "a large pool of national savings that helps fund investment.", "Compulsory super accumulates long-term savings that are invested across the economy."),
  ma(37, "Redistribution of income.", "The syllabus identifies redistribution, reallocation, stabilisation and correction of market failure as government roles."),
  ma(38, "is levied on, and paid by, the same person or entity (for example, personal income tax).", "For a direct tax the legal and economic incidence fall on the same party; it cannot be passed on."),
  ma(39, "The Goods and Services Tax (GST).", "The GST is levied on sellers but paid by consumers in the price — an indirect tax. The others are direct taxes."),
  ma(40, "who ultimately bears the burden of the tax.", "Economic incidence identifies who actually pays, which can differ from who is legally liable."),
  ma(41, "the average rate of tax rises as a person's income rises.", "Progressive taxation takes a larger proportion of income as income increases (e.g. income tax brackets)."),
  ma(42, "simplicity, fairness (equity) and efficiency.", "A good tax is simple to understand and comply with, fair, and does not badly distort economic decisions."),
  ma(43, "The Age Pension.", "A transfer payment provides income with no good or service given in return. Wages and purchases are not transfers."),
  ma(44, "government expenditure exceeds government revenue.", "A deficit is where spending is greater than revenue over the period."),
  ma(45, "voluntary exchange lets countries specialise according to opportunity cost, and both trading partners can gain.", "Trade based on comparative advantage improves the allocation of resources and raises total output."),
  ma(46, "the value of its exports exceeds the value of its imports.", "Exports greater than imports is a trade surplus; the reverse is a deficit."),
  ma(47, "Australian exports become more expensive for US buyers, and US imports become cheaper for Australians.", "An appreciation raises the AUD's value, making exports dearer abroad and imports cheaper at home."),
  ma(48, "foreign ownership of Australian assets, such as shares in Australian companies and property.", "Foreign equity is ownership; foreign debt is borrowing that must be repaid with interest."),
  ma(49, "a record of all economic transactions between Australia and the rest of the world over a period.", "The balance of payments records trade, income and financial flows between residents and non-residents."),
  ma(50, "in which it has a lower opportunity cost than its trading partners.", "Comparative advantage is about relative opportunity cost, not absolute output or price."),
];

const saAnswers: Array<[string, Answer]> = [
  sa(1,
    "Opportunity cost is the value of the next best alternative that is given up when a choice is made. For example, if a student spends Saturday working a paid shift, the opportunity cost is the leisure or study time they could have had instead.",
    [
      "Defines opportunity cost as the value of the next best alternative forgone",
      "Gives a valid example that identifies the alternative given up",
    ]),
  sa(2,
    "A PPF shows the maximum combinations of two goods an economy can produce with its resources fully and efficiently employed. Moving along the frontier to produce more of one good means giving up some of the other — the slope shows the opportunity cost. Points on the frontier are efficient; points inside are inefficient (resources idle or misallocated); points outside are unattainable with current resources and technology.",
    [
      "Explains the PPF shows maximum output combinations with resources fully/efficiently used",
      "Explains that moving along it involves an opportunity cost (giving up one good for the other)",
      "Distinguishes efficient (on the frontier) from inefficient (inside) points",
    ]),
  sa(3,
    "In a free market economy the key economic questions are answered by the price mechanism — private individuals and firms make decisions guided by prices, profits and self-interest, with little government direction. In a planned (command) economy a central authority owns most resources and directs what is produced, how, and for whom.",
    [
      "States a free market economy relies on the price mechanism / private decision-making",
      "States a planned economy relies on central government ownership and direction of resources",
    ]),
  sa(4,
    "The circular flow of income model shows income and spending flowing between five sectors: households, businesses, the financial sector, the government sector and the international sector. Injections add to the flow: investment (I), government spending (G) and exports (X). Leakages withdraw from the flow: savings (S), taxation (T) and imports (M).",
    [
      "Describes income/spending flowing between the sectors (households, firms, and financial/government/overseas)",
      "Identifies the injections: investment, government spending, exports",
      "Identifies the leakages: savings, taxation, imports",
    ]),
  sa(5,
    "When total leakages (S + T + M) exceed total injections (I + G + X), more income is being withdrawn from the circular flow than is being added back. Spending and production fall, so the level of economic activity contracts — output declines and unemployment tends to rise — until a new, lower equilibrium is reached.",
    [
      "States that leakages exceeding injections means net income is withdrawn from the flow",
      "Explains that spending and production therefore fall",
      "Concludes the level of economic activity contracts toward a lower equilibrium",
    ]),
  sa(6,
    "Economies pursue higher GDP because it generally allows higher average incomes and material living standards, and because a growing economy creates more jobs, reducing unemployment. Higher output also gives governments more tax revenue to fund services.",
    [
      "Reason 1: higher GDP raises average incomes / material living standards",
      "Reason 2: growth creates employment / reduces unemployment (or: more tax revenue for services)",
    ]),
  sa(7,
    "A cognitive bias is a systematic error in the way people think and make decisions, which departs from the rational, self-interested behaviour assumed in conventional economic models. For example, loss aversion means people feel the pain of a loss more strongly than the pleasure of an equal gain, so they may hold a falling investment too long.",
    [
      "Defines a cognitive bias as a systematic departure from rational decision-making",
      "Gives a valid example (e.g. anchoring, loss aversion, overconfidence, sunk cost fallacy) and explains it briefly",
    ]),
  sa(8,
    "In a market economy the price mechanism answers the key questions. 'What to produce' is decided by consumer demand — firms produce goods that are profitable to sell. 'How to produce' is decided by producers seeking the lowest-cost combination of resources given input prices. 'For whom to produce' is decided by the distribution of income — goods go to those willing and able to pay the price.",
    [
      "'What': consumer demand / profitability guides which goods are produced",
      "'How': producers choose the least-cost method given relative input prices",
      "'For whom': output is allocated to those able and willing to pay (distribution of income)",
    ]),
  sa(9,
    "Each factor of production earns a corresponding factor income: land earns rent, labour earns wages, capital earns interest, and enterprise (entrepreneurship) earns profit. These payments are the cost of the resource to the firm and the income of the resource owner.",
    [
      "Matches at least three factors to their incomes (land–rent, labour–wages, capital–interest, enterprise–profit)",
      "Notes these payments are both a cost to firms and income to resource owners",
    ]),
  sa(10,
    "A rise in the cost of production means firms are willing to supply less of the good at every price, so the supply curve shifts to the left (a decrease in supply). With demand unchanged, this raises the equilibrium price and reduces the equilibrium quantity traded.",
    [
      "States supply decreases — the supply curve shifts left",
      "States the equilibrium price rises",
      "States the equilibrium quantity falls",
    ]),
  sa(11,
    "The price elasticity of demand is calculated as the percentage change in quantity demanded divided by the percentage change in price. A value of 0.4 means that a 1% change in price causes only a 0.4% change in quantity demanded (in the opposite direction). Because it is less than 1, demand is relatively price-inelastic — quantity demanded is not very responsive to price.",
    [
      "States the formula: % change in quantity demanded ÷ % change in price",
      "Interprets 0.4 as quantity demanded changing proportionally less than price",
      "Concludes demand is relatively inelastic (value < 1)",
    ]),
  sa(12,
    "Demand is more price-inelastic when the good is a necessity that consumers must keep buying even if the price rises, and when it has few or no close substitutes, so consumers cannot switch away when the price rises. (Other valid factors: the good takes up only a small share of income, or there is little time to adjust.)",
    [
      "Factor 1: the good is a necessity (must be bought regardless of price)",
      "Factor 2: few or no close substitutes, so consumers cannot switch away",
    ]),
  sa(13,
    "Under perfect competition there are many small firms selling an identical product, there are no barriers to entry or exit, and each firm is a price taker with no power to set the price. Under monopoly there is a single firm with no close substitutes, protected by very high barriers to entry, and it has significant power to set the price (a price maker).",
    [
      "Number of firms: perfect competition has many; monopoly has one",
      "Barriers to entry: none / very low for perfect competition; very high for monopoly",
      "Pricing power: perfectly competitive firms are price takers; a monopolist is a price maker",
    ]),
  sa(14,
    "A negative externality from production is a cost of producing a good that is borne by third parties, not by the producer or the buyer — for example, pollution from a factory. Because the producer does not pay this social cost, the market price is too low and the quantity produced is too high compared with the level that is best for society. Resources are over-allocated to the good, which is market failure.",
    [
      "Defines a negative production externality as a cost imposed on third parties, not paid by the producer or consumer",
      "Explains that the market price is too low / quantity too high because the social cost is ignored",
      "Concludes resources are misallocated (over-produced) — market failure",
    ]),
  sa(15,
    "A public good is non-excludable (people who do not pay cannot be prevented from using it) and non-rival (one person's use does not reduce the amount available to others) — for example, national defence or street lighting. The free-rider problem is that, because non-payers cannot be excluded, individuals have an incentive not to pay, so a private market would under-provide or not provide the good at all.",
    [
      "Defines a public good as non-excludable and non-rival (or gives a valid example demonstrating both)",
      "Explains the free-rider problem: non-payers cannot be excluded, so private provision fails / is under-provided",
    ]),
  sa(16,
    "A per-unit subsidy paid to producers lowers their effective cost of production, so the supply curve shifts to the right. This lowers the price paid by consumers and raises the quantity traded. In terms of resource allocation, more resources are drawn into producing this good than the free market alone would direct — output is pushed above the unsubsidised equilibrium level.",
    [
      "States the subsidy shifts supply right, lowering the price and raising the quantity traded",
      "States producers receive the market price plus the subsidy",
      "Explains that more resources are allocated to this good than the free market would (over-allocation)",
    ]),
  sa(17,
    "Government intervention can itself create inefficiency (government failure). For example, a price ceiling set to help consumers can cause a persistent shortage and non-price rationing such as queues or a black market; or the cost of administering and enforcing a policy can outweigh the benefit; or policies can be distorted by rent-seeking.",
    [
      "Identifies a valid limitation (unintended consequences, administration/enforcement cost, rent-seeking, distorted incentives)",
      "Briefly explains how that limitation reduces the effectiveness or efficiency of the intervention",
    ]),
  sa(18,
    "If demand for a firm's product is price-inelastic, the firm can raise its price and increase total revenue, because the quantity sold falls proportionally less than the price rises. If demand is price-elastic, raising the price reduces total revenue, so the firm is more likely to hold or lower its price and may try to make demand less elastic through product differentiation and branding.",
    [
      "States that with inelastic demand a price rise increases total revenue",
      "States that with elastic demand a price rise reduces total revenue (hold or cut price)",
      "Links elasticity to the firm's strategy (e.g. differentiation to reduce elasticity, or output/pricing decisions)",
    ]),
  sa(19,
    "The law of diminishing marginal utility states that as a person consumes successive units of a good in a given period, the additional (marginal) satisfaction from each extra unit falls. For example, the first slice of pizza gives a lot of satisfaction, the second less, and by the fifth slice the extra satisfaction is small or even negative.",
    [
      "States that marginal (extra) utility falls as more units are consumed",
      "Gives a valid example showing the extra satisfaction declining with each unit",
    ]),
  sa(20,
    "The marginal propensity to consume (MPC) is the proportion of each extra dollar of income that a household spends on consumption, calculated as the change in consumption divided by the change in income. Here MPC = 150 ÷ 200 = 0.75.",
    [
      "Defines MPC as the fraction of extra income that is consumed (ΔC ÷ ΔY)",
      "Calculates MPC = 150 ÷ 200 = 0.75",
    ]),
  sa(21,
    "A household's income is either spent on consumption or saved: income = consumption + saving. As income rises, consumption rises but usually by less than the full increase, so saving also rises. The marginal propensity to consume (the extra spent) plus the marginal propensity to save (the extra saved) add to 1.",
    [
      "States income is divided between consumption and saving",
      "Explains that as income rises, consumption rises (typically by less than the income rise) and saving rises",
      "Notes MPC + MPS = 1",
    ]),
  sa(22,
    "For a normal good, demand rises when consumer income rises and falls when income falls. For an inferior good, the relationship is reversed: demand falls as income rises, because consumers switch to more preferred (often more expensive) alternatives.",
    [
      "States a normal good: demand rises as income rises",
      "States an inferior good: demand falls as income rises",
    ]),
  sa(23,
    "The supply of labour by households is affected by: the wage and non-wage benefits offered (higher pay and better conditions attract more workers); the size of the working-age population and the workforce participation rate; and the education, training and skills required (harder entry reduces the number able to supply that labour). Occupational and geographic mobility also matter.",
    [
      "Factor 1: wage and non-wage benefits / working conditions",
      "Factor 2: population size and/or workforce participation rate",
      "Factor 3: education, training and skills required (or occupational/geographic mobility)",
    ]),
  sa(24,
    "Accounting profit is total revenue minus the explicit (paid) costs of the business, such as wages, rent and materials. Economic profit is total revenue minus both explicit costs and implicit costs — the opportunity cost of the resources the owner contributes, such as their own time and capital. Economic profit is therefore smaller than accounting profit.",
    [
      "Defines accounting profit as revenue minus explicit (paid) costs",
      "Defines economic profit as revenue minus explicit AND implicit (opportunity) costs",
    ]),
  sa(25,
    "Productivity is output per unit of input (for example, output per hour worked). When productivity rises, the same resources produce more goods and services, so real output and real incomes per person can rise. Over time, growth in productivity is the main source of improvements in material living standards.",
    [
      "Defines productivity as output per unit of input",
      "Explains that higher productivity means more output / higher real income from the same resources",
      "Concludes productivity growth is the main driver of rising living standards over time",
    ]),
  sa(26,
    "Economies of scale occur when, as a firm increases its scale of production, its long-run average cost falls — for example, because it can spread fixed costs over more units or use more specialised equipment. Diseconomies of scale occur when the firm becomes so large that long-run average cost rises — for example, because management becomes harder to coordinate. On a long-run average cost curve, the curve slopes down over the range of economies of scale and slopes up over the range of diseconomies.",
    [
      "Defines economies of scale: LRAC falls as scale increases (with a valid reason)",
      "Defines diseconomies of scale: LRAC rises as scale increases (with a valid reason)",
      "Links both to the shape of the LRAC curve (downward then upward sloping)",
    ]),
  sa(27,
    "The minimum wage is a legally enforced price floor for labour, setting the lowest wage an employer may pay. Its aim is to raise the incomes of low-paid workers above the level the market would set. If it is set above the equilibrium wage, it can also create a surplus of labour (unemployment), because the quantity of labour supplied exceeds the quantity demanded at that wage.",
    [
      "States the minimum wage is a legal price floor for labour intended to raise low-paid workers' incomes",
      "Notes that, if set above equilibrium, it can create a labour surplus (unemployment)",
    ]),
  sa(28,
    "Automation and AI let firms substitute capital for labour, so for routine tasks that machines can now perform, the demand for that type of labour falls (the labour demand curve shifts left), lowering wages and employment in those roles. At the same time, automation can raise the demand for workers who design, maintain or complement the technology, and can raise productivity and output, which supports labour demand elsewhere.",
    [
      "Explains that automation/AI substitutes capital for labour, reducing demand for routine/replaceable labour",
      "Explains the effect on wages and employment in the affected roles (both fall)",
      "Notes an offsetting effect (higher demand for complementary/skilled labour, or higher productivity/output)",
    ]),
  sa(29,
    "An interest rate is the price of borrowing money and the reward for saving or lending it, usually expressed as a percentage per year. It acts as the cost of credit (influencing how much households and firms borrow and spend), and as the return on savings (influencing how much people save); it can also serve as an indicator of the risk of a loan.",
    [
      "Defines the interest rate as the price of money — cost of borrowing / reward for saving",
      "Outlines two roles (e.g. cost of credit affecting borrowing and spending; return on savings; indicator of risk)",
    ]),
  sa(30,
    "In the loanable funds market, the demand for funds comes from borrowers (households, firms and government) and slopes down — more is borrowed at a lower interest rate. The supply of funds comes from savers and lenders and slopes up — more is supplied at a higher interest rate. The equilibrium interest rate is where the quantity of funds demanded equals the quantity supplied; a change in either demand or supply moves the interest rate to a new equilibrium.",
    [
      "Describes demand for funds (borrowers, downward sloping) and supply of funds (savers/lenders, upward sloping)",
      "States the equilibrium interest rate is where quantity demanded equals quantity supplied",
      "Explains that a shift in demand or supply changes the equilibrium interest rate",
    ]),
  sa(31,
    "In the primary share market a company issues new shares to investors to raise funds (for example, in a float or capital raising), so money flows to the company. In the secondary share market investors buy and sell existing shares from one another (for example, on the ASX); the company receives no new funds, but the market provides liquidity and price information.",
    [
      "Primary market: new shares issued by the company to raise funds",
      "Secondary market: trading of existing shares between investors (company gets no new funds; provides liquidity)",
    ]),
  sa(32,
    "Raising funds through debt means borrowing (for example, issuing bonds or taking a loan): the business must repay the principal and pay interest, but lenders do not gain ownership or control. Raising funds through equity means selling ownership (for example, issuing shares): there is no obligation to repay, but new shareholders share in profits (dividends) and in control of the business.",
    [
      "Debt: borrowed funds that must be repaid with interest; lenders gain no ownership",
      "Equity: funds raised by selling ownership; no repayment obligation, but ownership/profits are shared",
    ]),
  sa(33,
    "Financial intermediaries, such as banks, insurers and fund managers, sit between savers and borrowers. They collect small deposits and savings from many people and channel them to borrowers who need larger amounts, transforming the size, maturity and risk of funds. This lowers the cost and risk of matching savers with borrowers, so more saving is turned into productive investment.",
    [
      "States intermediaries channel funds from savers to borrowers",
      "Explains a transformation function (pooling small savings, matching maturities, spreading/reducing risk)",
      "Concludes this increases the flow of saving into investment / lowers transaction costs and risk",
    ]),
  sa(34,
    "The Reserve Bank of Australia is Australia's central bank. In the financial sector it issues the currency, acts as banker to the government and to the commercial banks, and helps oversee the stability of the payments system and the financial system as a whole. It also conducts monetary policy by influencing interest rates.",
    [
      "Identifies the RBA as Australia's central bank",
      "Outlines a role in the financial sector (issuing currency, banker to banks/government, payments-system / financial stability, or monetary policy)",
    ]),
  sa(35,
    "A fall in interest rates lowers the cost of borrowing and reduces the return on saving. Households are more likely to borrow and less likely to save, so consumption spending rises, especially on items bought with credit such as cars and housing. For businesses, lower rates reduce the cost of financing new projects, so more investment projects become profitable and business investment rises.",
    [
      "Explains lower rates reduce borrowing cost and the reward for saving",
      "States household consumption rises (more borrowing / less saving)",
      "States business investment rises (more projects become profitable at the lower cost of finance)",
    ]),
  sa(36,
    "Superannuation is compulsory long-term saving for retirement. Because contributions are made throughout a person's working life and cannot generally be withdrawn until retirement, super builds a very large pool of national savings. Super funds invest these savings in shares, property, bonds and infrastructure, providing a stable source of funds for investment in the Australian economy.",
    [
      "Explains super is compulsory long-term saving that accumulates a large pool of national savings",
      "Explains that super funds invest these savings, providing funds for investment in the economy",
    ]),
  sa(37,
    "Government performs several economic roles in a market economy: redistribution — using taxes and transfer payments to reduce income inequality; reallocation — using taxes, subsidies and direct provision to shift resources towards goods society values (such as health and education) and away from harmful goods; and stabilisation — using its Budget to smooth the business cycle. It also acts to correct market failure.",
    [
      "Role 1: redistribution of income (taxes and transfers)",
      "Role 2: reallocation of resources (taxes, subsidies, direct provision, correcting market failure)",
      "Role 3: stabilisation of economic activity (managing the Budget over the business cycle)",
    ]),
  sa(38,
    "A direct tax is levied on and paid by the same person or entity, so its legal incidence and economic incidence are the same and it cannot be passed on — for example, personal income tax. An indirect tax is levied on producers or sellers but is passed on to consumers through higher prices, so the legal incidence (the seller) and the economic incidence (the buyer) differ — for example, the GST.",
    [
      "Direct tax: paid by the party it is levied on; incidence not shifted (e.g. income tax)",
      "Indirect tax: levied on sellers but passed on to consumers in the price; incidence shifts (e.g. GST)",
    ]),
  sa(39,
    "A progressive tax is one in which the average rate of tax rises as income rises, so higher-income earners pay a larger proportion of their income in tax. Australia's personal income tax is progressive, because it uses rising marginal tax rates across income brackets.",
    [
      "Defines a progressive tax: the average rate of tax rises as income rises",
      "Gives a valid Australian example (personal / PAYG income tax)",
    ]),
  sa(40,
    "A good tax should be simple — easy for taxpayers to understand and comply with, and cheap for the government to collect. It should be fair (equitable) — treating people in similar circumstances alike (horizontal equity) and asking more of those with greater capacity to pay (vertical equity). It should be efficient — raising revenue without badly distorting people's decisions to work, save or invest.",
    [
      "Simplicity: easy to understand, comply with and administer",
      "Equity / fairness: horizontal and vertical equity (capacity to pay)",
      "Efficiency: minimal distortion of economic decisions",
    ]),
  sa(41,
    "Recurrent spending is ongoing, day-to-day spending on the operation of government — wages of public servants, welfare and transfer payments, and running services such as schools and hospitals. Capital (non-recurrent) spending is one-off spending on long-lived assets, such as building roads, hospitals and other infrastructure, which provide benefits over many years.",
    [
      "Recurrent: ongoing day-to-day spending (wages, transfers, running services)",
      "Capital / non-recurrent: one-off spending on long-lived assets / infrastructure",
    ]),
  sa(42,
    "A transfer payment is a payment from the government to a household or individual for which no good or service is provided in return; it transfers income rather than paying for production. Examples include the Age Pension, JobSeeker and family payments.",
    [
      "Defines a transfer payment as a government payment with no good or service received in return (income transfer)",
      "Gives a valid example (Age Pension, JobSeeker, family payments, etc.)",
    ]),
  sa(43,
    "The government can redistribute income by taxing higher-income earners at higher average rates (a progressive income tax), which reduces the gap between high and low after-tax incomes, and by using the revenue to fund transfer payments (such as pensions and unemployment benefits) and services (such as public health and education) that benefit lower-income households proportionally more. Together the tax and transfer system makes the distribution of income more equal.",
    [
      "Explains the progressive tax side: higher earners pay a larger share, reducing high after-tax incomes",
      "Explains the transfer/spending side: payments and services raise the real incomes of lower-income households",
      "Concludes the tax-transfer system makes the income distribution more equal",
    ]),
  sa(44,
    "Markets sometimes fail to allocate resources efficiently — for example, they over-produce goods with negative externalities, under-produce goods with positive externalities, do not provide public goods, and allow abuse of market power. Because these outcomes reduce society's overall wellbeing, there is a rationale for the government to intervene — using taxes, subsidies, regulation, direct provision or price controls — to move production and consumption closer to the socially efficient level.",
    [
      "Identifies that markets fail to allocate resources efficiently in certain cases (externalities, public goods, market power, etc.)",
      "Explains that these failures reduce society's wellbeing",
      "Concludes government intervention is justified to move outcomes toward the socially efficient level",
    ]),
  sa(45,
    "International trade lets each country specialise in producing the goods and services in which it has a comparative advantage (a lower opportunity cost). This raises world output and allows consumers access to a greater variety of goods, often at lower prices. Trade also lets firms sell to larger markets and gain economies of scale, and exposes them to competition that encourages efficiency and innovation.",
    [
      "Explains specialisation according to comparative advantage raises total output",
      "Explains gains to consumers (variety, lower prices) and/or firms (larger markets, economies of scale)",
      "Notes trade encourages competition, efficiency and innovation",
    ]),
  sa(46,
    "A country has a trade surplus when the value of its exports of goods and services is greater than the value of its imports over a period. It has a trade deficit when the value of its imports is greater than the value of its exports.",
    [
      "Trade surplus: exports greater than imports",
      "Trade deficit: imports greater than exports",
    ]),
  sa(47,
    "An appreciation of the Australian dollar means it buys more foreign currency. For Australian exporters, their goods become more expensive in foreign currency terms, so overseas demand for Australian exports tends to fall, reducing export revenue. For Australian importers and consumers, foreign goods become cheaper in Australian dollars, so imports rise.",
    [
      "States an appreciation raises the value of the AUD against other currencies",
      "Explains exporters are worse off: exports become dearer abroad, so export demand/revenue falls",
      "Explains importers/consumers benefit: imports become cheaper, so imports rise",
    ]),
  sa(48,
    "Foreign debt is money that Australian borrowers (governments, businesses and banks) have borrowed from overseas lenders; it must be repaid, with interest. Foreign equity is overseas ownership of Australian assets — such as shares in Australian companies, or Australian property and businesses; it does not have to be repaid, but the foreign owners receive a share of the profits (dividends).",
    [
      "Foreign debt: borrowings from overseas that must be repaid with interest",
      "Foreign equity: overseas ownership of Australian assets; no repayment, but profits/dividends flow overseas",
    ]),
  sa(49,
    "The balance of payments is a systematic record of all the economic transactions between the residents of a country and the rest of the world over a period of time. It records trade in goods and services, primary and secondary income flows, and financial and capital flows. It shows how a country is paying its way internationally and how its trade is being financed.",
    [
      "Defines the balance of payments as a record of all international transactions over a period",
      "Identifies what it records (trade in goods and services, income flows, financial/capital flows)",
      "Notes its purpose: shows how a country pays its way / finances its trade internationally",
    ]),
  sa(50,
    "Australia's domestic savings are not large enough to fund all the profitable investment opportunities in the economy — in infrastructure, mining, housing and business expansion. Foreign investment (both debt and equity) provides additional funds, allowing more investment, faster growth in productive capacity and more jobs than would be possible using domestic savings alone.",
    [
      "Explains that domestic saving is insufficient to fund all profitable domestic investment",
      "Explains that foreign investment provides extra funds, allowing more investment / growth / employment",
    ]),
];

const mcAnswers2: Array<[string, Answer]> = [
  ma(51, "A city has enough land for either a new hospital or a new school, but not both.", "Scarcity means limited resources cannot satisfy every competing want, forcing a choice between alternatives."),
  ma(52, "the economy's productive capacity increases, for example through new technology or more resources.", "An outward PPF shift reflects economic growth — more of everything can potentially be produced."),
  ma(53, "Raising the minimum wage by 10% increased unemployment among teenagers by 2%.", "A positive statement is a testable, factual claim; the others express opinions about what should happen (normative)."),
  ma(54, "the factors of production, in exchange for factor incomes.", "Households own the factors of production and supply them to firms, receiving wages, rent, interest and profit in return."),
  ma(55, "Leakages rise while injections stay the same.", "If leakages (S+T+M) exceed injections (I+G+X), spending withdrawn from the flow exceeds spending injected, contracting activity."),
  ma(56, "the point at which economic activity is at its highest before turning down.", "The peak is the top of the cycle, immediately before a contraction begins."),
  ma(57, "recognising that people do not always make perfectly rational decisions.", "Behavioural economics incorporates psychological realism, relaxing the traditional assumption of perfect rationality."),
  ma(58, "What to produce, how to produce it, and for whom to produce it.", "These three questions must be answered by any economic system, however it allocates resources."),
  ma(59, "rise and fall, respectively.", "A leftward shift of supply, with demand unchanged, raises the equilibrium price and lowers the equilibrium quantity."),
  ma(60, "A manufactured good produced by a firm with spare production capacity.", "Spare capacity lets output expand quickly when price rises, making supply more responsive (elastic)."),
  ma(61, "sells a differentiated product and has some control over its price.", "Product differentiation gives monopolistically competitive firms limited pricing power, unlike price-taking firms in perfect competition."),
  ma(62, "a small number of large firms, often interdependent in their pricing and output decisions.", "Oligopoly is defined by a few dominant firms whose decisions affect, and are affected by, their rivals."),
  ma(63, "the free market tends to under-consume the good relative to the socially optimal level.", "Because the market price ignores the external benefit to third parties, the free market under-values and under-consumes the good."),
  ma(64, "society believes should be encouraged, because it is under-consumed relative to its social benefit.", "Merit goods (e.g. education, healthcare) generate benefits beyond the individual consumer and tend to be under-consumed without support."),
  ma(65, "government intervention leads to an outcome that is less efficient than the free market would have produced.", "Government failure describes intervention that worsens, rather than improves, resource allocation."),
  ma(66, "A tax on producers equal to the external cost imposed on third parties.", "A Pigouvian tax internalises the external cost, aligning the private cost of production with its true social cost."),
  ma(67, "price equals the marginal cost of production, so resources are directed to their most valued use.", "Allocative efficiency (P = MC) ensures the value consumers place on the last unit equals its cost of production."),
  ma(68, "the marginal utility from another unit still exceeds, or equals, its price.", "A rational consumer keeps buying while the extra satisfaction from a unit is at least worth its price."),
  ma(69, "a fall in consumption, since income is either spent or saved.", "With income fixed, income = consumption + saving, so a rise in saving must be matched by a fall in consumption."),
  ma(70, "Greater confidence about future job security and income.", "Higher confidence in future income encourages households to spend more of their current income now."),
  ma(71, "average cost first falls due to specialisation of a fixed factor, then rises due to diminishing returns.", "Short-run cost curves are U-shaped: early specialisation lowers cost, then diminishing marginal returns to the variable factor raise it."),
  ma(72, "cost savings a firm achieves as it grows larger, such as buying inputs in bulk.", "Internal economies of scale are firm-specific, arising from the individual firm's own growth in scale."),
  ma(73, "equity (funds raised by selling shares).", "Equity is ownership capital with no obligation to repay; debt (loans, bonds, credit) must eventually be repaid."),
  ma(74, "is just enough to keep the owner's resources employed in this business rather than their next best alternative.", "Normal profit covers the opportunity cost of the owner's own resources — the minimum needed to keep them in this use."),
  ma(75, "more output is produced for each hour of labour worked.", "Labour productivity is output per unit of labour input, not the size of the workforce or the wage paid."),
  ma(76, "A fall in consumer demand for the industry's output.", "Because labour demand is derived from output demand, weaker demand for the product reduces the demand for the labour that makes it."),
  ma(77, "part ownership of a company, entitling the holder to a share of profits and voting rights.", "A share is an equity stake in a company, unlike debt securities such as bonds."),
  ma(78, "accepting deposits from savers and lending those funds to borrowers.", "Financial intermediation — channelling funds from savers to borrowers — is the core banking function."),
  ma(79, "investments offering higher potential returns typically carry higher risk.", "The risk-return trade-off: investors generally must accept more risk to have a chance at a higher return."),
  ma(80, "encourage borrowing and investment, since credit becomes cheaper.", "Lower rates reduce the cost of borrowing, making investment projects more attractive and affordable."),
  ma(81, "It provides a market where shares and other securities are bought and sold.", "The ASX is Australia's main securities exchange, facilitating the trading of listed shares and other financial instruments."),
  ma(82, "pooling funds from many savers and lending to a diversified range of borrowers.", "Diversification across many borrowers spreads and reduces the risk faced by any individual saver."),
  ma(83, "a fixed sum of money deposited with a financial institution for an agreed period at an agreed interest rate.", "A term deposit locks funds away for a set term in exchange for a fixed, agreed rate of interest."),
  ma(84, "the share price can fall, and the dividend paid is not guaranteed.", "Unlike a deposit's guaranteed interest, share returns (price growth and dividends) are variable and not guaranteed."),
  ma(85, "government spending and taxation to influence the level of economic activity.", "Fiscal policy is the government's use of its Budget — spending and taxation — to manage the economy."),
  ma(86, "increasing government spending and/or cutting taxes, moving the Budget towards deficit.", "An expansionary Budget injects more spending power into the economy to stimulate activity, typically widening the deficit."),
  ma(87, "the average rate of tax falls as a person's income rises.", "A regressive tax takes a smaller proportion of income as income rises, the opposite of a progressive tax."),
  ma(88, "The government funding public hospitals and schools rather than leaving their provision entirely to the market.", "Reallocation shifts resources towards goods with wider social benefits (merit/public goods) that the market alone would under-provide."),
  ma(89, "smooth out fluctuations in the business cycle, such as high inflation or high unemployment.", "Stabilisation policy aims to moderate the swings of the business cycle, not eliminate it or maximise revenue."),
  ma(90, "government revenue exceeds government expenditure.", "A surplus occurs when the government collects more revenue than it spends over the period."),
  ma(91, "A tax imposed on producers to reflect the external cost they generate.", "A Pigouvian tax makes producers bear the external cost, correcting the overproduction caused by a negative externality."),
  ma(92, "people with a greater capacity to pay (e.g. higher income) should pay proportionally more tax.", "Vertical equity requires those with a greater ability to pay to contribute a larger share, consistent with a progressive tax system."),
  ma(93, "its payments to the rest of the world (for goods, services, income and transfers) exceed its receipts from the rest of the world.", "A current account deficit means outflows to the rest of the world exceed inflows over the period."),
  ma(94, "make Australian exports cheaper for foreign buyers and imports more expensive for Australians.", "A depreciation lowers the AUD's value, making Australian goods cheaper abroad and foreign goods dearer at home."),
  ma(95, "An increase in foreign demand for Australian exports.", "Foreign buyers must purchase AUD to pay for Australian exports, so stronger export demand raises demand for the AUD."),
  ma(96, "restrict international trade to protect domestic industries, such as tariffs and import quotas.", "Protectionism uses trade barriers to shield local producers from foreign competition."),
  ma(97, "a tax imposed on imported goods, raising their price to domestic consumers.", "A tariff is an import tax that raises the price of the imported good relative to domestically produced substitutes."),
  ma(98, "directly limits the physical quantity of a good that can be imported, rather than taxing it.", "A quota is a quantity restriction; a tariff instead works through price by taxing imports."),
  ma(99, "Export prices rising relative to import prices.", "The terms of trade improve when export prices rise relative to import prices, so a given quantity of exports buys more imports."),
  ma(100, "the increasing economic integration and interdependence of the world's economies through trade, investment and finance.", "Globalisation describes deepening links between national economies via trade, capital flows and finance."),
];

const saAnswers2: Array<[string, Answer]> = [
  sa(51,
    "A need is something essential for survival, such as food, water, shelter and basic clothing. A want is a desire for a good or service that is not essential for survival but that people would like to have, such as a new phone or a holiday. Economics is mainly concerned with wants, because they are unlimited, while needs are relatively few.",
    [
      "Defines a need as essential for survival, with an example",
      "Defines a want as a non-essential desire, with an example",
    ]),
  sa(52,
    "Economic growth is an increase in the total quantity of goods and services an economy is capable of producing. On a PPF diagram it is shown as an outward shift of the entire frontier, meaning more of both goods (or any combination of them) can now be produced than before, typically due to an increase in the quantity or quality of resources or an improvement in technology.",
    [
      "Defines economic growth as an increase in an economy's productive capacity",
      "States it is shown as an outward shift of the whole PPF",
      "Identifies a valid cause (more/better resources, improved technology)",
    ]),
  sa(53,
    "A positive statement is a factual claim that can be tested against evidence and shown to be true or false, such as 'unemployment rose to 4.5% last month'. A normative statement expresses an opinion or value judgement about what ought to happen, such as 'the government should do more to reduce unemployment', and cannot be proven true or false.",
    [
      "Defines a positive statement as testable/factual, with an example",
      "Defines a normative statement as an opinion/value judgement, with an example",
    ]),
  sa(54,
    "The circular flow model shows households and businesses as interdependent: households supply firms with the factors of production (land, labour, capital, enterprise) and, in return, firms pay households factor incomes (rent, wages, interest, profit). Households then use this income to buy the goods and services that firms produce, which generates the revenue firms need to keep producing and paying for factors. Each sector therefore depends on the other to keep the flow of income and spending going.",
    [
      "Describes households supplying factors of production to firms in exchange for factor incomes",
      "Describes households spending that income on firms' goods and services",
      "Explains that this mutual dependence keeps the flow of income and spending circulating",
    ]),
  sa(55,
    "Savings is a leakage because income saved by households is withdrawn from the spending stream rather than spent on domestic goods and services, reducing the level of economic activity unless it flows back in as investment. Taxation is a leakage because income paid to government in tax is also withdrawn from private spending, reducing activity unless it is returned through government spending. Both leakages, if not matched by injections, tend to reduce the level of economic activity.",
    [
      "Identifies a valid leakage (savings, taxation or imports) and explains it withdraws income from the flow",
      "Identifies a second valid leakage and explains it withdraws income from the flow",
    ]),
  sa(56,
    "The business cycle has four phases. The expansion (upturn) phase is when economic activity, output and employment are rising, up to the peak — the highest point of the cycle, where growth is at its strongest before turning down. The contraction (downturn) is when economic activity, output and employment are falling, down to the trough — the lowest point of the cycle, where activity stops falling before a new expansion begins.",
    [
      "Describes the expansion (upturn) and the peak (rising activity, up to its highest point)",
      "Describes the contraction (downturn) and the trough (falling activity, down to its lowest point)",
      "Correctly sequences all four phases (expansion, peak, contraction, trough)",
    ]),
  sa(57,
    "Bounded rationality is the idea that people want to make the best decision but are limited by incomplete information, limited time and limited mental processing ability, so they often make 'good enough' decisions rather than perfectly optimal ones. For example, a shopper may choose the first acceptable product they find rather than comparing every option available.",
    [
      "Defines bounded rationality as decision-making limited by information, time or cognitive capacity",
      "Gives a valid example of a 'good enough' rather than perfectly optimal decision",
    ]),
  sa(58,
    "Because resources are scarce relative to unlimited wants, every economic system — whether market, planned or mixed — must decide how to allocate those limited resources. This means it must determine what goods and services to produce with the available resources, how to produce them (which techniques and resources to use), and for whom they are produced (how the output is distributed among members of society). These three questions arise directly from the problem of scarcity and apply regardless of the system used to answer them.",
    [
      "Links the three questions to the underlying problem of scarcity",
      "States the three questions must be answered under any system, market or otherwise",
      "Names the three questions (what, how, for whom)",
    ]),
  sa(59,
    "An increase in supply, with demand unchanged, shifts the supply curve to the right, so more is offered for sale at every price. This moves the equilibrium to a point of lower price and higher quantity, since sellers must lower the price to sell the extra output and buyers respond by demanding more at the lower price.",
    [
      "States the supply curve shifts right",
      "States the equilibrium price falls",
      "States the equilibrium quantity rises",
    ]),
  sa(60,
    "In the short run, firms cannot easily change their production capacity, inputs or number of workers, so the quantity supplied responds little to a price change — supply is more inelastic. In the long run, firms can build new capacity, hire and train more workers, and new firms can enter the industry, giving much more scope to increase output in response to a higher price — so supply is more elastic.",
    [
      "Explains that in the short run capacity/inputs are fixed, so supply is inelastic",
      "Explains that in the long run firms can expand capacity and new firms can enter, making supply more elastic",
    ]),
  sa(61,
    "An oligopoly consists of a small number of large firms that dominate the market and are interdependent in their pricing and output decisions; their products may be similar or differentiated. A monopolistically competitive market has many firms, each selling a differentiated product with some pricing power, but no single firm is large enough to significantly affect its rivals' decisions.",
    [
      "Describes oligopoly: few large, interdependent firms",
      "Describes monopolistic competition: many firms, product differentiation, no single firm affects rivals",
      "Contrasts the number of firms and/or degree of interdependence between the two structures",
    ]),
  sa(62,
    "A positive externality of consumption means that people other than the consumer also benefit from the good, but the consumer only considers their own private benefit when deciding how much to buy. Because the market price does not reflect this extra social benefit, consumers buy less than the amount that would maximise society's overall welfare, so the good is under-consumed relative to the socially optimal quantity.",
    [
      "Explains that third parties also benefit but the consumer only weighs their own private benefit",
      "Explains that the market price/quantity ignores this extra social benefit",
      "Concludes the good is under-consumed relative to the socially efficient level",
    ]),
  sa(63,
    "Market failure occurs when the free market, left to itself, fails to allocate resources efficiently — that is, it produces too much or too little of a good relative to the socially optimal level. An example is a factory that pollutes the environment (a negative production externality) without bearing the cost of the pollution, leading to overproduction of the good relative to what is best for society.",
    [
      "Defines market failure as an inefficient allocation of resources by the free market",
      "Gives a valid example (e.g. externality, public good, information failure)",
    ]),
  sa(64,
    "A merit good, such as education or vaccination, is under-consumed in a free market because individuals do not take into account the wider social benefits their consumption creates for others. A government subsidy lowers the effective price paid by consumers, shifting demand or supply so that a greater quantity is consumed, moving the market closer to the socially optimal level of consumption.",
    [
      "Explains that a merit good is under-consumed because individuals ignore the wider social benefit",
      "Explains that a subsidy lowers the effective price, increasing the quantity consumed",
      "Concludes this moves the market towards the socially optimal outcome",
    ]),
  sa(65,
    "Government failure can occur when a government subsidy intended to support an industry is poorly targeted and instead props up an inefficient firm that would otherwise have exited the market, wasting taxpayer funds and producing a less efficient outcome than the market would have delivered on its own.",
    [
      "Gives a valid example of government intervention (e.g. a poorly targeted subsidy)",
      "Explains why it produces a worse outcome than the free market would have (government failure)",
    ]),
  sa(66,
    "Allocative efficiency in a competitive market occurs where price equals marginal cost (P = MC). At this point, the price consumers are willing to pay for the last unit (reflecting its value to them) exactly equals the cost of the resources used to produce it, so resources are being used to produce exactly the combination of goods that society values most, with no waste from producing too much or too little of any good.",
    [
      "States the condition for allocative efficiency: price equals marginal cost",
      "Explains that this means the value consumers place on the last unit equals its cost of production",
      "Explains why this represents an efficient use of society's scarce resources",
    ]),
  sa(67,
    "Total utility is the overall satisfaction a consumer gets from consuming a given quantity of a good. Marginal utility is the extra satisfaction gained from consuming one additional unit of that good. Total utility generally keeps rising as more units are consumed, even while marginal utility is falling (diminishing marginal utility).",
    [
      "Defines total utility as overall satisfaction from a given quantity consumed",
      "Defines marginal utility as the extra satisfaction from one more unit",
    ]),
  sa(68,
    "If households become more optimistic about their future income — for example, expecting a pay rise or believing their jobs are secure — they are more willing to spend now rather than save, since they feel less need to build up precautionary savings. Conversely, if households expect their future income to fall or become uncertain (for example, fearing job losses), they tend to increase saving now and reduce current consumption as a precaution.",
    [
      "Explains that positive expectations about future income increase current consumption (reduce saving)",
      "Explains that negative/uncertain expectations about future income increase current saving (reduce consumption)",
      "Links both cases clearly to a change in household behaviour now, based on expectations of the future",
    ]),
  sa(69,
    "A normal good is one for which demand rises as consumer income rises, but generally by a similar or smaller proportion than the rise in income. A luxury good is a normal good for which demand rises by a larger proportion than income — spending on it takes up a growing share of the household budget as income increases.",
    [
      "Defines a normal good: demand rises as income rises",
      "Defines a luxury good: demand rises by proportionally more than income",
    ]),
  sa(70,
    "As a firm keeps expanding beyond a certain scale, it can become difficult to manage, coordinate and communicate across a very large organisation, leading to inefficiencies such as slower decision-making and duplicated effort. These management and coordination problems can raise the average cost of production as output continues to increase, causing the long-run average cost curve to turn upward — diseconomies of scale.",
    [
      "Identifies a valid cause of diseconomies of scale (e.g. management/coordination difficulties in a very large firm)",
      "Explains why this cause raises costs (e.g. slower decisions, duplicated effort, loss of control)",
      "Concludes this raises average cost as output increases further, turning the LRAC curve upward",
    ]),
  sa(71,
    "Debt finance involves borrowing funds (such as a bank loan or bond) that must be repaid with interest over an agreed period, regardless of the business's profitability. Equity finance involves raising funds by selling part-ownership of the business (shares), which does not need to be repaid, but gives shareholders a claim on future profits and often a say in how the business is run.",
    [
      "Defines debt finance: borrowed funds that must be repaid with interest",
      "Defines equity finance: funds raised by selling ownership, no obligation to repay",
    ]),
  sa(72,
    "Higher labour productivity means each worker produces more output in the same amount of time, which lowers the labour cost per unit of output. This allows a business to produce more cheaply than competitors, sell at a lower price or earn higher profit margins, and better compete in domestic and international markets.",
    [
      "States higher productivity means more output per worker in the same time",
      "Explains that this lowers the labour cost per unit of output",
      "Links lower unit costs to improved competitiveness (lower prices, higher margins, or export competitiveness)",
    ]),
  sa(73,
    "Labour is not demanded for its own sake, but because it is needed to produce the goods and services that consumers want. The demand for labour therefore depends on ('is derived from') the demand for the output that labour helps to produce — if demand for that output changes, the demand for the labour used to make it changes too.",
    [
      "States that labour demand comes from the demand for the output it helps to produce",
      "Explains that a change in output demand causes labour demand to change in the same direction",
    ]),
  sa(74,
    "One factor is the level of education, training or qualifications required for the occupation — the more difficult and time-consuming it is to qualify, the fewer people are able to supply their labour to it. A second factor is non-wage working conditions, such as hours, safety and job satisfaction — more attractive conditions increase the number of people willing to supply their labour to that occupation.",
    [
      "Factor 1: education/training/qualification requirements, and how this affects labour supply",
      "Factor 2: non-wage working conditions, and how this affects labour supply",
      "Both factors are correctly linked to an increase or decrease in the quantity of labour supplied",
    ]),
  sa(75,
    "Automation can reduce the demand for labour in tasks that machines can perform more cheaply, particularly repetitive or routine tasks, shifting the labour demand curve for those workers to the left. At the same time, the workers who remain employed often work alongside more advanced machinery and technology, which can raise their output per hour — increasing labour productivity for the remaining workforce.",
    [
      "Explains that automation decreases demand for labour whose tasks are replaced (shifts demand left)",
      "Explains that remaining workers may become more productive when working with new technology",
      "Distinguishes the effect on demand for the displaced workers from the effect on the productivity of those who remain",
    ]),
  sa(76,
    "The primary function of financial markets is to allow new securities, such as newly issued shares, to be sold to raise fresh funds for a company. The secondary function is to allow existing securities, such as previously issued shares, to be bought and sold between investors, without providing any new funds directly to the company.",
    [
      "Defines the primary market function: raising new funds through newly issued securities",
      "Defines the secondary market function: trading existing securities between investors, no new funds raised",
    ]),
  sa(77,
    "A bank term deposit offers a low, but guaranteed and predictable, rate of interest with very low risk of loss, since it is generally covered by a government guarantee up to a limit. Company shares offer the potential for much higher returns through capital growth and dividends, but their value can rise or fall and dividends are not guaranteed, so they carry considerably more risk. An investor must weigh the certainty of a lower return against the possibility of a higher, but uncertain, return.",
    [
      "Describes the term deposit: low risk, low but guaranteed/predictable return",
      "Describes shares: higher potential return but variable value and no guaranteed dividend (higher risk)",
      "Explains the trade-off the investor faces between certainty and potential higher reward",
    ]),
  sa(78,
    "Financial intermediaries accept deposits from savers and pool these funds together. They then lend these pooled funds to borrowers such as households and businesses, earning a margin between the interest paid to savers and the interest charged to borrowers, while also assessing and managing the risk of lending on behalf of individual savers.",
    [
      "Function 1: accepting and pooling deposits from savers",
      "Function 2: lending the pooled funds to borrowers (and/or assessing and managing lending risk)",
    ]),
  sa(79,
    "A rise in the interest rate increases the cost of borrowing funds to finance an investment project, such as buying new equipment or expanding a factory. Because the return on many investment projects may no longer exceed this higher cost of borrowing, businesses tend to postpone or cancel these projects, so the level of business investment falls.",
    [
      "States a rise in interest rates raises the cost of borrowing for investment",
      "Explains that some projects' expected return no longer exceeds this higher cost",
      "Concludes businesses postpone or cancel projects, so business investment falls",
    ]),
  sa(80,
    "A bond is a form of debt: the investor lends money to the company for a fixed period and receives regular fixed interest payments, with the principal repaid at maturity, regardless of the company's profit. A share is a form of equity: the investor buys part-ownership of the company and receives a variable return in the form of dividends and any capital growth, which depends on the company's performance.",
    [
      "Defines a bond as debt: fixed interest, repaid at maturity, not linked to profit",
      "Defines a share as equity: part-ownership, variable return linked to company performance",
    ]),
  sa(81,
    "The ASX operates the main market in Australia for buying and selling shares and other securities such as exchange traded funds and bonds. It allows companies to raise capital by listing and issuing new shares (the primary market) and allows investors to trade existing shares with each other (the secondary market), while providing price transparency and regulating listed companies' disclosure obligations.",
    [
      "States the ASX provides a market for trading shares and other securities",
      "Explains its role in companies raising capital (primary market) and/or investors trading existing shares (secondary market)",
      "Notes its role in price transparency / regulating disclosure by listed companies",
    ]),
  sa(82,
    "Compulsory superannuation contributions accumulate into large superannuation funds over workers' lifetimes, creating a substantial pool of long-term savings. These funds are invested by superannuation funds into shares, property, bonds and other assets, channelling household savings into productive investment across the Australian economy.",
    [
      "Explains that compulsory super accumulates a large pool of long-term household savings",
      "Explains that super funds invest these savings into productive assets across the economy",
    ]),
  sa(83,
    "The interest rate is determined in the loanable funds market by the interaction of the demand for funds (from borrowers wanting to invest or spend) and the supply of funds (from savers). The equilibrium interest rate is where the quantity of funds demanded equals the quantity supplied. An increase in the demand for funds, with supply unchanged, shifts the demand curve to the right, raising the equilibrium interest rate and increasing the quantity of funds borrowed and lent.",
    [
      "States the equilibrium interest rate is where the demand for funds equals the supply of funds",
      "States an increase in the demand for funds shifts the demand curve right",
      "States this raises the equilibrium interest rate and increases the quantity of funds borrowed and lent",
    ]),
  sa(84,
    "Fiscal policy is the use of government spending and taxation, set out in the Budget, to influence the level of economic activity. Monetary policy is the use of interest rates (and the money supply) by the central bank (the Reserve Bank of Australia) to influence the economy. Fiscal policy is controlled by the government; monetary policy is controlled by the central bank.",
    [
      "Defines fiscal policy: government spending/taxation via the Budget, controlled by government",
      "Defines monetary policy: interest rates set by the central bank (RBA)",
    ]),
  sa(85,
    "An expansionary Budget increases government spending and/or cuts taxes to inject more spending power into the economy, typically moving the Budget towards deficit; a government might use this during a downturn or recession to boost economic activity and reduce unemployment. A contractionary Budget cuts spending and/or raises taxes to withdraw spending power from the economy, typically moving the Budget towards surplus; a government might use this when the economy is overheating and inflation is a concern.",
    [
      "Describes an expansionary Budget and a circumstance for using it (e.g. downturn/recession)",
      "Describes a contractionary Budget and a circumstance for using it (e.g. overheating economy/high inflation)",
      "Correctly links each type of Budget to its effect on the Budget balance (deficit/surplus)",
    ]),
  sa(86,
    "A progressive tax takes a larger proportion of income as income rises — for example, Australia's personal income tax, which applies higher marginal tax rates to higher income brackets. A regressive tax takes a smaller proportion of income as income rises — for example, the GST, which takes a larger share of the income of a lower-income earner than of a higher-income earner, since both pay the same rate on their spending.",
    [
      "Defines a progressive tax with a valid example (e.g. income tax)",
      "Defines a regressive tax with a valid example (e.g. GST)",
    ]),
  sa(87,
    "The government collects taxation, with progressive income tax taking a larger share from higher-income earners. It then uses some of this revenue to make transfer payments, such as pensions and unemployment benefits, to lower-income households who did not provide a good or service in return. Together, these two flows — collecting proportionally more from higher earners and giving payments to those in greater need — narrow the gap between high and low disposable incomes.",
    [
      "Explains that progressive taxation collects proportionally more from higher-income earners",
      "Explains that transfer payments provide income to lower-income households",
      "Concludes the combination redistributes income and narrows income inequality",
    ]),
  sa(88,
    "Horizontal equity means that people in similar financial circumstances (e.g. earning the same income) should pay the same amount of tax. Vertical equity means that people in different financial circumstances should be treated differently, with those who have a greater capacity to pay (e.g. higher income) paying proportionally more tax.",
    [
      "Defines horizontal equity: similar taxpayers pay the same tax",
      "Defines vertical equity: taxpayers with greater capacity to pay contribute proportionally more",
    ]),
  sa(89,
    "A Budget surplus occurs when government revenue exceeds government expenditure over a period. A Budget deficit occurs when government expenditure exceeds government revenue over a period. A balanced Budget occurs when government revenue and expenditure are exactly equal over the period.",
    [
      "Defines a Budget surplus: revenue exceeds expenditure",
      "Defines a Budget deficit: expenditure exceeds revenue",
      "Defines a balanced Budget: revenue equals expenditure",
    ]),
  sa(90,
    "The government's reallocation role involves shifting resources away from the pattern the free market alone would produce, towards a pattern that better reflects society's needs — for example, funding public education so that resources are allocated towards schooling even though some households might otherwise spend less on it, because education generates wider benefits for society as a whole.",
    [
      "Gives a valid example of government reallocation (e.g. education, healthcare, public infrastructure)",
      "Explains why the government reallocates resources towards this good (wider social benefit / under-provision by the market)",
    ]),
  sa(91,
    "A government can impose a tax on producers of a good that generates a negative externality (such as pollution), raising their cost of production so that it reflects the true social cost of making the good, not just the private cost. This shifts the supply curve to the left, raising the price and reducing the quantity produced towards the socially optimal level. The size of the tax needed should equal the value of the external cost imposed on third parties at the socially optimal quantity, so that producers fully account for it.",
    [
      "Explains that the tax raises producers' costs to reflect the external cost, shifting supply left",
      "Explains that this reduces the quantity towards the socially optimal level",
      "States the tax should be set equal to the size of the external cost, to fully account for it",
    ]),
  sa(92,
    "The current account records trade in goods and services, primary income (such as interest and dividends) and secondary income (such as transfers) between Australia and the rest of the world. The capital and financial account records financial flows, such as foreign investment into and out of Australia, including debt and equity transactions.",
    [
      "Describes the current account: trade in goods/services and income/transfer flows",
      "Describes the capital and financial account: financial flows/investment (debt and equity)",
    ]),
  sa(93,
    "An appreciation of the Australian dollar means it can now buy more of a foreign currency than before. This makes Australian exports more expensive in foreign-currency terms for overseas buyers, since they need more of their own currency to buy the same amount of AUD, reducing demand for Australian exports. At the same time, imports become cheaper for Australians, since each Australian dollar now buys more foreign currency, so imported goods cost less in AUD terms.",
    [
      "States exports become more expensive for foreign buyers",
      "States imports become cheaper for Australian buyers",
      "Links both effects correctly to the AUD buying more foreign currency after the appreciation",
    ]),
  sa(94,
    "A tariff is a tax placed on imported goods, which raises their price to domestic consumers but allows any quantity to still be imported (fewer are simply bought at the higher price). An import quota instead directly limits the physical quantity of a good that can be legally imported, regardless of price, which can also raise the domestic price by restricting available supply.",
    [
      "Defines a tariff: a tax on imports, working through price",
      "Defines a quota: a direct quantity restriction on imports",
    ]),
  sa(95,
    "Comparative advantage means a country can produce a good at a lower opportunity cost (giving up less of other goods) than another country, even if it is not necessarily the most efficient producer in absolute terms. If each country specialises in producing the good(s) in which it has a comparative advantage and trades with others, total world output can rise and all trading countries can consume more than they could by producing everything themselves — this is the basic economic justification for international trade.",
    [
      "Defines comparative advantage as producing at a lower opportunity cost than a trading partner",
      "Notes this need not mean being the most efficient (absolute) producer",
      "Explains that specialising according to comparative advantage and trading increases total output/consumption for all trading partners",
    ]),
  sa(96,
    "The terms of trade measure the ratio of a country's export prices to its import prices, usually expressed as an index. An improvement in the terms of trade means export prices have risen relative to import prices, so a given quantity of exports can now be exchanged for a greater quantity of imports — the country's real purchasing power on world markets has increased.",
    [
      "Defines the terms of trade as the ratio of export prices to import prices",
      "Explains that an improvement means a given quantity of exports buys more imports (greater purchasing power)",
    ]),
  sa(97,
    "One argument is to protect a young ('infant') domestic industry from established, larger foreign competitors until it can grow and achieve efficiencies of scale to compete on its own. A second argument is to protect strategic industries considered important for national security or self-sufficiency (such as food or energy production), so the country is not entirely reliant on foreign supply during a crisis.",
    [
      "Argument 1: protecting an infant industry until it can become internationally competitive",
      "Argument 2: protecting a strategically important industry for national security/self-sufficiency",
      "Both arguments are correctly explained, not just named",
    ]),
  sa(98,
    "Foreign debt is money Australia has borrowed from overseas lenders, which must eventually be repaid along with interest, regardless of how well the borrowed funds are used. Foreign equity is foreign ownership of Australian assets, such as shares in Australian companies or property; it does not need to be repaid, but profits and dividends earned on that ownership flow back overseas to the foreign owners.",
    [
      "Defines foreign debt: overseas borrowing that must be repaid with interest",
      "Defines foreign equity: overseas ownership of Australian assets, no repayment required but profits flow overseas",
    ]),
  sa(99,
    "Globalisation has increased Australia's trade and financial links with the rest of the world, exposing Australian businesses to greater international competition but also giving them access to larger export markets and cheaper imported inputs. For example, Australian consumers now have access to a much wider range of imported goods at lower prices than if the economy were closed to trade, while Australian resource exporters have benefited from strong demand from rapidly growing economies such as China.",
    [
      "Explains that globalisation has increased trade and financial integration with the rest of the world",
      "States a valid effect on the Australian economy (consumers, exporters, competition, investment, etc.)",
      "Supports this with a correctly reasoned example",
    ]),
  sa(100,
    "The exchange rate determines how much of a foreign currency an Australian dollar can buy, which directly affects the price of Australian exports in foreign markets and the price of imports in Australia. A weaker (depreciated) exchange rate makes Australian goods and services cheaper and more competitive for foreign buyers, while a stronger (appreciated) exchange rate makes them more expensive and less competitive internationally.",
    [
      "Explains that the exchange rate affects the foreign-currency price of exports and the AUD price of imports",
      "Explains that a weaker exchange rate improves international competitiveness (and a stronger one worsens it)",
    ]),
];

export const answers: AnswerSet = Object.fromEntries([
  ...mcAnswers,
  ...mcAnswers2,
  ...saAnswers,
  ...saAnswers2,
]);
