import type { Answer, AnswerSet } from "@/lib/types";

// Answer key for y11-economics-preliminary. NO "server-only" import here (the
// validator reads it); only re-exported via content/answers/index.ts, which is
// server-only. Never import from a client component.

const U = "y11-economics-preliminary";
const p2 = (n: number) => String(n).padStart(2, "0");

function ma(n: number, correctText: string, why: string): [string, Answer] {
  return [`${U}.m${p2(n)}`, { correctText, rubric: [why] }];
}

function sa(n: number, model: string, rubric: string[]): [string, Answer] {
  return [`${U}.s${p2(n)}`, { modelAnswer: model, rubric }];
}

const mcAnswers: Array<[string, Answer]> = [
  ma(1, "unlimited wants must be satisfied using scarce (limited) resources.", "Scarcity — limited resources against unlimited wants — is the fundamental economic problem that forces choice."),
  ma(2, "the value of the next best alternative that is given up.", "Opportunity cost is the value of the next best alternative forgone when a choice is made."),
  ma(3, "Land, labour, capital and enterprise.", "The four factors of production are natural resources (land), labour, capital and entrepreneurship."),
  ma(4, "interest.", "Capital earns interest; land earns rent, labour earns wages, and enterprise earns profit."),
  ma(5, "the price mechanism — the interaction of buyers and sellers.", "In a market economy, decentralised prices set by demand and supply answer the key economic questions."),
  ma(6, "resources are unemployed or not being used efficiently.", "A point inside the PPF is attainable but wasteful — some resources are idle or misallocated."),
  ma(7, "Savings, taxation and imports.", "Leakages (S, T, M) withdraw income from the domestic circular flow; injections are I, G and X."),
  ma(8, "S + T + M = I + G + X (total leakages equal total injections).", "Equilibrium in the circular flow occurs when total leakages equal total injections, so the level of activity is stable."),
  ma(9, "rising unemployment and slowing or falling economic activity.", "A contraction means output growth slows or falls, so firms hire fewer workers and unemployment rises."),
  ma(10, "incentive function.", "A higher price raises potential profit, giving producers an incentive to expand output."),
  ma(11, "a rightward shift of the demand curve.", "Income is a non-price factor, so a change in it shifts the whole demand curve (right, for a normal good)."),
  ma(12, "a higher price and a higher quantity.", "An increase in demand against unchanged supply raises both the equilibrium price and quantity."),
  ma(13, "0.5 — demand is relatively inelastic.", "PED = %ΔQd ÷ %ΔP = 5 ÷ 10 = 0.5; a value below 1 is relatively inelastic."),
  ma(14, "is a necessity with few close substitutes.", "Necessities with no substitutes must be bought almost regardless of price, so demand barely responds."),
  ma(15, "monopoly.", "One seller, no close substitutes and very high barriers to entry defines a monopoly."),
  ma(16, "many small firms selling identical products, with no barriers to entry and no pricing power.", "Perfect competition: many price-taking firms, homogeneous product, free entry and exit."),
  ma(17, "a negative externality from production.", "The pollution is a cost imposed on third parties that is not reflected in the market price."),
  ma(18, "non-excludable and non-rival in consumption.", "A public good cannot exclude non-payers and one person's use does not reduce another's — leading to the free-rider problem."),
  ma(19, "a persistent shortage of rental housing.", "A binding ceiling holds rent below equilibrium, so quantity demanded exceeds quantity supplied."),
  ma(20, "as a person consumes more units of a good, the extra satisfaction from each additional unit falls.", "Diminishing marginal utility: each successive unit adds less to total satisfaction."),
  ma(21, "0.8.", "MPC = change in consumption ÷ change in income = 80 ÷ 100 = 0.8."),
  ma(22, "1.", "Every extra dollar of income is either consumed or saved, so MPC + MPS = 1."),
  ma(23, "falls as consumer incomes rise.", "For an inferior good, higher income leads consumers to switch to preferred alternatives, reducing demand."),
  ma(24, "consumers, through their spending decisions, ultimately determine what is produced.", "Consumer sovereignty: producers respond to consumers' purchasing choices."),
  ma(25, "the opportunity cost of the resources the owner supplies (such as their own labour and capital).", "Economic profit subtracts implicit (opportunity) costs as well as explicit costs; accounting profit subtracts only explicit costs."),
  ma(26, "long-run average cost falls as the scale of production increases.", "Economies of scale mean per-unit cost falls as output rises, up to the technical optimum."),
  ma(27, "the demand for the goods and services that the labour is used to produce.", "Labour is wanted to produce output, so its demand is derived from the demand for that output."),
  ma(28, "More people gaining the qualifications the occupation requires.", "More qualified people willing to do the work increases labour supply to that occupation."),
  ma(29, "channel funds from savers to borrowers, facilitating saving and investment.", "The financial sector's core role is intermediation between surplus and deficit units."),
  ma(30, "primary market.", "New securities issued to raise funds are a primary-market transaction; the secondary market trades existing securities."),
  ma(31, "Australia's central bank, responsible for monetary policy.", "The RBA is the central bank; it conducts monetary policy and issues currency."),
  ma(32, "the price of money — the cost of borrowing and the reward for saving.", "The interest rate is the price of credit and the return to lenders/savers."),
  ma(33, "lower the equilibrium interest rate.", "More funds supplied at each rate shifts supply right, reducing the equilibrium price of funds (the interest rate)."),
  ma(34, "lending money to the government in return for interest payments.", "A bond is a debt security; the buyer lends to the issuer and receives interest (coupons)."),
  ma(35, "less affordable, because mortgage repayments increase.", "Higher rates raise the cost of servicing a mortgage, reducing borrowing capacity and affordability."),
  ma(36, "a large pool of national savings that helps fund investment.", "Compulsory super accumulates long-term savings that are invested across the economy."),
  ma(37, "Redistribution of income.", "The syllabus identifies redistribution, reallocation, stabilisation and correction of market failure as government roles."),
  ma(38, "is levied on, and paid by, the same person or entity (for example, personal income tax).", "For a direct tax the legal and economic incidence fall on the same party; it cannot be passed on."),
  ma(39, "The Goods and Services Tax (GST).", "The GST is levied on sellers but paid by consumers in the price — an indirect tax. The others are direct taxes."),
  ma(40, "who ultimately bears the burden of the tax.", "Economic incidence identifies who actually pays, which can differ from who is legally liable."),
  ma(41, "the average rate of tax rises as a person's income rises.", "Progressive taxation takes a larger proportion of income as income increases (e.g. income tax brackets)."),
  ma(42, "simplicity, fairness (equity) and efficiency.", "A good tax is simple to understand and comply with, fair, and does not badly distort economic decisions."),
  ma(43, "The Age Pension.", "A transfer payment provides income with no good or service given in return. Wages and purchases are not transfers."),
  ma(44, "government expenditure exceeds government revenue.", "A deficit is where spending is greater than revenue over the period."),
  ma(45, "voluntary exchange lets countries specialise according to opportunity cost, and both trading partners can gain.", "Trade based on comparative advantage improves the allocation of resources and raises total output."),
  ma(46, "the value of its exports exceeds the value of its imports.", "Exports greater than imports is a trade surplus; the reverse is a deficit."),
  ma(47, "Australian exports become more expensive for US buyers, and US imports become cheaper for Australians.", "An appreciation raises the AUD's value, making exports dearer abroad and imports cheaper at home."),
  ma(48, "foreign ownership of Australian assets, such as shares in Australian companies and property.", "Foreign equity is ownership; foreign debt is borrowing that must be repaid with interest."),
  ma(49, "a record of all economic transactions between Australia and the rest of the world over a period.", "The balance of payments records trade, income and financial flows between residents and non-residents."),
  ma(50, "in which it has a lower opportunity cost than its trading partners.", "Comparative advantage is about relative opportunity cost, not absolute output or price."),
];

const saAnswers: Array<[string, Answer]> = [
  sa(1,
    "Opportunity cost is the value of the next best alternative that is given up when a choice is made. For example, if a student spends Saturday working a paid shift, the opportunity cost is the leisure or study time they could have had instead.",
    [
      "Defines opportunity cost as the value of the next best alternative forgone",
      "Gives a valid example that identifies the alternative given up",
    ]),
  sa(2,
    "A PPF shows the maximum combinations of two goods an economy can produce with its resources fully and efficiently employed. Moving along the frontier to produce more of one good means giving up some of the other — the slope shows the opportunity cost. Points on the frontier are efficient; points inside are inefficient (resources idle or misallocated); points outside are unattainable with current resources and technology.",
    [
      "Explains the PPF shows maximum output combinations with resources fully/efficiently used",
      "Explains that moving along it involves an opportunity cost (giving up one good for the other)",
      "Distinguishes efficient (on the frontier) from inefficient (inside) points",
    ]),
  sa(3,
    "In a free market economy the key economic questions are answered by the price mechanism — private individuals and firms make decisions guided by prices, profits and self-interest, with little government direction. In a planned (command) economy a central authority owns most resources and directs what is produced, how, and for whom.",
    [
      "States a free market economy relies on the price mechanism / private decision-making",
      "States a planned economy relies on central government ownership and direction of resources",
    ]),
  sa(4,
    "The circular flow of income model shows income and spending flowing between five sectors: households, businesses, the financial sector, the government sector and the international sector. Injections add to the flow: investment (I), government spending (G) and exports (X). Leakages withdraw from the flow: savings (S), taxation (T) and imports (M).",
    [
      "Describes income/spending flowing between the sectors (households, firms, and financial/government/overseas)",
      "Identifies the injections: investment, government spending, exports",
      "Identifies the leakages: savings, taxation, imports",
    ]),
  sa(5,
    "When total leakages (S + T + M) exceed total injections (I + G + X), more income is being withdrawn from the circular flow than is being added back. Spending and production fall, so the level of economic activity contracts — output declines and unemployment tends to rise — until a new, lower equilibrium is reached.",
    [
      "States that leakages exceeding injections means net income is withdrawn from the flow",
      "Explains that spending and production therefore fall",
      "Concludes the level of economic activity contracts toward a lower equilibrium",
    ]),
  sa(6,
    "Economies pursue higher GDP because it generally allows higher average incomes and material living standards, and because a growing economy creates more jobs, reducing unemployment. Higher output also gives governments more tax revenue to fund services.",
    [
      "Reason 1: higher GDP raises average incomes / material living standards",
      "Reason 2: growth creates employment / reduces unemployment (or: more tax revenue for services)",
    ]),
  sa(7,
    "A cognitive bias is a systematic error in the way people think and make decisions, which departs from the rational, self-interested behaviour assumed in conventional economic models. For example, loss aversion means people feel the pain of a loss more strongly than the pleasure of an equal gain, so they may hold a falling investment too long.",
    [
      "Defines a cognitive bias as a systematic departure from rational decision-making",
      "Gives a valid example (e.g. anchoring, loss aversion, overconfidence, sunk cost fallacy) and explains it briefly",
    ]),
  sa(8,
    "In a market economy the price mechanism answers the key questions. 'What to produce' is decided by consumer demand — firms produce goods that are profitable to sell. 'How to produce' is decided by producers seeking the lowest-cost combination of resources given input prices. 'For whom to produce' is decided by the distribution of income — goods go to those willing and able to pay the price.",
    [
      "'What': consumer demand / profitability guides which goods are produced",
      "'How': producers choose the least-cost method given relative input prices",
      "'For whom': output is allocated to those able and willing to pay (distribution of income)",
    ]),
  sa(9,
    "Each factor of production earns a corresponding factor income: land earns rent, labour earns wages, capital earns interest, and enterprise (entrepreneurship) earns profit. These payments are the cost of the resource to the firm and the income of the resource owner.",
    [
      "Matches at least three factors to their incomes (land–rent, labour–wages, capital–interest, enterprise–profit)",
      "Notes these payments are both a cost to firms and income to resource owners",
    ]),
  sa(10,
    "A rise in the cost of production means firms are willing to supply less of the good at every price, so the supply curve shifts to the left (a decrease in supply). With demand unchanged, this raises the equilibrium price and reduces the equilibrium quantity traded.",
    [
      "States supply decreases — the supply curve shifts left",
      "States the equilibrium price rises",
      "States the equilibrium quantity falls",
    ]),
  sa(11,
    "The price elasticity of demand is calculated as the percentage change in quantity demanded divided by the percentage change in price. A value of 0.4 means that a 1% change in price causes only a 0.4% change in quantity demanded (in the opposite direction). Because it is less than 1, demand is relatively price-inelastic — quantity demanded is not very responsive to price.",
    [
      "States the formula: % change in quantity demanded ÷ % change in price",
      "Interprets 0.4 as quantity demanded changing proportionally less than price",
      "Concludes demand is relatively inelastic (value < 1)",
    ]),
  sa(12,
    "Demand is more price-inelastic when the good is a necessity that consumers must keep buying even if the price rises, and when it has few or no close substitutes, so consumers cannot switch away when the price rises. (Other valid factors: the good takes up only a small share of income, or there is little time to adjust.)",
    [
      "Factor 1: the good is a necessity (must be bought regardless of price)",
      "Factor 2: few or no close substitutes, so consumers cannot switch away",
    ]),
  sa(13,
    "Under perfect competition there are many small firms selling an identical product, there are no barriers to entry or exit, and each firm is a price taker with no power to set the price. Under monopoly there is a single firm with no close substitutes, protected by very high barriers to entry, and it has significant power to set the price (a price maker).",
    [
      "Number of firms: perfect competition has many; monopoly has one",
      "Barriers to entry: none / very low for perfect competition; very high for monopoly",
      "Pricing power: perfectly competitive firms are price takers; a monopolist is a price maker",
    ]),
  sa(14,
    "A negative externality from production is a cost of producing a good that is borne by third parties, not by the producer or the buyer — for example, pollution from a factory. Because the producer does not pay this social cost, the market price is too low and the quantity produced is too high compared with the level that is best for society. Resources are over-allocated to the good, which is market failure.",
    [
      "Defines a negative production externality as a cost imposed on third parties, not paid by the producer or consumer",
      "Explains that the market price is too low / quantity too high because the social cost is ignored",
      "Concludes resources are misallocated (over-produced) — market failure",
    ]),
  sa(15,
    "A public good is non-excludable (people who do not pay cannot be prevented from using it) and non-rival (one person's use does not reduce the amount available to others) — for example, national defence or street lighting. The free-rider problem is that, because non-payers cannot be excluded, individuals have an incentive not to pay, so a private market would under-provide or not provide the good at all.",
    [
      "Defines a public good as non-excludable and non-rival (or gives a valid example demonstrating both)",
      "Explains the free-rider problem: non-payers cannot be excluded, so private provision fails / is under-provided",
    ]),
  sa(16,
    "A per-unit subsidy paid to producers lowers their effective cost of production, so the supply curve shifts to the right. This lowers the price paid by consumers and raises the quantity traded. In terms of resource allocation, more resources are drawn into producing this good than the free market alone would direct — output is pushed above the unsubsidised equilibrium level.",
    [
      "States the subsidy shifts supply right, lowering the price and raising the quantity traded",
      "States producers receive the market price plus the subsidy",
      "Explains that more resources are allocated to this good than the free market would (over-allocation)",
    ]),
  sa(17,
    "Government intervention can itself create inefficiency (government failure). For example, a price ceiling set to help consumers can cause a persistent shortage and non-price rationing such as queues or a black market; or the cost of administering and enforcing a policy can outweigh the benefit; or policies can be distorted by rent-seeking.",
    [
      "Identifies a valid limitation (unintended consequences, administration/enforcement cost, rent-seeking, distorted incentives)",
      "Briefly explains how that limitation reduces the effectiveness or efficiency of the intervention",
    ]),
  sa(18,
    "If demand for a firm's product is price-inelastic, the firm can raise its price and increase total revenue, because the quantity sold falls proportionally less than the price rises. If demand is price-elastic, raising the price reduces total revenue, so the firm is more likely to hold or lower its price and may try to make demand less elastic through product differentiation and branding.",
    [
      "States that with inelastic demand a price rise increases total revenue",
      "States that with elastic demand a price rise reduces total revenue (hold or cut price)",
      "Links elasticity to the firm's strategy (e.g. differentiation to reduce elasticity, or output/pricing decisions)",
    ]),
  sa(19,
    "The law of diminishing marginal utility states that as a person consumes successive units of a good in a given period, the additional (marginal) satisfaction from each extra unit falls. For example, the first slice of pizza gives a lot of satisfaction, the second less, and by the fifth slice the extra satisfaction is small or even negative.",
    [
      "States that marginal (extra) utility falls as more units are consumed",
      "Gives a valid example showing the extra satisfaction declining with each unit",
    ]),
  sa(20,
    "The marginal propensity to consume (MPC) is the proportion of each extra dollar of income that a household spends on consumption, calculated as the change in consumption divided by the change in income. Here MPC = 150 ÷ 200 = 0.75.",
    [
      "Defines MPC as the fraction of extra income that is consumed (ΔC ÷ ΔY)",
      "Calculates MPC = 150 ÷ 200 = 0.75",
    ]),
  sa(21,
    "A household's income is either spent on consumption or saved: income = consumption + saving. As income rises, consumption rises but usually by less than the full increase, so saving also rises. The marginal propensity to consume (the extra spent) plus the marginal propensity to save (the extra saved) add to 1.",
    [
      "States income is divided between consumption and saving",
      "Explains that as income rises, consumption rises (typically by less than the income rise) and saving rises",
      "Notes MPC + MPS = 1",
    ]),
  sa(22,
    "For a normal good, demand rises when consumer income rises and falls when income falls. For an inferior good, the relationship is reversed: demand falls as income rises, because consumers switch to more preferred (often more expensive) alternatives.",
    [
      "States a normal good: demand rises as income rises",
      "States an inferior good: demand falls as income rises",
    ]),
  sa(23,
    "The supply of labour by households is affected by: the wage and non-wage benefits offered (higher pay and better conditions attract more workers); the size of the working-age population and the workforce participation rate; and the education, training and skills required (harder entry reduces the number able to supply that labour). Occupational and geographic mobility also matter.",
    [
      "Factor 1: wage and non-wage benefits / working conditions",
      "Factor 2: population size and/or workforce participation rate",
      "Factor 3: education, training and skills required (or occupational/geographic mobility)",
    ]),
  sa(24,
    "Accounting profit is total revenue minus the explicit (paid) costs of the business, such as wages, rent and materials. Economic profit is total revenue minus both explicit costs and implicit costs — the opportunity cost of the resources the owner contributes, such as their own time and capital. Economic profit is therefore smaller than accounting profit.",
    [
      "Defines accounting profit as revenue minus explicit (paid) costs",
      "Defines economic profit as revenue minus explicit AND implicit (opportunity) costs",
    ]),
  sa(25,
    "Productivity is output per unit of input (for example, output per hour worked). When productivity rises, the same resources produce more goods and services, so real output and real incomes per person can rise. Over time, growth in productivity is the main source of improvements in material living standards.",
    [
      "Defines productivity as output per unit of input",
      "Explains that higher productivity means more output / higher real income from the same resources",
      "Concludes productivity growth is the main driver of rising living standards over time",
    ]),
  sa(26,
    "Economies of scale occur when, as a firm increases its scale of production, its long-run average cost falls — for example, because it can spread fixed costs over more units or use more specialised equipment. Diseconomies of scale occur when the firm becomes so large that long-run average cost rises — for example, because management becomes harder to coordinate. On a long-run average cost curve, the curve slopes down over the range of economies of scale and slopes up over the range of diseconomies.",
    [
      "Defines economies of scale: LRAC falls as scale increases (with a valid reason)",
      "Defines diseconomies of scale: LRAC rises as scale increases (with a valid reason)",
      "Links both to the shape of the LRAC curve (downward then upward sloping)",
    ]),
  sa(27,
    "The minimum wage is a legally enforced price floor for labour, setting the lowest wage an employer may pay. Its aim is to raise the incomes of low-paid workers above the level the market would set. If it is set above the equilibrium wage, it can also create a surplus of labour (unemployment), because the quantity of labour supplied exceeds the quantity demanded at that wage.",
    [
      "States the minimum wage is a legal price floor for labour intended to raise low-paid workers' incomes",
      "Notes that, if set above equilibrium, it can create a labour surplus (unemployment)",
    ]),
  sa(28,
    "Automation and AI let firms substitute capital for labour, so for routine tasks that machines can now perform, the demand for that type of labour falls (the labour demand curve shifts left), lowering wages and employment in those roles. At the same time, automation can raise the demand for workers who design, maintain or complement the technology, and can raise productivity and output, which supports labour demand elsewhere.",
    [
      "Explains that automation/AI substitutes capital for labour, reducing demand for routine/replaceable labour",
      "Explains the effect on wages and employment in the affected roles (both fall)",
      "Notes an offsetting effect (higher demand for complementary/skilled labour, or higher productivity/output)",
    ]),
  sa(29,
    "An interest rate is the price of borrowing money and the reward for saving or lending it, usually expressed as a percentage per year. It acts as the cost of credit (influencing how much households and firms borrow and spend), and as the return on savings (influencing how much people save); it can also serve as an indicator of the risk of a loan.",
    [
      "Defines the interest rate as the price of money — cost of borrowing / reward for saving",
      "Outlines two roles (e.g. cost of credit affecting borrowing and spending; return on savings; indicator of risk)",
    ]),
  sa(30,
    "In the loanable funds market, the demand for funds comes from borrowers (households, firms and government) and slopes down — more is borrowed at a lower interest rate. The supply of funds comes from savers and lenders and slopes up — more is supplied at a higher interest rate. The equilibrium interest rate is where the quantity of funds demanded equals the quantity supplied; a change in either demand or supply moves the interest rate to a new equilibrium.",
    [
      "Describes demand for funds (borrowers, downward sloping) and supply of funds (savers/lenders, upward sloping)",
      "States the equilibrium interest rate is where quantity demanded equals quantity supplied",
      "Explains that a shift in demand or supply changes the equilibrium interest rate",
    ]),
  sa(31,
    "In the primary share market a company issues new shares to investors to raise funds (for example, in a float or capital raising), so money flows to the company. In the secondary share market investors buy and sell existing shares from one another (for example, on the ASX); the company receives no new funds, but the market provides liquidity and price information.",
    [
      "Primary market: new shares issued by the company to raise funds",
      "Secondary market: trading of existing shares between investors (company gets no new funds; provides liquidity)",
    ]),
  sa(32,
    "Raising funds through debt means borrowing (for example, issuing bonds or taking a loan): the business must repay the principal and pay interest, but lenders do not gain ownership or control. Raising funds through equity means selling ownership (for example, issuing shares): there is no obligation to repay, but new shareholders share in profits (dividends) and in control of the business.",
    [
      "Debt: borrowed funds that must be repaid with interest; lenders gain no ownership",
      "Equity: funds raised by selling ownership; no repayment obligation, but ownership/profits are shared",
    ]),
  sa(33,
    "Financial intermediaries, such as banks, insurers and fund managers, sit between savers and borrowers. They collect small deposits and savings from many people and channel them to borrowers who need larger amounts, transforming the size, maturity and risk of funds. This lowers the cost and risk of matching savers with borrowers, so more saving is turned into productive investment.",
    [
      "States intermediaries channel funds from savers to borrowers",
      "Explains a transformation function (pooling small savings, matching maturities, spreading/reducing risk)",
      "Concludes this increases the flow of saving into investment / lowers transaction costs and risk",
    ]),
  sa(34,
    "The Reserve Bank of Australia is Australia's central bank. In the financial sector it issues the currency, acts as banker to the government and to the commercial banks, and helps oversee the stability of the payments system and the financial system as a whole. It also conducts monetary policy by influencing interest rates.",
    [
      "Identifies the RBA as Australia's central bank",
      "Outlines a role in the financial sector (issuing currency, banker to banks/government, payments-system / financial stability, or monetary policy)",
    ]),
  sa(35,
    "A fall in interest rates lowers the cost of borrowing and reduces the return on saving. Households are more likely to borrow and less likely to save, so consumption spending rises, especially on items bought with credit such as cars and housing. For businesses, lower rates reduce the cost of financing new projects, so more investment projects become profitable and business investment rises.",
    [
      "Explains lower rates reduce borrowing cost and the reward for saving",
      "States household consumption rises (more borrowing / less saving)",
      "States business investment rises (more projects become profitable at the lower cost of finance)",
    ]),
  sa(36,
    "Superannuation is compulsory long-term saving for retirement. Because contributions are made throughout a person's working life and cannot generally be withdrawn until retirement, super builds a very large pool of national savings. Super funds invest these savings in shares, property, bonds and infrastructure, providing a stable source of funds for investment in the Australian economy.",
    [
      "Explains super is compulsory long-term saving that accumulates a large pool of national savings",
      "Explains that super funds invest these savings, providing funds for investment in the economy",
    ]),
  sa(37,
    "Government performs several economic roles in a market economy: redistribution — using taxes and transfer payments to reduce income inequality; reallocation — using taxes, subsidies and direct provision to shift resources towards goods society values (such as health and education) and away from harmful goods; and stabilisation — using its Budget to smooth the business cycle. It also acts to correct market failure.",
    [
      "Role 1: redistribution of income (taxes and transfers)",
      "Role 2: reallocation of resources (taxes, subsidies, direct provision, correcting market failure)",
      "Role 3: stabilisation of economic activity (managing the Budget over the business cycle)",
    ]),
  sa(38,
    "A direct tax is levied on and paid by the same person or entity, so its legal incidence and economic incidence are the same and it cannot be passed on — for example, personal income tax. An indirect tax is levied on producers or sellers but is passed on to consumers through higher prices, so the legal incidence (the seller) and the economic incidence (the buyer) differ — for example, the GST.",
    [
      "Direct tax: paid by the party it is levied on; incidence not shifted (e.g. income tax)",
      "Indirect tax: levied on sellers but passed on to consumers in the price; incidence shifts (e.g. GST)",
    ]),
  sa(39,
    "A progressive tax is one in which the average rate of tax rises as income rises, so higher-income earners pay a larger proportion of their income in tax. Australia's personal income tax is progressive, because it uses rising marginal tax rates across income brackets.",
    [
      "Defines a progressive tax: the average rate of tax rises as income rises",
      "Gives a valid Australian example (personal / PAYG income tax)",
    ]),
  sa(40,
    "A good tax should be simple — easy for taxpayers to understand and comply with, and cheap for the government to collect. It should be fair (equitable) — treating people in similar circumstances alike (horizontal equity) and asking more of those with greater capacity to pay (vertical equity). It should be efficient — raising revenue without badly distorting people's decisions to work, save or invest.",
    [
      "Simplicity: easy to understand, comply with and administer",
      "Equity / fairness: horizontal and vertical equity (capacity to pay)",
      "Efficiency: minimal distortion of economic decisions",
    ]),
  sa(41,
    "Recurrent spending is ongoing, day-to-day spending on the operation of government — wages of public servants, welfare and transfer payments, and running services such as schools and hospitals. Capital (non-recurrent) spending is one-off spending on long-lived assets, such as building roads, hospitals and other infrastructure, which provide benefits over many years.",
    [
      "Recurrent: ongoing day-to-day spending (wages, transfers, running services)",
      "Capital / non-recurrent: one-off spending on long-lived assets / infrastructure",
    ]),
  sa(42,
    "A transfer payment is a payment from the government to a household or individual for which no good or service is provided in return; it transfers income rather than paying for production. Examples include the Age Pension, JobSeeker and family payments.",
    [
      "Defines a transfer payment as a government payment with no good or service received in return (income transfer)",
      "Gives a valid example (Age Pension, JobSeeker, family payments, etc.)",
    ]),
  sa(43,
    "The government can redistribute income by taxing higher-income earners at higher average rates (a progressive income tax), which reduces the gap between high and low after-tax incomes, and by using the revenue to fund transfer payments (such as pensions and unemployment benefits) and services (such as public health and education) that benefit lower-income households proportionally more. Together the tax and transfer system makes the distribution of income more equal.",
    [
      "Explains the progressive tax side: higher earners pay a larger share, reducing high after-tax incomes",
      "Explains the transfer/spending side: payments and services raise the real incomes of lower-income households",
      "Concludes the tax-transfer system makes the income distribution more equal",
    ]),
  sa(44,
    "Markets sometimes fail to allocate resources efficiently — for example, they over-produce goods with negative externalities, under-produce goods with positive externalities, do not provide public goods, and allow abuse of market power. Because these outcomes reduce society's overall wellbeing, there is a rationale for the government to intervene — using taxes, subsidies, regulation, direct provision or price controls — to move production and consumption closer to the socially efficient level.",
    [
      "Identifies that markets fail to allocate resources efficiently in certain cases (externalities, public goods, market power, etc.)",
      "Explains that these failures reduce society's wellbeing",
      "Concludes government intervention is justified to move outcomes toward the socially efficient level",
    ]),
  sa(45,
    "International trade lets each country specialise in producing the goods and services in which it has a comparative advantage (a lower opportunity cost). This raises world output and allows consumers access to a greater variety of goods, often at lower prices. Trade also lets firms sell to larger markets and gain economies of scale, and exposes them to competition that encourages efficiency and innovation.",
    [
      "Explains specialisation according to comparative advantage raises total output",
      "Explains gains to consumers (variety, lower prices) and/or firms (larger markets, economies of scale)",
      "Notes trade encourages competition, efficiency and innovation",
    ]),
  sa(46,
    "A country has a trade surplus when the value of its exports of goods and services is greater than the value of its imports over a period. It has a trade deficit when the value of its imports is greater than the value of its exports.",
    [
      "Trade surplus: exports greater than imports",
      "Trade deficit: imports greater than exports",
    ]),
  sa(47,
    "An appreciation of the Australian dollar means it buys more foreign currency. For Australian exporters, their goods become more expensive in foreign currency terms, so overseas demand for Australian exports tends to fall, reducing export revenue. For Australian importers and consumers, foreign goods become cheaper in Australian dollars, so imports rise.",
    [
      "States an appreciation raises the value of the AUD against other currencies",
      "Explains exporters are worse off: exports become dearer abroad, so export demand/revenue falls",
      "Explains importers/consumers benefit: imports become cheaper, so imports rise",
    ]),
  sa(48,
    "Foreign debt is money that Australian borrowers (governments, businesses and banks) have borrowed from overseas lenders; it must be repaid, with interest. Foreign equity is overseas ownership of Australian assets — such as shares in Australian companies, or Australian property and businesses; it does not have to be repaid, but the foreign owners receive a share of the profits (dividends).",
    [
      "Foreign debt: borrowings from overseas that must be repaid with interest",
      "Foreign equity: overseas ownership of Australian assets; no repayment, but profits/dividends flow overseas",
    ]),
  sa(49,
    "The balance of payments is a systematic record of all the economic transactions between the residents of a country and the rest of the world over a period of time. It records trade in goods and services, primary and secondary income flows, and financial and capital flows. It shows how a country is paying its way internationally and how its trade is being financed.",
    [
      "Defines the balance of payments as a record of all international transactions over a period",
      "Identifies what it records (trade in goods and services, income flows, financial/capital flows)",
      "Notes its purpose: shows how a country pays its way / finances its trade internationally",
    ]),
  sa(50,
    "Australia's domestic savings are not large enough to fund all the profitable investment opportunities in the economy — in infrastructure, mining, housing and business expansion. Foreign investment (both debt and equity) provides additional funds, allowing more investment, faster growth in productive capacity and more jobs than would be possible using domestic savings alone.",
    [
      "Explains that domestic saving is insufficient to fund all profitable domestic investment",
      "Explains that foreign investment provides extra funds, allowing more investment / growth / employment",
    ]),
];

export const answers: AnswerSet = Object.fromEntries([...mcAnswers, ...saAnswers]);
