import type { Answer, AnswerSet } from "@/lib/types";

// Answer key for y11-physics-preliminary. NO "server-only" import here (the
// validator reads it); only re-exported via content/answers/index.ts, which is
// server-only. Never import from a client component.

const U = "y11-physics-preliminary";
const p2 = (n: number) => String(n).padStart(2, "0");

function ma(n: number, correctText: string, why: string): [string, Answer] {
  return [`${U}.m${p2(n)}`, { correctText, rubric: [why] }];
}

function sa(n: number, model: string, rubric: string[]): [string, Answer] {
  return [`${U}.s${p2(n)}`, { modelAnswer: model, rubric }];
}

const mcAnswers: Array<[string, Answer]> = [
  ma(1, "Displacement.", "Displacement has both magnitude and direction, so it is a vector; distance, speed and time are scalars."),
  ma(2, "400 m and 0 m.", "Distance is the total path length (one lap = 400 m); displacement is the straight-line change in position, which is zero because start and finish coincide."),
  ma(3, "instantaneous velocity.", "On a displacement–time graph, the slope is the rate of change of displacement, which is velocity."),
  ma(4, "moving at constant velocity with zero acceleration.", "A horizontal section of a velocity–time graph means the velocity is not changing, so acceleration is zero."),
  ma(5, "displacement of the object.", "The area under a velocity–time graph is velocity × time, which gives displacement."),
  ma(6, "its velocity is changing in magnitude or direction.", "Acceleration is any change in velocity; a change in direction alone (e.g. circular motion) is still acceleration."),
  ma(7, "remain at rest, or continue moving at constant velocity in a straight line.", "Newton's first law (inertia): with no net force, an object's state of motion does not change."),
  ma(8, "a smaller acceleration.", "From Fnet = ma, for a fixed net force a is inversely proportional to m."),
  ma(9, "the gravitational pull of the book on the Earth.", "Newton's third law pairs act on different objects; the reaction to Earth pulling the book is the book pulling the Earth."),
  ma(10, "the driving force is equal in size to the total of friction and air resistance.", "Constant velocity means zero net force, so the forward and backward forces must balance."),
  ma(11, "slightly larger.", "It takes a bit more force to start an object sliding than to keep it sliding, so maximum static friction exceeds kinetic friction."),
  ma(12, "zero.", "Constant velocity means no acceleration, so by Newton's first law the net force is zero (gravity component down the slope is balanced by friction)."),
  ma(13, "the object moves and the force has a component in the direction of motion.", "Work = force × displacement in the direction of the force; no displacement, or a perpendicular force, means no work."),
  ma(14, "decrease and increase.", "As the ball rises it slows (KE falls) and gains height (GPE rises); mechanical energy is transformed from KE to GPE."),
  ma(15, "no net external force acts on the system.", "Conservation of momentum requires the system to be isolated (internal forces cancel by Newton's third law)."),
  ma(16, "momentum is conserved but kinetic energy is not.", "Momentum is always conserved in an isolated collision; in an inelastic collision some KE is converted to heat, sound or deformation."),
  ma(17, "increase the time over which the car's momentum changes.", "Impulse = force × time = change in momentum; for the same momentum change, a longer time means a smaller force."),
  ma(18, "twice the momentum and twice the kinetic energy.", "Momentum p = mv is proportional to m; kinetic energy ½mv² is also proportional to m when v is the same."),
  ma(19, "perpendicular to the direction the wave travels.", "That is the defining feature of a transverse wave; in a longitudinal wave the oscillation is parallel to the wave's travel."),
  ma(20, "longitudinal wave, with compressions and rarefactions.", "Sound in air is a pressure wave in which air particles oscillate back and forth along the direction of travel."),
  ma(21, "wavelength and amplitude.", "The crest-to-crest distance is one wavelength; the distance from the rest position to a crest is the amplitude."),
  ma(22, "time taken for one complete wave (one full oscillation) to pass a point.", "Period is a time; frequency is how many waves pass per second, and wavelength/amplitude are distances."),
  ma(23, "halve.", "From v = fλ with v constant, wavelength is inversely proportional to frequency."),
  ma(24, "All electromagnetic waves travel at the same speed in a vacuum.", "All EM waves travel at c in a vacuum; they differ in frequency, wavelength and energy, and they do not need a medium."),
  ma(25, "decreases in proportion to one over the distance squared.", "The same energy spreads over a sphere whose area grows as r², so intensity falls as 1/r²."),
  ma(26, "toward the normal.", "Light slows on entering a denser medium (glass), so it bends toward the normal."),
  ma(27, "how much the medium slows light compared with a vacuum.", "Refractive index n = c ÷ (speed of light in the medium); a higher n means light travels more slowly in the medium."),
  ma(28, "from a medium of higher refractive index toward one of lower refractive index, at an angle greater than the critical angle.", "TIR needs light going from a denser to a less dense medium and an angle of incidence beyond the critical angle."),
  ma(29, "similar to, or smaller than, the wavelength of the wave.", "Significant diffraction (bending/spreading) occurs when the gap or obstacle is comparable to or smaller than the wavelength."),
  ma(30, "destructive interference — the displacements cancel.", "By superposition, a crest and an equal trough add to zero displacement at that point."),
  ma(31, "nodes.", "Nodes are points of zero displacement in a standing wave; antinodes are points of maximum displacement."),
  ma(32, "compressed to a shorter wavelength and higher frequency.", "As the source approaches, each successive wavefront is emitted closer, shortening the wavelength and raising the observed frequency (pitch)."),
  ma(33, "observed wavelength is longer than the wavelength that was emitted.", "A receding source stretches the waves to longer wavelengths — toward the red end of the spectrum."),
  ma(34, "louder.", "Amplitude determines the energy carried and hence loudness; frequency determines pitch."),
  ma(35, "electrons have been transferred from the cloth to the rod.", "The rod gains extra electrons, giving it a net negative charge; charge is transferred, not created."),
  ma(36, "positive.", "Field lines point away from positive charges and toward negative charges."),
  ma(37, "one positive and one negative (opposite charges).", "Field lines run from the positive charge to the negative charge, so the charges are opposite."),
  ma(38, "one quarter as large.", "Coulomb's law: force is inversely proportional to the square of the separation, so doubling r divides the force by four."),
  ma(39, "uniform — the same strength and direction everywhere between the plates.", "Except near the edges, the field between parallel plates is uniform, shown by evenly spaced parallel field lines."),
  ma(40, "positive charge, from the positive terminal to the negative terminal around the external circuit.", "Conventional current is defined as positive-charge flow; electrons actually drift the opposite way."),
  ma(41, "made longer.", "Resistance increases with length and with temperature, and decreases with cross-sectional area and with using a better conductor."),
  ma(42, "double.", "For an ohmic conductor, V = IR with R constant, so current is proportional to voltage."),
  ma(43, "increase and decrease.", "Series resistances add, so total resistance rises; with a fixed supply voltage, a higher total resistance means a smaller current."),
  ma(44, "the same, and equal to the supply voltage.", "Each parallel branch is connected directly across the supply, so all branches have the same voltage."),
  ma(45, "decrease.", "Adding a parallel path gives the current more routes, lowering the total (equivalent) resistance below that of either resistor."),
  ma(46, "an ammeter must carry the same current as the component, and a voltmeter must have the same voltage across it as the component.", "Series placement lets the ammeter read the component's current; parallel placement lets the voltmeter read the component's voltage."),
  ma(47, "from the north pole to the south pole.", "By convention, magnetic field lines emerge from the north pole and enter the south pole outside the magnet."),
  ma(48, "concentric circles around the wire.", "The magnetic field of a straight current-carrying wire circles the wire; its direction is given by the right-hand grip rule."),
  ma(49, "stronger.", "The field inside a solenoid increases with the current and with the number of turns per unit length."),
  ma(50, "becomes strongly magnetised when current flows and loses its magnetism quickly when the current stops.", "Soft iron is a temporary magnet — ideal for an electromagnet that must switch on and off; steel would retain magnetism."),
];

const saAnswers: Array<[string, Answer]> = [
  sa(1,
    "A scalar quantity has magnitude (size) only — for example, speed or mass. A vector quantity has both magnitude and direction — for example, velocity or force.",
    ["Defines a scalar as having magnitude only, with a valid example", "Defines a vector as having magnitude and direction, with a valid example"]),
  sa(2,
    "Distance is the total length of the path travelled and is a scalar. Displacement is the straight-line change in position from start to finish, together with its direction, and is a vector. For example, walking 3 km north then 3 km south gives a distance of 6 km but a displacement of zero.",
    ["States distance is the total path length (scalar)", "States displacement is the straight-line change in position with direction (vector), with an example"]),
  sa(3,
    "Speed is a scalar — it is the rate at which distance is covered, with no direction. Velocity is a vector — it is the rate of change of displacement, so it includes a direction. An object can travel at constant speed but changing velocity if its direction changes.",
    ["States speed is the rate of covering distance (scalar, no direction)", "States velocity is the rate of change of displacement (vector, includes direction)"]),
  sa(4,
    "In the first section the line rises from zero, so the object accelerates uniformly from rest (its velocity increases at a constant rate). In the middle section the line is horizontal, so the object moves at constant velocity with zero acceleration. In the final section the line falls back to zero, so the object decelerates uniformly until it stops.",
    ["First section: uniform acceleration from rest (velocity increasing)", "Middle section: constant velocity, zero acceleration", "Final section: uniform deceleration to rest"]),
  sa(5,
    "The acceleration is the gradient (slope) of the velocity–time graph — the change in velocity divided by the change in time. The displacement is the area between the graph line and the time axis over the interval of interest.",
    ["Acceleration = gradient / slope of the velocity–time graph", "Displacement = area under the velocity–time graph"]),
  sa(6,
    "Acceleration is any change in velocity. Velocity is a vector, so even if the speed (magnitude) stays constant, an object moving in a circle is continuously changing direction, which means its velocity is changing and it is therefore accelerating (toward the centre of the circle).",
    ["States acceleration is a change in velocity (a vector quantity)", "Explains that circular motion continuously changes the direction of the velocity, so the object accelerates"]),
  sa(7,
    "First law: an object remains at rest, or continues moving at constant velocity in a straight line, unless acted on by a net external force. Second law: the net force on an object equals its mass times its acceleration (Fnet = ma), and the acceleration is in the direction of the net force. Third law: when one object exerts a force on a second object, the second exerts an equal and opposite force on the first.",
    ["States the first law (inertia)", "States the second law (Fnet = ma; acceleration in the direction of the net force)", "States the third law (equal and opposite forces on different objects)"]),
  sa(8,
    "A rocket carries fuel that it burns and expels backward as hot exhaust gas at high speed. The rocket exerts a large force on the exhaust gases (pushing them backward). By Newton's third law, the exhaust gases exert an equal and opposite force on the rocket (pushing it forward). This forward reaction force is the thrust, and it does not need anything external to push against.",
    ["States the rocket pushes exhaust gas backward (action force)", "States that by Newton's third law the gas pushes the rocket forward with an equal and opposite force", "Concludes this forward thrust needs no external object to push against"]),
  sa(9,
    "Because the car moves at constant velocity, its acceleration is zero, so by Newton's first (and second) law the net force on it is zero. This means the forces must be balanced: the upward normal force equals the downward weight, and the forward driving force equals the total of the backward friction and air resistance.",
    ["States constant velocity means zero acceleration and therefore zero net force", "States the vertical forces balance (normal force = weight)", "States the horizontal forces balance (driving force = friction + air resistance)"]),
  sa(10,
    "Static friction acts between surfaces that are not sliding relative to each other; it can vary in size up to a maximum value and prevents motion from starting. Kinetic (sliding) friction acts between surfaces that are sliding past each other; it is roughly constant and is usually a little smaller than the maximum static friction.",
    ["Static friction: acts when surfaces are not sliding; adjusts up to a maximum and prevents motion starting", "Kinetic friction: acts when surfaces slide; roughly constant and slightly less than maximum static friction"]),
  sa(11,
    "As the ramp is tilted, the component of the box's weight acting down the slope increases while the component pressing into the slope (and hence the maximum static friction) decreases. The box stays still while friction can balance the down-slope weight component. Once the down-slope component exceeds the maximum static friction, the forces are no longer balanced, there is a net force down the slope, and the box begins to slide.",
    ["Explains the down-slope component of weight increases as the angle increases", "Explains the maximum static friction available decreases (smaller normal force)", "Concludes sliding begins when the down-slope weight component exceeds the maximum static friction"]),
  sa(12,
    "A conservative force is one for which the work done in moving an object between two points does not depend on the path taken, and the work done around any closed loop is zero. Gravity is an example (also the spring force). This means potential energy can be defined for a conservative force.",
    ["Defines a conservative force (work done is path-independent / zero around a closed loop)", "Gives a valid example (gravity or the elastic/spring force)"]),
  sa(13,
    "At the highest point the bob is momentarily at rest, so it has maximum gravitational potential energy and no kinetic energy. As it swings down, gravitational potential energy is transformed into kinetic energy, so it speeds up, reaching maximum kinetic energy and minimum potential energy at the lowest point. As it rises on the other side, kinetic energy is transformed back into gravitational potential energy. With no friction, the total mechanical energy stays constant throughout.",
    ["Highest point: maximum GPE, zero (minimum) KE", "Swinging down: GPE is transformed into KE, reaching maximum KE at the lowest point", "Rising again: KE is transformed back into GPE; total mechanical energy stays constant"]),
  sa(14,
    "Total mechanical energy (kinetic plus potential) is conserved when only conservative forces (such as gravity) do work on the system — that is, when there are no resistive or friction forces removing energy as heat or sound.",
    ["States only conservative forces do work / no work is done by friction or resistance", "States that under this condition the sum of kinetic and potential energy stays constant"]),
  sa(15,
    "During the collision the two objects exert forces on each other. By Newton's third law these forces are equal in size and opposite in direction, and they act for the same length of time, so the impulses on the two objects are equal and opposite. This means the momentum gained by one object is exactly equal to the momentum lost by the other, so the total momentum of the system is unchanged — provided no net external force acts.",
    ["States the two objects exert equal and opposite forces on each other (Newton's third law)", "States these forces act for the same time, so the impulses (and momentum changes) are equal and opposite", "Concludes the total momentum of the system is unchanged (in the absence of external forces)"]),
  sa(16,
    "Classify the collision by calculating and comparing the total kinetic energy of the objects before and after the collision. If the total kinetic energy is the same before and after, the collision is elastic. If total kinetic energy is lost (converted to heat, sound or deformation), the collision is inelastic. In both cases, total momentum is conserved.",
    ["States you compare total kinetic energy before and after the collision", "Elastic: total kinetic energy is unchanged", "Inelastic: total kinetic energy decreases (energy converted to other forms); momentum still conserved"]),
  sa(17,
    "When you land, your momentum must be reduced to zero. The impulse needed equals your change in momentum, and impulse is the force multiplied by the time over which it acts. By bending your knees you increase the time taken to stop, so for the same change in momentum the average force on your legs is smaller.",
    ["States that stopping requires a fixed change in momentum / impulse", "States impulse = force × time", "Concludes that increasing the stopping time reduces the average force"]),
  sa(18,
    "In a transverse wave the particles of the medium oscillate perpendicular to the direction the wave (and its energy) travels — for example, a wave on a string or a water surface wave. In a longitudinal wave the particles oscillate parallel to the direction the wave travels, producing compressions and rarefactions — for example, a sound wave in air.",
    [
      "Transverse: particle motion perpendicular to the direction of wave travel",
      "Longitudinal: particle motion parallel to the direction of wave travel (compressions/rarefactions)",
      "Gives a valid example of each type",
    ]),
  sa(19,
    "The wavelength is the distance over which the wave's shape repeats — for example, the distance between two adjacent crests. On the diagram this is X. The amplitude is the maximum displacement of a particle from its rest position. On the diagram this is Y.",
    ["Defines wavelength (distance for one full wave / crest to crest) and identifies it as X", "Defines amplitude (maximum displacement from rest) and identifies it as Y"]),
  sa(20,
    "The frequency is the number of complete waves passing a point each second, and the period is the time for one complete wave to pass. They are reciprocals of each other: frequency = 1 ÷ period. So a higher frequency means a shorter period.",
    ["States frequency is waves per second and period is the time for one wave", "States they are reciprocals (frequency = 1/period), so a higher frequency means a shorter period"]),
  sa(21,
    "The speed of a wave equals its frequency multiplied by its wavelength (v = fλ). If the speed is fixed and the frequency is increased, the wavelength must decrease so that the product stays the same — wavelength is inversely proportional to frequency at constant speed.",
    ["States the relationship v = fλ (speed = frequency × wavelength)", "Explains that with speed constant, increasing frequency requires the wavelength to decrease (inverse relationship)"]),
  sa(22,
    "Sound is a mechanical wave: it travels as vibrations passed from particle to particle, so it needs a medium such as air, water or a solid. A vacuum has no particles to vibrate, so sound cannot travel through it. Light is an electromagnetic wave — an oscillating electric and magnetic field — which can travel through empty space, so it can cross a vacuum.",
    ["States sound is a mechanical wave that needs particles / a medium to transmit vibrations, so it cannot cross a vacuum", "States light is an electromagnetic wave that does not need a medium, so it can travel through a vacuum"]),
  sa(23,
    "A vibrating source (such as a speaker cone) pushes and pulls on the air next to it, creating regions of higher pressure (compressions) and lower pressure (rarefactions). Each layer of air pushes on the next, passing the disturbance along. The air particles themselves only oscillate back and forth about a fixed position; it is the energy of the vibration, not the air, that travels from the source to the listener.",
    ["Describes a vibrating source creating compressions and rarefactions in the air", "Explains the disturbance is passed from particle to particle along the medium", "States the particles oscillate about fixed positions; it is energy that is transferred, not the air itself"]),
  sa(24,
    "Light spreads out from a point source in all directions. As it travels further, the same amount of energy is spread over the surface of a larger sphere, and the area of a sphere increases with the square of its radius. So the intensity (power per unit area) falls in proportion to one over the distance squared: doubling the distance reduces the intensity to a quarter.",
    ["States the same energy is spread over a larger area as distance increases", "States the area grows as the square of the distance", "Concludes intensity is proportional to 1 / distance², e.g. doubling the distance quarters the intensity"]),
  sa(25,
    "Light travels more slowly in glass than in air because glass is optically denser (higher refractive index). When the ray meets the boundary at an angle, one side of the wavefront enters the glass and slows before the other side, which swings the ray around. As it enters the denser glass, the ray bends toward the normal.",
    ["States light slows down on entering the glass (higher refractive index / optically denser)", "Explains the change of speed at the boundary causes the ray to change direction", "States the ray bends toward the normal on entering the denser medium"]),
  sa(26,
    "Total internal reflection requires two conditions. First, the light must be travelling from a medium of higher refractive index toward one of lower refractive index (from denser to less dense, e.g. glass to air). Second, the angle of incidence at the boundary must be greater than the critical angle for those two media. When both are met, no light is refracted out and all of it is reflected back inside.",
    ["Condition 1: light travelling from a higher-index (denser) medium toward a lower-index (less dense) medium", "Condition 2: the angle of incidence is greater than the critical angle"]),
  sa(27,
    "Diffraction is the spreading out (or bending) of a wave as it passes through a gap or around an obstacle. It is most noticeable when the size of the gap or obstacle is similar to, or smaller than, the wavelength of the wave; when the gap is much larger than the wavelength there is very little spreading.",
    ["Defines diffraction as the spreading / bending of a wave at a gap or obstacle", "States it is most noticeable when the gap or obstacle is comparable to or smaller than the wavelength"]),
  sa(28,
    "The principle of superposition states that when two waves overlap, the resultant displacement at each point is the sum of the individual displacements. Constructive interference occurs where the waves are in phase — for example, crest meeting crest — so the displacements add to give a larger amplitude. Destructive interference occurs where the waves are out of phase — crest meeting trough — so the displacements partly or completely cancel, giving a smaller or zero amplitude.",
    ["States the principle of superposition (resultant displacement = sum of individual displacements)", "Constructive interference: waves in phase (crest + crest) add to a larger amplitude", "Destructive interference: waves out of phase (crest + trough) cancel to a smaller/zero amplitude"]),
  sa(29,
    "When a wave travels along the string it reflects off the fixed ends and travels back. The forward and reflected waves overlap and, at certain frequencies, superpose to produce a standing wave whose pattern does not appear to move along the string. A node is a point that stays still (zero displacement), where the two waves always cancel; an antinode is a point that oscillates with maximum amplitude, where the two waves always reinforce.",
    ["Explains a standing wave forms from the superposition of the wave and its reflection from the fixed ends", "Defines a node as a point of zero displacement (waves cancel)", "Defines an antinode as a point of maximum displacement (waves reinforce)"]),
  sa(30,
    "As the car approaches, each successive sound wave is emitted from a position closer to you, so the wavefronts are bunched together. This shortens the wavelength reaching you and raises the frequency, so the horn sounds higher in pitch. As the car moves away, the wavefronts are stretched out, lengthening the wavelength and lowering the frequency, so the horn sounds lower in pitch. The actual frequency produced by the horn does not change.",
    ["Approaching: wavefronts bunch up, wavelength shortens, observed frequency (pitch) rises", "Receding: wavefronts stretch out, wavelength lengthens, observed frequency (pitch) falls", "Notes the source frequency itself is unchanged"]),
  sa(31,
    "Redshift is an increase in the observed wavelength of light from an object compared with the wavelength it emitted, shifting the light toward the red end of the spectrum. It is caused by the source moving away from us, so a redshifted galaxy is receding from Earth — and the larger the redshift, the faster it is moving away.",
    ["States redshift is an increase in observed wavelength (shift toward the red end)", "States it indicates the galaxy is moving away from Earth (and greater redshift = faster recession)"]),
  sa(32,
    "The loudness of a sound depends on the amplitude of the sound wave — a larger amplitude carries more energy and sounds louder. The pitch of a sound depends on the frequency of the wave — a higher frequency is heard as a higher pitch.",
    ["States loudness depends on the amplitude of the wave", "States pitch depends on the frequency of the wave"]),
  sa(33,
    "Infrared radiation is strongly absorbed by materials and transfers heat, so it is used in thermal imaging cameras and heat lamps, and in remote controls. Ultraviolet radiation carries more energy than visible light and can cause chemical changes and fluorescence, so it is used for sterilising equipment (it damages microorganisms) and for detecting forgeries and security marks that fluoresce.",
    ["Infrared: valid application linked to its property (e.g. heat transfer → thermal imaging / heating)", "Ultraviolet: valid application linked to its property (e.g. higher energy → sterilisation / fluorescence detection)"]),
  sa(34,
    "When two suitable materials are rubbed together, friction gives some electrons enough energy to transfer from one surface to the other. The material that gains electrons ends up with more negative charge than positive, so it is negatively charged; the material that loses electrons is left positively charged. No charge is created — it is only moved from one object to the other, so the charges are equal and opposite.",
    ["Explains friction causes electrons to transfer from one surface to the other", "States the object gaining electrons becomes negative and the object losing electrons becomes positive", "Notes charge is transferred, not created (equal and opposite charges)"]),
  sa(35,
    "In charging by conduction, a charged object is touched to a neutral object; electrons flow between them until they share the charge, so the neutral object ends up with the same sign of charge as the charging object. In charging by induction, a charged object is brought near (but not touching) a neutral conductor; this pushes electrons in the conductor toward one end, and if the far side is then earthed and the earth removed, the conductor is left with a charge opposite in sign to the charging object.",
    [
      "Conduction: contact with a charged object; charge is shared; the object gains the same sign of charge",
      "Induction: no contact; charges in the conductor are separated (rearranged), and after earthing the object is left with the opposite sign of charge",
      "Contrasts the two: conduction requires contact and gives the same sign; induction needs no contact and gives the opposite sign",
    ]),
  sa(36,
    "Electric field lines show the direction of the force that a small positive test charge would feel at each point — the line points the way the force acts. The spacing of the lines shows the strength of the field: lines close together mean a strong field, lines far apart mean a weak field (so the field is strongest near the charge). Because the lines in the diagram point outward, away from the charge, the charge must be positive.",
    ["States field-line direction shows the direction of force on a positive test charge", "States line spacing shows field strength (closer = stronger)", "Concludes the charge is positive because the lines point outward"]),
  sa(37,
    "By Coulomb's law, the electrostatic force between two point charges is directly proportional to the product of the two charges — so making either charge larger increases the force. It is also inversely proportional to the square of the distance between them — so moving the charges further apart weakens the force rapidly (doubling the separation reduces the force to a quarter).",
    ["States force is proportional to the product of the two charges (larger charges → larger force)", "States force is inversely proportional to the square of the separation", "Illustrates the distance effect (e.g. double the distance → quarter the force)"]),
  sa(38,
    "Between two parallel charged plates (away from the edges), the electric field lines are straight, parallel and evenly spaced, running from the positive plate to the negative plate. Because the lines have the same direction and the same spacing everywhere in this region, the field has the same strength and direction at every point — it is uniform.",
    ["States the field lines between the plates are straight, parallel and evenly spaced", "Concludes the field has the same strength and direction everywhere, so it is uniform"]),
  sa(39,
    "The electric field between the plates points from the positive plate to the negative plate, which is the direction of the force on a positive charge. As the positive charge moves from the positive plate toward the negative plate, it moves in the direction of the force, so the field does positive work on it and its electric potential energy decreases. That lost potential energy is transformed into kinetic energy, so the charge speeds up.",
    ["States the charge moves in the direction of the electric force, so the field does work on it", "States the electric potential energy of the charge decreases", "States the lost potential energy is transformed into kinetic energy (the charge speeds up)"]),
  sa(40,
    "Conventional current is defined as a flow of positive charge from the positive terminal of the source, around the external circuit, to the negative terminal. In a metal wire the charge carriers are actually free electrons, which are negative, so they drift in the opposite direction — from the negative terminal to the positive terminal.",
    ["States conventional current is (positive) charge flow from + to − around the external circuit", "States electrons actually flow the opposite way, from − to +"]),
  sa(41,
    "In direct current (DC), charge flows in one direction only and the voltage has a constant polarity — for example, from a battery. In alternating current (AC), the direction of charge flow reverses periodically (the voltage swings positive and negative), as in mains electricity, which reverses 50 times per second in Australia.",
    ["DC: current flows in one direction, constant polarity (e.g. a battery)", "AC: current periodically reverses direction (e.g. mains supply)"]),
  sa(42,
    "The resistance of a wire increases with its length, because the charge carriers must travel through more material and collide more often. It decreases as the cross-sectional area increases, because a thicker wire gives the current more room to flow (more paths in parallel). It also increases with temperature, because the hotter atoms of the wire vibrate more and impede the flow of electrons more.",
    ["Length: resistance increases with length", "Cross-sectional area: resistance decreases as the wire gets thicker", "Temperature: resistance increases as the wire gets hotter"]),
  sa(43,
    "In a series circuit there is only one path, so the current is the same at every point, and the supply voltage is shared between the components (the voltages across the components add up to the supply voltage). In a parallel circuit there are several paths, so the total current from the supply splits between the branches (the branch currents add up to the total), and every branch has the full supply voltage across it.",
    [
      "Series current: the same at every point; parallel current: the total splits between branches (branch currents add)",
      "Series voltage: the supply voltage is shared between components (voltages add up to the supply)",
      "Parallel voltage: every branch has the full supply voltage across it",
    ]),
  sa(44,
    "Adding a resistor in parallel provides an extra pathway for the current to flow through. For a given supply voltage, more total current can now flow, which means the combination behaves as though it has a lower resistance than before. Since this is true whichever resistor you add, the equivalent resistance of a parallel combination is always less than the smallest individual resistance.",
    ["Explains that a parallel resistor adds another path for current", "Explains that more total current flows for the same voltage, so the effective resistance is lower", "Concludes the combined resistance is less than any single branch resistance"]),
  sa(45,
    "An ammeter measures current, and current is the same all the way along a single path, so the ammeter must be placed in the same path (in series) as the component to carry that component's current; it is built with a very low resistance so it hardly affects the circuit. A voltmeter measures the potential difference across a component, so it must be connected across the component (in parallel) to have the same voltage; it is built with a very high resistance so it draws almost no current.",
    ["Ammeter in series: to carry the same current as the component (has very low resistance)", "Voltmeter in parallel: to have the same voltage across it as the component (has very high resistance)"]),
  sa(46,
    "The magnetic field around a bar magnet forms closed loops. Outside the magnet the field lines run from the north pole around to the south pole; inside the magnet they run from south to north. The lines are closest together near the poles, where the field is strongest, and spread out further away.",
    ["Describes the field as loops running from north to south outside the magnet (south to north inside)", "Notes the field is strongest (lines closest) near the poles"]),
  sa(47,
    "The magnetic field around a long straight current-carrying wire consists of concentric circles centred on the wire, lying in planes perpendicular to the wire. The field is strongest close to the wire and weakens with distance; its direction is given by the right-hand grip rule (thumb along the current, fingers curl in the direction of the field).",
    ["Describes the field as concentric circles around the wire", "Notes the field weakens with distance and its direction is given by the right-hand grip rule"]),
  sa(48,
    "A current-carrying solenoid (a coil of wire) produces a magnetic field that is strong and roughly uniform along the inside of the coil, running parallel to the coil's axis, and emerges from one end (acting as a north pole) and enters the other (a south pole). Outside the solenoid the field looks just like that of a bar magnet, with field lines running from the north end around to the south end.",
    [
      "Describes a strong, roughly uniform field along the axis inside the solenoid",
      "States the solenoid has a north end and a south end (field emerges from one end, enters the other)",
      "States the external field has the same shape as that of a bar magnet",
    ]),
  sa(49,
    "The strength of an electromagnet can be increased by: increasing the current flowing through the coil; increasing the number of turns of wire in the coil (or the turns per unit length); and using a core made of a soft ferromagnetic material such as soft iron, which becomes strongly magnetised and greatly increases the field.",
    ["Way 1: increase the current in the coil", "Way 2: increase the number of turns (turns per unit length)", "Way 3: add / use a soft iron (ferromagnetic) core"]),
  sa(50,
    "Soft iron is easily magnetised when current flows through the coil, giving a strong field, but it loses almost all of its magnetism as soon as the current is switched off. This is exactly what an electromagnet needs, so it can be turned on and off. Steel would keep much of its magnetism after the current stopped (it would become a permanent magnet), so the electromagnet could not be switched off effectively.",
    ["States soft iron becomes strongly magnetised with current but loses its magnetism when the current stops", "States this allows the electromagnet to be switched on and off (steel would retain magnetism)"]),
];

const mcAnswers2: Array<[string, Answer]> = [
  ma(51, "The cyclist's velocity is continually changing because its direction changes, even though speed is constant.", "Velocity includes direction; going around a circle constantly changes direction, so velocity (and hence acceleration) is never constant."),
  ma(52, "Mass (scalar) and force (vector).", "Mass has magnitude only; force has both magnitude and direction, so it is a vector."),
  ma(53, "constant and directed downward, regardless of its speed.", "In free fall with no air resistance, the only force is gravity, giving a constant acceleration regardless of speed."),
  ma(54, "moving at a constant, non-zero velocity, since its acceleration is zero.", "A horizontal line above the axis on a velocity–time graph means the velocity is not changing but is not zero, so acceleration is zero."),
  ma(55, "uniform (constant) acceleration.", "A straight line on a velocity–time graph has a constant gradient, meaning velocity changes at a constant rate — uniform acceleration."),
  ma(56, "The first law — the passenger's body tends to remain in its state of motion (inertia) until an external force acts on it.", "Inertia (Newton's first law) means the passenger keeps moving forward until a seatbelt or other force acts on them."),
  ma(57, "hit the ground at the same time, since both accelerate at the same rate due to gravity.", "With no air resistance, gravitational acceleration does not depend on mass, so both objects fall together."),
  ma(58, "in the direction opposing the object's relative motion.", "Friction always opposes relative sliding motion between two surfaces."),
  ma(59, "double its acceleration.", "From Newton's second law, a = Fnet/m; with mass constant, acceleration is directly proportional to the net force."),
  ma(60, "air resistance has increased to exactly balance their weight, so the net force is zero and velocity is constant.", "Terminal velocity occurs when the upward drag force equals the downward weight, giving zero net force and constant speed."),
  ma(61, "A person pushes a box and it slides forward across the floor.", "Work requires a displacement in the direction of the applied force; the other options involve no displacement or a force perpendicular to the motion."),
  ma(62, "decrease and increase.", "As the pendulum falls, height (and so GPE) decreases while speed (and so KE) increases."),
  ma(63, "zero, because the gravitational force is always perpendicular to the satellite's velocity.", "Gravity provides centripetal force, always at right angles to the satellite's velocity, so it does no work over a full orbit."),
  ma(64, "both momentum and total kinetic energy are conserved.", "An elastic collision is defined as one in which both momentum and total kinetic energy are unchanged."),
  ma(65, "a perfectly inelastic collision.", "Objects that stick together after colliding undergo the maximum possible loss of kinetic energy, defining a perfectly inelastic collision."),
  ma(66, "increasing the time over which the passenger's momentum changes, reducing the average force experienced.", "By impulse = force × time, spreading the same momentum change over a longer time lowers the average force."),
  ma(67, "stationary, since their equal and opposite momenta cancel out.", "Momentum is conserved; two equal masses with equal and opposite momenta sum to zero, so the combined trolleys have zero momentum after sticking together."),
  ma(68, "increases the time of contact, reducing the force needed to stop the ball.", "Moving the hands back with the ball extends the time over which its momentum changes, reducing the force needed."),
  ma(69, "Wavelength and amplitude are distances; period is a time.", "Wavelength and amplitude are measured in metres; period is measured in seconds; frequency is measured in hertz (waves per second)."),
  ma(70, "energy from one place to another, without transferring matter.", "A wave is a disturbance that transfers energy through a medium (or through space); the particles of the medium do not travel with the wave."),
  ma(71, "more energy than wave B.", "The energy carried by a wave increases with the square of its amplitude, so a larger amplitude means more energy."),
  ma(72, "A sound wave in air, where compressions and rarefactions travel in the direction of energy transfer.", "This is the defining feature of a longitudinal wave; the other options are transverse waves."),
  ma(73, "The wave's speed and its wavelength both change.", "Frequency is fixed by the source; when a wave changes medium its speed changes, and since v = fλ, wavelength must change too."),
  ma(74, "frequency (and wavelength) of a wave due to relative motion between the source and the observer.", "The Doppler effect is the apparent change in observed frequency caused by relative motion between source and observer."),
  ma(75, "Violet.", "In the visible spectrum, wavelength increases from violet (shortest) through to red (longest)."),
  ma(76, "a shorter wavelength and higher frequency.", "X-rays lie beyond ultraviolet in the electromagnetic spectrum, with much shorter wavelength and higher frequency than visible light."),
  ma(77, "speeds up and bends away from the normal.", "Light speeds up moving into a less dense medium (air), so it bends away from the normal."),
  ma(78, "the refracted ray travels exactly along the boundary, at a refraction angle of 90°.", "The critical angle is defined as the angle of incidence that produces a 90° angle of refraction, the threshold for total internal reflection."),
  ma(79, "Light diffracts (spreads out) when passing through a very narrow slit.", "Diffraction is a wave-specific phenomenon that cannot be explained by a simple particle model travelling in straight lines."),
  ma(80, "constructive interference, producing a larger amplitude.", "By superposition, two waves in phase add their displacements, producing a larger resultant amplitude."),
  ma(81, "waves travelling in opposite directions that interfere to produce fixed nodes and antinodes.", "A standing wave results from the superposition of two identical waves travelling in opposite directions, typically an incident and a reflected wave."),
  ma(82, "frequency.", "Pitch is the perceived property that corresponds to a sound wave's frequency; amplitude corresponds to loudness."),
  ma(83, "different wavelengths.", "From v = fλ, with speed fixed, a different frequency must correspond to a different wavelength."),
  ma(84, "longer than visible light but shorter than most radio waves.", "In the electromagnetic spectrum, microwaves sit between infrared/visible light and radio waves, with a wavelength longer than visible light and generally shorter than radio waves."),
  ma(85, "loses electrons, leaving an excess of positive charge.", "An object becomes positively charged when it has fewer electrons than protons, i.e. it has lost electrons."),
  ma(86, "does not require direct contact between the charged object and the object being charged.", "Induction separates charge in a nearby object using the electric field of a charged object, without them touching."),
  ma(87, "a charged object experiences a force.", "An electric field is defined by its effect: it exerts a force on any charge placed within it."),
  ma(88, "a small positive test charge placed at that point.", "By convention, electric field direction is defined as the direction of the force on a small positive test charge."),
  ma(89, "repel each other.", "Like charges repel; unlike charges attract — a fundamental property of electric charge."),
  ma(90, "doubles.", "Coulomb's law: force is directly proportional to the magnitude of each charge, so doubling one charge doubles the force."),
  ma(91, "constant in size and direction anywhere between the plates, due to the uniform field.", "The field between oppositely charged parallel plates is uniform (except near the edges), so the force on a charge there is constant."),
  ma(92, "free (delocalised) electrons through the metal's lattice.", "In a metal, current is carried by mobile (delocalised) electrons drifting through the fixed lattice of positive ions."),
  ma(93, "Increasing its cross-sectional area.", "Resistance decreases as cross-sectional area increases; it increases with length, temperature, and with a less conductive material."),
  ma(94, "is not a straight line, because the globe's resistance changes as it heats up.", "A non-ohmic device does not obey a simple proportional V–I relationship, because its resistance varies (e.g. rising as a filament heats up)."),
  ma(95, "also go out, because the circuit is broken and no current can flow.", "In series, there is only one path for current, so a break anywhere stops current everywhere in that loop."),
  ma(96, "continue to operate normally, since each branch has its own complete path for current.", "Parallel branches provide independent current paths, so removing one branch does not stop current in the others."),
  ma(97, "increase, since the current must pass through each resistor in turn.", "Series resistances add directly, since the same current must overcome the resistance of each one in turn."),
  ma(98, "it is connected in series and should not significantly change the current it is measuring.", "A very low resistance ammeter added in series barely affects the circuit's total resistance and current."),
  ma(99, "increasing the number of turns of wire or adding a soft iron core.", "Solenoid field strength increases with current, number of turns, and is greatly boosted by a ferromagnetic (soft iron) core."),
  ma(100, "deflect, showing that the current produces a magnetic field around the wire.", "A current-carrying wire produces its own magnetic field, which will deflect a nearby compass needle — the basis of Oersted's discovery."),
];

const saAnswers2: Array<[string, Answer]> = [
  sa(51,
    "Velocity is the rate of change of displacement, and since displacement is a vector (it has both magnitude and direction), velocity is also a vector. Speed is the rate at which distance is covered, and since distance has magnitude only, speed is a scalar with no associated direction.",
    ["States velocity is derived from displacement (a vector), so it is a vector", "States speed is derived from distance (a scalar), so it is a scalar"]),
  sa(52,
    "Acceleration is defined as any change in velocity, and velocity includes both speed and direction. Even though the object's speed stays constant on a circular path, its direction of travel is continuously changing, so its velocity is continuously changing — meaning it is accelerating, towards the centre of the circle.",
    ["States acceleration is a change in velocity, which includes direction as well as speed", "Explains that constant direction change on a circular path means velocity (and hence motion) is accelerating"]),
  sa(53,
    "The graph starts at the origin and rises as a straight line with a constant positive slope, showing uniform acceleration from rest. It then becomes a horizontal line, showing a period of constant velocity with zero acceleration. Finally the line falls as a straight line with a constant negative slope back down to the time axis, showing uniform deceleration back to rest.",
    ["Describes the first section: a straight rising line from the origin (uniform acceleration from rest)", "Describes the middle section: a horizontal line (constant velocity, zero acceleration)", "Describes the final section: a straight falling line back to zero (uniform deceleration to rest)"]),
  sa(54,
    "Average velocity is the total displacement divided by the total time taken for a journey, giving an overall picture that ignores variations along the way. Instantaneous velocity is the velocity of an object at one particular moment in time, which can be found from the gradient of a displacement–time graph at that instant.",
    ["Defines average velocity as total displacement over total time", "Defines instantaneous velocity as the velocity at a single moment (gradient at a point on a displacement–time graph)"]),
  sa(55,
    "By Newton's second law, acceleration equals the net force divided by mass. Gravity exerts a force on an object that is directly proportional to its mass (its weight), so when this weight is divided by the object's mass to find the acceleration, the mass cancels out. This means every object experiences the same gravitational acceleration, regardless of how much mass it has, as long as air resistance is ignored.",
    ["States Newton's second law: acceleration = net force ÷ mass", "States gravitational force (weight) on an object is proportional to its mass", "Explains that dividing this force by the mass cancels the mass, giving the same acceleration for every object"]),
  sa(56,
    "Newton's first law states that an object will remain at rest, or continue moving at a constant velocity in a straight line, unless acted on by an unbalanced (net) external force. Inertia is the tendency of an object to resist a change in its state of motion — the reason a stationary object stays still and a moving object keeps moving unless something forces it to change.",
    ["States Newton's first law: an object stays at rest or at constant velocity unless a net force acts on it", "Defines inertia as an object's tendency to resist a change in its state of motion"]),
  sa(57,
    "Newton's second law states that acceleration equals net force divided by mass (a = Fnet/m). For the same driving force, an object with a larger mass will have a smaller acceleration, because acceleration is inversely proportional to mass. A heavily loaded truck has much more mass than an empty one, so the same driving force produces a much smaller acceleration in the loaded truck.",
    ["States Newton's second law relates acceleration, net force and mass (a = Fnet/m)", "Explains that acceleration is inversely proportional to mass for a fixed force", "Concludes the more massive (loaded) truck accelerates less for the same force"]),
  sa(58,
    "A net force is the single overall force that results from combining all the individual forces acting on an object, taking their directions into account. When the net force on an object is zero, the object's velocity does not change — it remains at rest if it was at rest, or continues moving at a constant velocity in a straight line if it was already moving.",
    ["Defines net force as the overall combined effect of all forces acting on an object", "States that zero net force means no change in velocity (remains at rest or moves at constant velocity)"]),
  sa(59,
    "Newton's third law states that whenever one object exerts a force on a second object, the second object exerts an equal and opposite force back on the first — forces always arise in interacting pairs. These paired forces do not cancel out for a single object because they act on two different objects, not on the same one; only forces acting on the same object can be combined to find a net force.",
    ["States Newton's third law: forces occur in equal and opposite pairs", "States the pair arises between two interacting objects", "Explains that the paired forces act on different objects, so they cannot cancel for either object individually"]),
  sa(60,
    "Mass is the amount of matter in an object, measured in kilograms, and does not change with location. Weight is the force of gravity acting on that mass, measured in newtons, and depends on the strength of the local gravitational field, so an object's weight would be different on the Moon even though its mass is unchanged.",
    ["Defines mass as the amount of matter (kg), constant everywhere", "Defines weight as the gravitational force on that mass (N), which depends on the local gravitational field"]),
  sa(61,
    "Friction is useful when it allows control or grip, such as the friction between shoes and the ground that lets a person walk without slipping. Friction is unwanted when it causes energy loss or wear, such as friction inside a car engine, which converts useful mechanical energy into heat and wastes fuel.",
    ["Gives a valid example of useful friction", "Explains why it is useful there (grip/control)", "Gives a valid example of unwanted friction and explains why (energy loss/wear)"]),
  sa(62,
    "Kinetic energy is the energy an object has because of its motion. Gravitational potential energy is the energy an object has because of its position in a gravitational field, such as its height above the ground.",
    ["Defines kinetic energy as the energy of motion", "Defines gravitational potential energy as energy due to position/height in a gravitational field"]),
  sa(63,
    "The law of conservation of energy states that energy cannot be created or destroyed, only transformed from one form into another or transferred from one object to another; the total amount of energy in an isolated system stays constant. For example, as a ball rolls down a hill, its gravitational potential energy is transformed into kinetic energy as it speeds up.",
    ["States energy cannot be created or destroyed, only transformed or transferred", "States the total energy in an isolated system stays constant", "Gives a valid example of one form of energy being transformed into another"]),
  sa(64,
    "An isolated system is one on which no net external force acts, so no external impulse changes the total momentum of the objects within it. Any forces that occur are internal, acting between the objects inside the system, and by Newton's third law such internal forces cancel out when the momentum of the whole system is considered.",
    ["Defines an isolated system as one with no net external force acting on it", "Explains that only internal forces act within it, which cancel by Newton's third law and so do not change total momentum"]),
  sa(65,
    "When two objects collide, each exerts a force on the other, and by Newton's third law these two forces are equal in size and opposite in direction, acting for the same length of time. This means the impulse (and hence the change in momentum) of one object is equal and opposite to the impulse on the other, so the individual momenta change but the total momentum of the two-object system — the sum of the two — stays the same.",
    ["States that the two colliding objects exert equal and opposite forces on each other (Newton's third law)", "Explains that this gives equal and opposite impulses/momentum changes for the same time", "Concludes the individual momenta change but their sum (total momentum) stays constant"]),
  sa(66,
    "In an elastic collision, both the total momentum and the total kinetic energy of the system are conserved. In an inelastic collision, total momentum is still conserved, but some kinetic energy is converted into other forms, such as heat, sound or the energy of permanent deformation, so total kinetic energy is not conserved.",
    ["States that momentum is conserved in both types of collision", "States that kinetic energy is conserved in an elastic collision but not in an inelastic collision"]),
  sa(67,
    "Impulse equals the change in momentum, and impulse is also equal to the average force multiplied by the time over which it acts. For a car bringing about the same total change in momentum (coming to a stop from the same speed), braking gently spreads this change in momentum over a longer time, so the average force needed on the passengers (and the car) is smaller than if the car stopped suddenly over a shorter time.",
    ["States impulse = change in momentum", "States impulse = average force × time", "Explains that for the same momentum change, a longer stopping time means a smaller average force"]),
  sa(68,
    "In a crash, a seatbelt keeps the passenger moving with the car and extends the time over which their momentum changes to zero, spreading out the impulse needed to stop them. Because impulse equals average force multiplied by time, extending this time for the same change in momentum reduces the average force experienced by the passenger, lowering the risk of injury compared with being stopped suddenly (e.g. by hitting the windscreen).",
    ["States the seatbelt extends the time taken for the passenger's momentum to change to zero", "Explains that a longer time for the same momentum change means a smaller average force, reducing injury risk"]),
  sa(69,
    "The amplitude of a wave is the maximum displacement of a point in the medium from its rest (equilibrium) position. A wave with a larger amplitude carries more energy; the energy transferred by a wave increases as its amplitude increases.",
    ["Defines amplitude as the maximum displacement from the rest position", "States that a larger amplitude means the wave carries more energy"]),
  sa(70,
    "A wave transfers energy through a medium (or through space, for electromagnetic waves) without any net transfer of matter — the particles of the medium oscillate about a fixed position and return to it, rather than travelling along with the wave. In contrast, when an object moves from one place to another, the matter making up that object is physically transported to the new location.",
    ["States a wave transfers energy without transferring matter", "Explains the medium's particles oscillate about a fixed position rather than travelling with the wave", "Contrasts this with a moving object, where the matter itself is physically transported"]),
  sa(71,
    "A wave's speed equals its frequency multiplied by its wavelength. This means that for a wave travelling at a fixed speed, frequency and wavelength are inversely related: increasing one causes the other to decrease, so that their product (the speed) stays the same.",
    ["States the relationship: wave speed = frequency × wavelength", "Explains that at constant speed, frequency and wavelength are inversely related"]),
  sa(72,
    "The frequency of a wave is set by the source that creates it and depends only on how often the source vibrates, not on the medium the wave is travelling through. When the light crosses the boundary from glass into air, it enters a new medium in which it travels at a different speed, and since frequency stays fixed while speed changes, the wavelength must change too (from v = fλ) to keep the equation balanced.",
    ["States the wave's frequency is set by the source and does not change when it enters a new medium", "States the wave's speed changes when it crosses into the new medium", "Explains that because speed changes while frequency stays the same, the wavelength must change instead"]),
  sa(73,
    "As the wave moves into the less dense medium its speed increases while its frequency, set by the source, stays exactly the same. Because wave speed equals frequency multiplied by wavelength, an increase in speed with unchanged frequency means the wavelength must increase.",
    ["States frequency stays the same as the wave changes medium", "States that because speed increases with frequency unchanged, the wavelength must also increase"]),
  sa(74,
    "Diffraction — the spreading of a wave around an obstacle or through a gap — is most noticeable when the size of the gap or obstacle is similar to, or smaller than, the wavelength of the wave. Sound waves have much longer wavelengths than light waves, comparable to the size of everyday obstacles such as walls and doorways, so they diffract noticeably around corners; light has a far shorter wavelength, so it diffracts only very slightly around such large obstacles and appears to travel in straight lines, casting sharp shadows.",
    ["States diffraction is most noticeable when the gap/obstacle size is comparable to or smaller than the wavelength", "Explains that sound's much longer wavelength (comparable to everyday obstacles) makes it diffract noticeably", "Explains that light's much shorter wavelength means it diffracts far less around the same obstacles"]),
  sa(75,
    "Total internal reflection occurs when light travelling inside a denser medium strikes the boundary with a less dense medium at an angle of incidence greater than the critical angle for that pair of media. Instead of refracting out into the less dense medium, all of the light is reflected back into the denser medium, obeying the normal law of reflection.",
    ["States the condition: light in a denser medium hitting the boundary at an angle greater than the critical angle", "States the result: all the light is reflected back into the denser medium, none is refracted out"]),
  sa(76,
    "An optical fibre is made of a material with a high refractive index (the core) so that light travelling inside it strikes the walls of the fibre at an angle greater than the critical angle. Each time the light reaches the wall of the fibre it undergoes total internal reflection rather than escaping, bouncing repeatedly along the length of the fibre and carrying its signal over long distances with very little loss.",
    ["States the fibre's core has a high refractive index so light inside strikes its walls at an angle greater than the critical angle", "States this causes total internal reflection rather than the light escaping", "Explains this repeats along the fibre, carrying the light (signal) over long distances"]),
  sa(77,
    "The principle of superposition states that when two or more waves meet at the same point in a medium, the resultant displacement at that point is the vector sum of the individual displacements each wave would have produced on its own. After the waves pass through each other, they continue on unaffected, as though the meeting had not occurred.",
    ["States the principle: the resultant displacement where waves overlap is the sum of the individual displacements", "Notes the waves continue on unchanged after passing through the overlap"]),
  sa(78,
    "Constructive interference occurs when two waves meet in phase (crest meets crest, trough meets trough), so their displacements add together to produce a resultant wave with a larger amplitude. Destructive interference occurs when two waves meet out of phase (crest meets trough), so their displacements subtract, producing a resultant wave with a smaller amplitude, or zero displacement if the waves have equal amplitude.",
    ["Defines constructive interference: waves in phase, displacements add, amplitude increases", "Defines destructive interference: waves out of phase, displacements subtract, amplitude decreases (or cancels)", "States the condition for each (in phase vs out of phase)"]),
  sa(79,
    "When a wave travelling along a string reaches the fixed end, it reflects back along the string in the opposite direction. This reflected wave then overlaps with the incoming wave, and by superposition the two waves interfere to produce a stationary pattern: points where the two waves always cancel (nodes, of zero displacement) and points where they always reinforce (antinodes, of maximum displacement), rather than a wave that appears to travel along the string.",
    ["States the wave reflects back from the fixed end, travelling in the opposite direction to the original wave", "States the reflected wave overlaps and interferes with the incoming wave (superposition)", "Describes the resulting stationary pattern of nodes and antinodes"]),
  sa(80,
    "As the siren approaches, it emits each successive wavefront slightly closer to the observer than the last, compressing the sound waves reaching the observer to a shorter wavelength and higher frequency, which is heard as a higher pitch. As it moves away, each wavefront is emitted slightly further from the observer, stretching the waves to a longer wavelength and lower frequency, heard as a lower pitch.",
    ["Explains that an approaching source compresses the wavelength, raising the observed frequency (higher pitch)", "Explains that a receding source stretches the wavelength, lowering the observed frequency (lower pitch)"]),
  sa(81,
    "Redshift is the stretching of light to longer (redder) wavelengths than those emitted by its source, due to the Doppler effect acting on light. Observing redshift in the light from a distant galaxy indicates that the galaxy is moving away from Earth, and this is used as evidence that the universe is expanding.",
    ["Defines redshift as light being stretched to longer wavelengths due to the Doppler effect", "States this indicates the galaxy is moving away from Earth"]),
  sa(82,
    "From longest to shortest wavelength: radio waves, visible light, X-rays, gamma rays. In general, as the wavelength of a region of the electromagnetic spectrum decreases, its frequency increases, and so does the energy carried by each photon — shorter-wavelength radiation such as gamma rays carries much more energy than longer-wavelength radiation such as radio waves.",
    ["Correctly orders the four regions from longest to shortest wavelength", "States that shorter wavelength corresponds to higher frequency", "States that shorter wavelength/higher frequency also means greater energy"]),
  sa(83,
    "Electromagnetic waves are produced by oscillating electric and magnetic fields that regenerate each other as they travel, so they do not need a medium of particles to pass the disturbance along — they can travel through empty space. Sound waves, in contrast, are mechanical vibrations of particles, so they need a medium (such as air, water or a solid) to travel through and cannot exist in a vacuum.",
    ["States electromagnetic waves are self-propagating oscillating electric and magnetic fields, needing no medium", "States sound is a mechanical wave requiring particles of a medium, so it cannot travel through a vacuum"]),
  sa(84,
    "Reflection occurs when a light ray bounces back off the surface of a medium without entering it, obeying the law that the angle of incidence equals the angle of reflection. Refraction occurs when a light ray passes from one medium into another and changes speed, causing it to bend (change direction) at the boundary, unless it is travelling exactly along the normal.",
    ["Defines reflection: the ray bounces back without entering the new medium", "States the law of reflection: angle of incidence equals angle of reflection", "Defines refraction: the ray enters the new medium, changes speed and bends at the boundary"]),
  sa(85,
    "An object becomes negatively charged when it gains extra electrons, so it has more electrons than protons overall. This commonly happens through friction, when electrons are transferred from one material to another as the two surfaces rub together, leaving the material that gained electrons with a net negative charge.",
    ["States an object becomes negatively charged when it gains extra electrons (more electrons than protons)", "Explains this can occur through friction, transferring electrons from one material to another"]),
  sa(86,
    "When a charged object is brought close to (but not touching) a neutral conductor, its electric field repels or attracts the free electrons within the conductor, causing them to redistribute — moving away from or towards the charged object. This separates the conductor's charge, concentrating opposite charge on the near side and like charge on the far side, without any electrons actually being transferred between the two objects.",
    ["States the charged object's field causes free electrons in the neutral conductor to redistribute (without contact)", "Explains this separates charge within the conductor, with opposite charge accumulating on the near side", "Notes no electrons are actually transferred between the two objects"]),
  sa(87,
    "Electric field lines point in the direction that a small positive test charge would be pushed if placed at that point in the field, showing the direction of the electric force. The spacing of the field lines shows the strength of the field: where the lines are closer together the field is stronger, and where they are further apart the field is weaker.",
    ["States field lines show direction: the way a positive test charge would be pushed", "States field lines show strength through their spacing: closer together means a stronger field"]),
  sa(88,
    "At any point in space, the electric field can only point in one direction — the direction of the net force on a positive test charge placed there. If two field lines crossed, that point would appear to have two different field directions at once, which is impossible, so field lines can never cross.",
    ["States the field at any point has only one direction (the force on a test charge there)", "Explains that crossing lines would imply two directions at the same point, which is impossible"]),
  sa(89,
    "(a) The electrostatic force between two charged objects increases as the size (magnitude) of either charge increases — larger charges exert and experience a stronger force on each other. (b) The force decreases as the distance between the two charges increases — the further apart the charges are, the weaker the force between them.",
    ["Part (a): force increases as the magnitude of either charge increases", "Part (b): force decreases as the distance between the charges increases", "Both parts are explained with correct reasoning, not just stated"]),
  sa(90,
    "In a conductor, some electrons are free to move throughout the material, allowing charge to flow easily through it. In an insulator, electrons are tightly bound to their atoms and cannot move freely, so charge cannot flow through the material.",
    ["States a conductor has free (mobile) electrons that allow charge to flow", "States an insulator's electrons are tightly bound and cannot move freely, preventing charge flow"]),
  sa(91,
    "Except very close to the edges of the plates, the field lines between two oppositely charged parallel plates run straight across from the positive plate to the negative plate, evenly spaced everywhere in between. Because the field lines are parallel and evenly spaced throughout the region between the plates, the field has the same strength and direction at every point there, making it uniform.",
    ["States the field lines between the plates are straight, parallel and evenly spaced (away from the edges)", "Concludes this even spacing and direction means the field has the same strength and direction everywhere between the plates (uniform)"]),
  sa(92,
    "Electric potential energy is the energy a charge has because of its position within an electric field, similar to gravitational potential energy due to height. Electric potential difference (voltage) is the change in electric potential energy per unit charge between two points, describing how much energy would be transferred per coulomb of charge moved between those two points.",
    ["Defines electric potential energy as energy due to a charge's position in a field", "Defines potential difference as the change in potential energy per unit charge between two points", "Draws a clear distinction between the two (energy vs. energy-per-charge)"]),
  sa(93,
    "Conventional current is defined, by convention, as the flow of positive charge from the positive terminal of a supply, around the circuit, to the negative terminal. In a metal wire, however, it is actually negatively charged electrons that physically move, and they flow in the opposite direction — from the negative terminal to the positive terminal.",
    ["States conventional current is defined as positive charge flowing from positive to negative terminal", "States electrons actually flow in the opposite direction, from negative to positive terminal"]),
  sa(94,
    "A wire's resistance increases as its length increases, since the charge carriers must travel further and collide with the lattice more often. Resistance decreases as its cross-sectional area increases, since a thicker wire gives the charge carriers more space to flow through. Resistance also increases as the temperature of the wire increases, since the metal's lattice ions vibrate more and collide with the moving electrons more often.",
    ["States resistance increases with length", "States resistance decreases as cross-sectional area increases", "States resistance increases as temperature increases"]),
  sa(95,
    "An ohmic conductor has a resistance that stays constant regardless of the current flowing through it, so a graph of voltage against current is a straight line through the origin, meaning voltage is directly proportional to current. A non-ohmic device such as a filament globe does not have constant resistance — as more current flows, the filament heats up and its resistance increases, so its voltage–current graph curves rather than forming a straight line.",
    ["States an ohmic conductor has constant resistance, giving a straight-line (proportional) voltage–current graph", "States a non-ohmic device's resistance changes with current/temperature", "States this gives a curved (non-proportional) voltage–current graph for the non-ohmic device"]),
  sa(96,
    "In a series circuit, the same current flows through every component one after another, but the supply voltage is shared (divided) between the components according to their resistance. In a parallel circuit, each component is connected directly across the supply so they all have the same voltage, but the total current from the supply is shared (divided) between the branches according to their resistance.",
    ["Describes series: same current through all components", "States series voltage is shared/divided between components", "Describes parallel: same voltage across all branches, current is shared/divided between branches"]),
  sa(97,
    "Adding a resistor in parallel gives the current an additional path to flow through, alongside the existing resistor(s). Because current now has more routes available between the same two points, the overall (equivalent) resistance of the parallel combination is lower than the resistance of any single branch on its own.",
    ["States a parallel resistor provides an extra path for current to flow", "Explains that more available paths for the same current means lower total (equivalent) resistance"]),
  sa(98,
    "An ammeter is connected in series, so it must carry the full current being measured; if its own resistance were large it would noticeably reduce the current in the circuit, giving an inaccurate reading, so it is designed to have a very low resistance. A voltmeter is connected in parallel with a component; if its resistance were low it would draw significant current away from the component and change the circuit, so it is designed to have a very high resistance so that almost no current flows through it instead.",
    ["Explains an ammeter needs very low resistance so it does not reduce the current it is measuring (in series)", "Explains a voltmeter needs very high resistance so it draws negligible current from the component (in parallel)"]),
  sa(99,
    "A current-carrying solenoid produces a magnetic field pattern very similar to that of a bar magnet: field lines emerge from one end (which behaves like a north pole), curve around the outside of the solenoid, and enter the other end (which behaves like a south pole), with the field inside the solenoid being strong and roughly uniform, running along its axis.",
    ["Describes the solenoid's external field lines running from one end (north-like) to the other (south-like)", "States the field inside the solenoid is strong and roughly uniform, along its axis", "States this pattern closely resembles that of a bar magnet"]),
  sa(100,
    "One way is to increase the current flowing through the coil, since a larger current produces a stronger magnetic field. A second way is to increase the number of turns of wire in the coil, since each additional turn adds to the total field produced; a third way is to insert a soft iron core inside the coil, which becomes strongly magnetised and greatly boosts the overall field strength.",
    ["Way 1: increase the current through the coil", "Way 2: increase the number of turns of wire in the coil (or add/use a soft iron core)"]),
];

export const answers: AnswerSet = Object.fromEntries([
  ...mcAnswers,
  ...mcAnswers2,
  ...saAnswers,
  ...saAnswers2,
]);
