/**
 * Pre-renders every formula's LaTeX to KaTeX HTML and writes
 * content/formulas.generated.ts. Runs before build (and can be run by hand:
 * `npm run gen:formulas`).
 *
 * Doing this at build time keeps the ~75 kB KaTeX library out of the client
 * bundle — the app ships only the small HTML strings.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import katex from "katex";

import { F } from "../content/formulas";

const out: Record<string, string> = {};
for (const def of Object.values(F)) {
  out[def.text] = katex.renderToString(def.tex, {
    throwOnError: true,
    displayMode: false,
    output: "html",
  });
}

const body =
  `// GENERATED by scripts/gen-formula-html.ts — do not edit.\n` +
  `// Pre-rendered KaTeX HTML for each formula, keyed by its plain-text form.\n\n` +
  `export const FORMULA_HTML: Record<string, string> = ${JSON.stringify(out, null, 2)};\n`;

const target = join(process.cwd(), "content", "formulas.generated.ts");
writeFileSync(target, body, "utf8");
console.log(`✓ Wrote ${Object.keys(out).length} formula HTML strings to content/formulas.generated.ts`);
