import type { Answer, AnswerSet } from "@/lib/types";

// Answer key for y11-formula-test. NO "server-only" import here (so the content
// validator can read it); only ever re-exported via content/answers/index.ts,
// which is server-only. Never import this file from a client component.

const U = "y11-formula-test";
const p2 = (n: number) => String(n).padStart(2, "0");

// ---- short answers ---------------------------------------------------------

/** what the formula tells you (reused across a formula's short questions) */
const TELLS: Record<string, string> = {
  suvat_s: "It gives the displacement of an object moving with constant (uniform) acceleration, from its initial velocity, its acceleration and the time.",
  suvat_v2: "It links an object's final velocity to its initial velocity, acceleration and displacement when the acceleration is constant — with no time term.",
  suvat_v: "It gives the final velocity of an object moving with constant acceleration after a time t.",
  fma: "It states that the net (resultant) force on an object equals its mass times its acceleration (Newton's second law).",
  gpe: "It gives the change in gravitational potential energy of a mass raised or lowered through a height Δh near the Earth's surface.",
  work: "It gives the work done by a constant force whose point of application moves through a displacement s, where θ is the angle between the force and the displacement.",
  ke: "It gives the translational kinetic energy of a mass m moving at speed v.",
  powerE: "It gives the average power — the rate at which energy is transferred or transformed.",
  powerFv: "It gives the power delivered by a force F to an object moving with velocity v, where θ is the angle between them.",
  consKE: "It states that the total kinetic energy of a system is the same before and after an interaction; this only holds for an elastic collision.",
  consP: "It states that the total momentum of a system is unchanged by an interaction when no net external force acts on it (conservation of momentum).",
  impulse: "It states that the change in an object's momentum equals the impulse — the net force multiplied by the time for which it acts.",
  ugrav: "It gives the gravitational potential energy of a mass m a distance r from a mass M, with the zero of energy taken at infinite separation (so U is negative).",
  wave: "It relates the speed of a wave to its frequency and its wavelength.",
  fT: "It states that the frequency of a periodic event is the reciprocal of its period.",
  refIndex: "It defines the refractive index of a medium as the speed of light in a vacuum divided by its speed in that medium.",
  specHeat: "It gives the heat energy needed to change the temperature of a mass m of a substance by ΔT, given its specific heat capacity.",
  beats: "It gives the beat frequency heard when two notes of slightly different frequency sound together — the size of the difference between them.",
  doppler: "It gives the frequency detected by an observer when the source and/or observer move relative to the medium (the Doppler effect).",
  snell: "It relates the angles a light ray makes with the normal on each side of a boundary to the refractive indices of the two media (Snell's law).",
  critical: "It gives the critical angle of incidence beyond which light going from a denser to a less dense medium is totally internally reflected.",
  invSquare: "It expresses the inverse-square law: the intensity of radiation from a point source falls off with the square of the distance from it.",
  conduction: "It gives the rate at which heat is conducted through a slab of material of area A and thickness d with a temperature difference ΔT across it.",
  eField: "It gives the strength of the uniform electric field between two parallel plates from the voltage across them and their separation.",
  potDiff: "It defines the electric potential difference between two points as the change in electric potential energy per unit charge moved between them.",
  wqv: "It gives the work done (energy transferred) when a charge q moves through a potential difference V.",
  wqed: "It gives the work done on a charge q as it moves a distance d through a uniform electric field E.",
  bWire: "It gives the magnetic field strength at a perpendicular distance r from a long straight wire carrying current I.",
  fqe: "It gives the force on a charge q placed in an electric field E.",
  coulomb: "It gives the electrostatic force between two point charges — proportional to the product of the charges and inversely proportional to the square of their separation (Coulomb's law).",
  current: "It defines electric current as the rate of flow of charge — the charge passing a point divided by the time taken.",
  ohm: "It relates the potential difference across an ohmic conductor to the current through it and its resistance (Ohm's law).",
  pvi: "It gives the electrical power delivered to or dissipated by a component as the potential difference across it times the current through it.",
  fqvb: "It gives the force on a charge q moving at speed v through a magnetic field B, where θ is the angle between the velocity and the field.",
  flib: "It gives the force on a length l of conductor carrying current I in a magnetic field B, where θ is the angle between the conductor and the field.",
  parallelWires: "It gives the force per unit length between two long parallel conductors carrying currents I₁ and I₂ a distance r apart.",
};

function sa(
  n: number,
  tells: string,
  quantity: string,
  unit: string,
  notes?: string,
): [string, Answer] {
  return [
    `${U}.s${p2(n)}`,
    {
      modelAnswer: `(a) ${tells} (b) It represents ${quantity}. (c) SI unit: ${unit}.`,
      rubric: [
        `Describes what the formula tells you (${tells})`,
        `Names the quantity: ${quantity}`,
        `States the SI unit: ${unit}`,
      ],
      notes,
    },
  ];
}

const MS = "metre per second (m s⁻¹)";
const J = "joule (J)";
const M = "metre (m)";
const HZ = "hertz (Hz)";
const RAD = "radian (rad); degrees are also used in practice";
const DIMLESS = "none — refractive index is a ratio and has no unit";

const shortAnswers: Array<[string, Answer]> = [
  sa(1, TELLS.suvat_s, "the displacement of the object", M),
  sa(2, TELLS.suvat_v2, "the final velocity of the object", MS),
  sa(3, TELLS.suvat_v, "the final velocity of the object", MS),
  sa(4, TELLS.fma, "the net (resultant) force on the object", "newton (N)"),
  sa(5, TELLS.gpe, "the change in gravitational potential energy", J),
  sa(6, TELLS.work, "the work done by the force", J),
  sa(7, TELLS.ke, "the kinetic energy of the object", J),
  sa(8, TELLS.powerE, "power — the rate of energy transfer", "watt (W)"),
  sa(9, TELLS.powerFv, "power", "watt (W)"),
  sa(10, TELLS.consKE, "the speed of one of the colliding objects", MS),
  sa(11, TELLS.consP, "the mass of one of the objects", "kilogram (kg)"),
  sa(12, TELLS.impulse, "the change in momentum (equal to the impulse)", "kilogram metre per second (kg m s⁻¹), equivalently newton second (N s)"),
  sa(13, TELLS.ugrav, "the gravitational potential energy of the two-mass system", J),
  sa(14, TELLS.wave, "the wavelength of the wave", M),
  sa(15, TELLS.fT, "the period of the wave (time for one cycle)", "second (s)"),
  sa(16, TELLS.refIndex, "the absolute refractive index of the medium", DIMLESS),
  sa(17, TELLS.specHeat, "the heat energy transferred to or from the substance", J),
  sa(18, TELLS.beats, "the beat frequency", HZ),
  sa(19, TELLS.doppler, "the frequency detected by the observer", HZ),
  sa(20, TELLS.snell, "the angle of incidence, measured from the normal", RAD),
  sa(21, TELLS.critical, "the critical angle", RAD),
  sa(22, TELLS.invSquare, "the intensity of the radiation at the first position", "watt per square metre (W m⁻²)"),
  sa(23, TELLS.conduction, "the thermal conductivity of the material", "watt per metre per kelvin (W m⁻¹ K⁻¹)"),
  sa(24, TELLS.eField, "the electric field strength between the plates", "volt per metre (V m⁻¹), equivalently newton per coulomb (N C⁻¹)"),
  sa(25, TELLS.potDiff, "the electric potential difference (voltage) between the two points", "volt (V)"),
  sa(26, TELLS.wqv, "the electric charge that is moved", "coulomb (C)"),
  sa(27, TELLS.wqed, "the electric field strength", "newton per coulomb (N C⁻¹), equivalently volt per metre (V m⁻¹)"),
  sa(28, TELLS.bWire, "the magnetic field strength (magnetic flux density)", "tesla (T)"),
  sa(29, TELLS.fqe, "the force on the charge", "newton (N)"),
  sa(30, TELLS.coulomb, "the electrostatic force between the two point charges", "newton (N)"),
  sa(31, TELLS.current, "the electric current", "ampere (A)"),
  sa(32, TELLS.ohm, "the resistance of the conductor", "ohm (Ω)"),
  sa(33, TELLS.pvi, "the electrical power", "watt (W)"),
  sa(34, TELLS.fqvb, "the magnetic force on the moving charge", "newton (N)"),
  sa(35, TELLS.flib, "the force on the current-carrying conductor", "newton (N)"),
  sa(36, TELLS.parallelWires, "the force per unit length between the two wires", "newton per metre (N m⁻¹)"),
  sa(37, TELLS.suvat_s, "the initial velocity of the object", MS),
  sa(38, TELLS.suvat_v2, "the constant acceleration of the object", "metre per second squared (m s⁻²)"),
  sa(39, TELLS.suvat_v, "the time interval", "second (s)"),
  sa(40, TELLS.fma, "the mass of the object", "kilogram (kg)"),
  sa(41, TELLS.gpe, "the change in height", M),
  sa(42, TELLS.work, "the angle between the force and the displacement", RAD),
  sa(43, TELLS.ke, "the speed of the object", MS),
  sa(44, TELLS.specHeat, "the specific heat capacity of the substance", "joule per kilogram per kelvin (J kg⁻¹ K⁻¹)"),
  sa(45, TELLS.snell, "the refractive index of the second medium", DIMLESS),
  sa(46, TELLS.invSquare, "the distance from the source at the first position", M),
  sa(47, TELLS.bWire, "the perpendicular distance from the wire", M),
  sa(48, TELLS.coulomb, "the distance between the two point charges", M),
  sa(49, TELLS.ohm, "the potential difference across the conductor", "volt (V)"),
  sa(50, TELLS.fqvb, "the magnetic field strength (magnetic flux density)", "tesla (T)"),
  sa(51, TELLS.suvat_s, "the constant (uniform) acceleration of the object", "metre per second squared (m s⁻²)"),
  sa(52, TELLS.suvat_v2, "the initial velocity of the object", MS),
  sa(53, TELLS.suvat_v, "the constant acceleration of the object", "metre per second squared (m s⁻²)"),
  sa(54, TELLS.fma, "the acceleration produced by the net force", "metre per second squared (m s⁻²)"),
  sa(55, TELLS.gpe, "the mass being raised or lowered", "kilogram (kg)"),
  sa(56, TELLS.work, "the magnitude of the force doing the work", "newton (N)"),
  sa(57, TELLS.ke, "the mass of the moving object", "kilogram (kg)"),
  sa(58, TELLS.powerE, "the amount of energy transferred or transformed", J),
  sa(59, TELLS.powerFv, "the magnitude of the force doing work on the object", "newton (N)"),
  sa(60, TELLS.consKE, "the mass of one of the objects in the collision", "kilogram (kg)"),
  sa(61, TELLS.consP, "the velocity of one of the objects, before or after", MS),
  sa(62, TELLS.impulse, "the net force acting on the object", "newton (N)"),
  sa(63, TELLS.ugrav, "the mass of one of the two bodies (e.g. the orbiting object)", "kilogram (kg)"),
  sa(64, TELLS.wave, "the speed of the wave", MS),
  sa(65, TELLS.fT, "the frequency of the periodic event", HZ),
  sa(66, TELLS.refIndex, "the speed of light in a vacuum (a universal constant)", MS),
  sa(67, TELLS.specHeat, "the mass of the substance", "kilogram (kg)"),
  sa(68, TELLS.beats, "the frequency of one of the two notes", HZ),
  sa(69, TELLS.doppler, "the frequency emitted by the source (measured at the source)", HZ),
  sa(70, TELLS.snell, "the refractive index of the medium the light is travelling in before the boundary", DIMLESS),
  sa(71, TELLS.critical, "the refractive index of the denser medium the light is travelling in", DIMLESS),
  sa(72, TELLS.invSquare, "the intensity of the radiation at the second distance", "watt per square metre (W m⁻²)"),
  sa(73, TELLS.conduction, "the cross-sectional area through which the heat is conducted", "square metre (m²)"),
  sa(74, TELLS.eField, "the potential difference (voltage) across the plates", "volt (V)"),
  sa(75, TELLS.potDiff, "the change in electric potential energy of the charge", J),
  sa(76, TELLS.wqv, "the work done on (or by) the charge", J),
  sa(77, TELLS.wqed, "the magnitude of the charge", "coulomb (C)"),
  sa(78, TELLS.bWire, "the current in the wire", "ampere (A)"),
  sa(79, TELLS.fqe, "the magnitude of the charge", "coulomb (C)"),
  sa(80, TELLS.coulomb, "the magnitude of one of the point charges", "coulomb (C)"),
  sa(81, TELLS.current, "the charge that passes the point", "coulomb (C)"),
  sa(82, TELLS.ohm, "the current through the conductor", "ampere (A)"),
  sa(83, TELLS.pvi, "the potential difference across the component", "volt (V)"),
  sa(84, TELLS.fqvb, "the magnitude of the moving charge", "coulomb (C)"),
  sa(85, TELLS.flib, "the current in the conductor", "ampere (A)"),
  sa(86, TELLS.parallelWires, "the current in one of the wires", "ampere (A)"),
  sa(87, TELLS.suvat_s, "the time interval", "second (s)"),
  sa(88, TELLS.suvat_v2, "the displacement of the object", M),
  sa(89, TELLS.work, "the displacement of the point of application of the force", M),
  sa(90, TELLS.powerFv, "the speed of the object", MS),
  sa(91, TELLS.impulse, "the time interval over which the force acts", "second (s)"),
  sa(92, TELLS.wave, "the frequency of the wave", HZ),
  sa(93, TELLS.specHeat, "the change in temperature of the substance", "kelvin (K); equivalently degree Celsius (°C) for a temperature change"),
  sa(94, TELLS.doppler, "the speed of the source relative to the medium", MS),
  sa(95, TELLS.snell, "the angle of refraction, measured from the normal", RAD),
  sa(96, TELLS.critical, "the refractive index of the less dense medium", DIMLESS),
  sa(97, TELLS.eField, "the separation between the plates", M),
  sa(98, TELLS.wqed, "the distance moved by the charge along the field direction", M),
  sa(99, TELLS.pvi, "the current through the component", "ampere (A)"),
  sa(100, TELLS.parallelWires, "the perpendicular separation between the two wires", M),
];

// ---- multiple choice ------------------------------------------------------

function ma(n: number, correctText: string, why: string): [string, Answer] {
  return [`${U}.m${p2(n)}`, { correctText, rubric: [why] }];
}

const mcAnswers: Array<[string, Answer]> = [
  ma(1, "Find how far a car travels in 4.0 s if it starts at 8.0 m s⁻¹ and accelerates uniformly at 2.0 m s⁻².", "s = ut + ½at² gives displacement from u, a and t. The distractors need v = u + at, F = ma and K = ½mv²."),
  ma(2, "Find the take-off speed of a plane after it accelerates at 3.0 m s⁻² from rest along a 900 m runway.", "v² = u² + 2as links final speed to u, a and s with no time. The distractors need v = u + at, F = ma and p = mv."),
  ma(3, "Find the velocity of a ball 1.5 s after it is thrown straight up at 8.0 m s⁻¹.", "v = u + at gives velocity after a time t. The distractors need v² = u² + 2as, ΔU = mgΔh and Δp = FΔt."),
  ma(4, "Find the net force on a 1200 kg car that is accelerating at 3.0 m s⁻².", "F_net = ma gives net force from mass and acceleration. The distractors need v = u + at, W = Fs and K = ½mv²."),
  ma(5, "Find the gravitational potential energy gained when a 45 kg performer is lifted 3.0 m onto a platform.", "ΔU = mgΔh gives change in gravitational PE near Earth. The distractors need K = ½mv², P = ΔE/Δt and p = mv."),
  ma(6, "Find the work done by a 1200 N driving force as a car moves 600 m in the direction of the force.", "W = Fs cos θ gives work done by a force over a displacement. The distractors need P = Fv, F = ma and ΔU = mgΔh."),
  ma(7, "Find the kinetic energy of a 5.0 kg trolley moving at 4.0 m s⁻¹.", "K = ½mv² gives kinetic energy from mass and speed. The distractors need p = mv, ΔU = mgΔh and Δp = FΔt."),
  ma(8, "Find the power of a kettle that transfers 168 000 J of heat to the water in 95 s.", "P = ΔE/Δt gives power as energy per unit time. The distractors need Q = mcΔT, W = Fs and V = IR."),
  ma(9, "Find the power a train's engine delivers while pulling with 20 000 N at a steady 25 m s⁻¹.", "P = Fv cos θ gives power from force and velocity. The distractors need W = Fs, F = ma and P = ΔE/Δt."),
  ma(10, "Check whether a collision between two pucks is elastic by comparing total kinetic energy before and after.", "Σ½mv²(before) = Σ½mv²(after) only holds for elastic collisions, so it is the test for one. The distractors need conservation of momentum and Δp = FΔt."),
  ma(11, "Find the velocity of a stationary 1.5 kg mass after a 3.0 kg mass moving at 0.40 m s⁻¹ strikes it.", "Conservation of momentum gives the unknown final velocity. The distractors need KE conservation, Δp = FΔt and K = ½mv²."),
  ma(12, "Find the impact speed of a 2000 kg crash-test car from the area under its force–time graph.", "Area under a force–time graph is impulse; Δp = FΔt then gives the speed change. The distractors need F = ma, K = ½mv² and W = Fs."),
  ma(13, "Find the gravitational potential energy of a 500 kg probe 2.0 × 10⁷ m from the centre of a planet.", "U = −GMm/r gives gravitational PE far from a planet. The near-surface distractor uses ΔU = mgΔh; the others need K = ½mv² and p = mv."),
  ma(14, "Find the wavelength in air of a 3.3 × 10⁷ Hz radio wave.", "v = fλ links wave speed, frequency and wavelength. The distractors need f = 1/T, n = c/v and f_beat."),
  ma(15, "Find the frequency of a wave whose period is read from a CRO trace as 4.0 ms.", "f = 1/T converts a period into a frequency. The distractors need v = fλ, f_beat and the Doppler effect."),
  ma(16, "Find the refractive index of glass in which light travels at 2.0 × 10⁸ m s⁻¹.", "n = c/v gives refractive index from the speed of light in the medium. The distractors need Snell's law, the critical angle and v = fλ."),
  ma(17, "Find the energy needed to raise the temperature of 2.0 kg of water by 10 °C.", "Q = mcΔT gives the heat for a temperature change. The distractors need Q/t = kAΔT/d, ΔU = mgΔh and P = ΔE/Δt."),
  ma(18, "Find how many beats per second are heard when a 256 Hz and a 259 Hz tuning fork sound together.", "f_beat = |f₂ − f₁| gives the beat frequency. The distractors need f = 1/T, the Doppler effect and v = fλ."),
  ma(19, "Find the frequency a stationary observer hears from a 1200 Hz siren on a truck approaching at 30 m s⁻¹.", "The Doppler formula gives the observed frequency for a moving source. The distractors need f_beat, v = fλ and f = 1/T."),
  ma(20, "Find the angle of refraction when light passes from water (n = 1.33) into glass (n = 1.52) at 40°.", "Snell's law relates the angles and refractive indices at a boundary. The distractors need the critical angle, n = c/v and v = fλ."),
  ma(21, "Find the smallest angle of incidence at which light is totally internally reflected in a fibre of n = 1.48.", "sin θ_c = n₂/n₁ gives the critical angle. The distractors need Snell's law, n = c/v and v = fλ."),
  ma(22, "Find the light intensity 4.0 m from a lamp, given its intensity at 1.0 m.", "I₁r₁² = I₂r₂² is the inverse-square law for intensity. The distractors need P = ΔE/Δt, Q = mcΔT and v = fλ."),
  ma(23, "Find the rate heat is conducted through a 6.0 mm window, 1.5 m² in area, with 15 °C across it.", "Q/t = kAΔT/d gives the rate of heat conduction through a slab. The distractors need Q = mcΔT, P = ΔE/Δt and P = VI."),
  ma(24, "Find the electric field strength between two parallel plates 1.5 cm apart connected to a 12 V supply.", "E = V/d gives the uniform field between plates. The distractors need F = qE, W = qV and I = q/t."),
  ma(25, "Find the potential difference given that 3.0 J of electrical PE is lost when 0.50 C moves between two points.", "V = ΔU/q gives potential difference as energy per unit charge. The distractors need E = V/d, W = qV and V = IR."),
  ma(26, "Find the work done moving a +3.6 mC charge through a potential difference of 160 V.", "W = qV gives the work to move a charge through a voltage. The distractors need E = V/d, Coulomb's law and I = q/t."),
  ma(27, "Find the work done on a +2.5 µC charge as it moves 0.5 cm through a uniform 800 N C⁻¹ field.", "W = qEd gives the work on a charge crossing a uniform field. The distractors need F = qE, E = V/d and I = q/t."),
  ma(28, "Find the magnetic field strength 20 cm from a long straight wire carrying 10 A.", "B = μ₀I/2πr gives the field around a straight wire. The distractors need F = lIB, F = qvB and the force between parallel wires."),
  ma(29, "Find the force on a −2.5 µC charge sitting in a uniform electric field of 800 N C⁻¹.", "F = qE gives the force on a charge in an electric field. The distractors need Coulomb's law, F = qvB and E = V/d."),
  ma(30, "Find the electrostatic force on a +5.0 µC charge from a +8.0 µC charge 4.0 cm away.", "Coulomb's law gives the force between two point charges. The distractors need F = qE, E = V/d and W = qV."),
  ma(31, "Find the current in a wire when 360 C of charge passes a point in 60 s.", "I = q/t defines current as charge per unit time. The distractors need V = IR, P = VI and W = qV."),
  ma(32, "Find the current through a 6.0 Ω resistor connected across a 12 V supply.", "V = IR (Ohm's law) links voltage, current and resistance. The distractors need P = VI, I = q/t and E = V/d."),
  ma(33, "Find the power dissipated by a heating coil carrying 6.0 A at 30 V.", "P = VI gives electrical power from voltage and current. The distractors need V = IR, I = q/t and Q = mcΔT."),
  ma(34, "Find the force on a proton moving at 2.0 × 10⁶ m s⁻¹ at right angles to a 0.30 T magnetic field.", "F = qvB sin θ gives the force on a moving charge in a magnetic field. The distractors need F = lIB, Coulomb's law and B = μ₀I/2πr."),
  ma(35, "Find the force on a 4.0 cm length of wire carrying 3.0 A at right angles to a 0.25 T field.", "F = lIB sin θ gives the force on a current-carrying conductor. The distractors need F = qvB, the force between parallel wires and B = μ₀I/2πr."),
  ma(36, "Find the force per metre between two parallel wires 5.0 cm apart carrying 10 A and 15 A.", "F/l = (μ₀/2π)(I₁I₂/r) gives the force per unit length between parallel currents. The distractors need F = lIB, B = μ₀I/2πr and F = qvB."),
  ma(37, "Find the distance a book slides down a tilted desk in 1.25 s, starting from rest.", "s = ut + ½at² gives displacement from rest under constant acceleration. The distractors need v = u + at, F = ma and K = ½mv²."),
  ma(38, "Find a car's velocity 5.5 s after it starts braking at 3.0 m s⁻² from 17 m s⁻¹.", "v = u + at gives velocity after a time under constant acceleration. The distractors need v² = u² + 2as, F = ma and p = mv."),
  ma(39, "Find the acceleration of two blocks (total 80 kg) pushed across a frictionless floor by a 200 N force.", "F_net = ma gives acceleration from net force and total mass. The distractors need v = u + at, W = Fs and K = ½mv²."),
  ma(40, "Find the potential energy a 38 kg student gains climbing a 3.2 m flight of stairs.", "ΔU = mgΔh gives gravitational PE gained over a height. The distractors need P = ΔE/Δt, K = ½mv² and p = mv."),
  ma(41, "Find the momentum of the third fragment when a stationary 5.5 kg shell bursts into three pieces.", "Conservation of momentum (total zero before) gives the third momentum. The distractors need K = ½mv² and Δp = FΔt."),
  ma(42, "Find the average force on each of two cars in a 0.40 s head-on collision, given their change in velocity.", "Δp = F_net Δt gives the average force from the momentum change and contact time. The distractors need F = ma, K = ½mv² and ΔU = mgΔh."),
  ma(43, "Find the specific heat capacity of a metal block from the temperature change when it is dropped into known water.", "Q = mcΔT (with heat lost = heat gained) gives an unknown specific heat. The distractors need Q/t = kAΔT/d, P = ΔE/Δt and ΔU = mgΔh."),
  ma(44, "Find the frequency an observer hears once a 1000 Hz aircraft has passed and is receding at 100 m s⁻¹.", "The Doppler formula gives the observed frequency for a receding source. The distractors need f_beat, f = 1/T and v = fλ."),
  ma(45, "Find the refractive index of a Perspex block from the gradient of a sin i versus sin r graph.", "Snell's law makes the gradient of sin i vs sin r equal to the refractive index. The distractors need the critical angle, n = c/v and v = fλ."),
  ma(46, "Find how many times brighter a lamp 20 cm from a page is than a ceiling light 2.0 m away.", "I₁r₁² = I₂r₂² (inverse-square law) compares intensities at two distances. The distractors need P = ΔE/Δt, Q = mcΔT and P = VI."),
  ma(47, "Find how the magnetic field strength changes as you move from 10 cm to 20 cm from a straight wire.", "B = μ₀I/2πr shows B ∝ 1/r for a straight wire. The distractors need F = lIB, the force between parallel wires and F = qvB."),
  ma(48, "Find the separation at which a +6 µC and a −8 µC charge attract each other with a force of 1.11 N.", "Coulomb's law, rearranged for r, gives the separation for a given force. The distractors need F = qE, W = qV and E = V/d."),
  ma(49, "Find the energy a spotlight uses in one hour from its operating voltage and current.", "P = VI gives power, and energy = power × time. The distractors need V = IR, I = q/t and the inverse-square law."),
  ma(50, "Find the force on an electron entering a 0.20 T field at 45° to the field lines at 3.0 × 10⁶ m s⁻¹.", "F = qvB sin θ gives the force on a charge moving at an angle to a magnetic field. The distractors need F = lIB, Coulomb's law and B = μ₀I/2πr."),
  ma(51, "Find how far a cyclist travels in 6.0 s if she starts at 3.0 m s⁻¹ and pedals with a uniform acceleration of 0.50 m s⁻².", "s = ut + ½at² gives displacement from u, a and t. The distractors need v = u + at, F = ma and K = ½mv²."),
  ma(52, "Find the speed of a skateboarder at the bottom of a 5.0 m ramp, starting at 1.0 m s⁻¹ with a constant acceleration of 4.0 m s⁻² down the slope.", "v² = u² + 2as links final speed to u, a and s with no time. The distractors need v = u + at, F = ma and p = mv."),
  ma(53, "Find the velocity of a lift 2.0 s after it starts from rest, accelerating upward at 1.5 m s⁻².", "v = u + at gives velocity after a time t. The distractors need s = ut + ½at², ΔU = mgΔh and Δp = FΔt."),
  ma(54, "Find the net force needed to accelerate a 25 kg shopping trolley at 0.80 m s⁻².", "F_net = ma gives net force from mass and acceleration. The distractors need v = u + at, W = Fs and K = ½mv²."),
  ma(55, "Find the gravitational potential energy gained when a 12 kg suitcase is lifted 1.2 m onto an overhead locker.", "ΔU = mgΔh gives change in gravitational PE near Earth. The distractors need K = ½mv², P = ΔE/Δt and p = mv."),
  ma(56, "Find the work done by a person pushing a 300 N lawnmower a distance of 15 m in the direction of the push.", "W = Fs cos θ gives work done by a force over a displacement. The distractors need P = Fv, F = ma and ΔU = mgΔh."),
  ma(57, "Find the kinetic energy of a 0.15 kg cricket ball bowled at 35 m s⁻¹.", "K = ½mv² gives kinetic energy from mass and speed. The distractors need p = mv, ΔU = mgΔh and Δp = FΔt."),
  ma(58, "Find the power of a solar panel that delivers 45 000 J of electrical energy in 300 s.", "P = ΔE/Δt gives power as energy per unit time. The distractors need Q = mcΔT, W = Fs and V = IR."),
  ma(59, "Find the power delivered by a tow rope pulling a water-skier with 400 N at a steady 8.0 m s⁻¹.", "P = Fv cos θ gives power from force and velocity. The distractors need W = Fs, F = ma and P = ΔE/Δt."),
  ma(60, "Check whether two gliders on an air track collide elastically by comparing their total kinetic energy before and after.", "Σ½mv²(before) = Σ½mv²(after) only holds for elastic collisions, so it is the test for one. The distractors need conservation of momentum, Δp = FΔt and K = ½mv²."),
  ma(61, "Find the recoil velocity of a 4.0 kg rifle after it fires a 0.010 kg bullet at 300 m s⁻¹.", "Conservation of momentum gives the recoil velocity from the bullet's momentum. The distractors need KE conservation, Δp = FΔt and K = ½mv²."),
  ma(62, "Find the average force a goalkeeper exerts catching a 0.45 kg ball that stops in 0.15 s after arriving at 20 m s⁻¹.", "Δp = F_net Δt gives the average force from the momentum change and contact time. The distractors need F = ma, K = ½mv² and W = Fs."),
  ma(63, "Find the gravitational potential energy of a 1200 kg satellite 7.0 × 10⁶ m from Earth's centre.", "U = −GMm/r gives gravitational PE far from a planet. The near-surface distractor uses ΔU = mgΔh; the others need K = ½mv² and p = mv."),
  ma(64, "Find the speed of sound in a gas given a 440 Hz tuning fork produces a wavelength of 0.75 m in it.", "v = fλ links wave speed, frequency and wavelength. The distractors need f = 1/T, n = c/v and f_beat."),
  ma(65, "Find the frequency of rotation of a fan blade that completes one revolution every 0.040 s.", "f = 1/T converts a period into a frequency. The distractors need v = fλ, f_beat and the Doppler effect."),
  ma(66, "Find the refractive index of a diamond in which light travels at 1.24 × 10⁸ m s⁻¹.", "n = c/v gives refractive index from the speed of light in the medium. The distractors need Snell's law, the critical angle and v = fλ."),
  ma(67, "Find the heat energy needed to warm 3.0 kg of cooking oil from 20 °C to 180 °C, given its specific heat capacity.", "Q = mcΔT gives the heat for a temperature change. The distractors need Q/t = kAΔT/d, P = ΔE/Δt and ΔU = mgΔh."),
  ma(68, "Find the beat frequency heard when two guitar strings tuned to 330 Hz and 333 Hz are plucked together.", "f_beat = |f₂ − f₁| gives the beat frequency. The distractors need f = 1/T, the Doppler effect and v = fλ."),
  ma(69, "Find the frequency heard by a stationary observer as an ambulance siren (700 Hz) approaches at 25 m s⁻¹.", "The Doppler formula gives the observed frequency for a moving source. The distractors need f_beat, f = 1/T and v = fλ."),
  ma(70, "Find the angle of incidence in air that produces a 20° angle of refraction in a glass block of n = 1.50.", "Snell's law relates the angles and refractive indices at a boundary. The distractors need the critical angle, n = c/v and v = fλ."),
  ma(71, "Find the critical angle for a diamond–air boundary given diamond's refractive index of 2.42.", "sin θ_c = n₂/n₁ gives the critical angle. The distractors need Snell's law, n = c/v and v = fλ."),
  ma(72, "Find the intensity of sunlight reaching a planet twice as far from the Sun as Earth, given Earth's intensity.", "I₁r₁² = I₂r₂² is the inverse-square law for intensity. The distractors need P = ΔE/Δt, Q = mcΔT and v = fλ."),
  ma(73, "Find the rate of heat loss through a 12 mm thick wooden door, 2.0 m² in area, with a 12 °C difference across it.", "Q/t = kAΔT/d gives the rate of heat conduction through a slab. The distractors need Q = mcΔT, P = ΔE/Δt and P = VI."),
  ma(74, "Find the electric field strength between two charged plates 4.0 mm apart connected to a 6.0 V battery.", "E = V/d gives the uniform field between plates. The distractors need W = qV, I = q/t and Coulomb's law."),
  ma(75, "Find the potential difference between two points if a 0.20 C charge gains 5.0 J of electrical potential energy moving between them.", "V = ΔU/q gives potential difference as energy per unit charge. The distractors need E = V/d, W = qV and V = IR."),
  ma(76, "Find the energy transferred when a 2.0 C charge moves through a 9.0 V battery.", "W = qV gives the work to move a charge through a voltage. The distractors need E = V/d, F = qE and I = q/t."),
  ma(77, "Find the work done on a dust particle carrying +1.2 µC as it crosses 3.0 mm of a uniform 500 N C⁻¹ field in an electrostatic precipitator.", "W = qEd gives the work on a charge crossing a uniform field. The distractors need F = qE, E = V/d and Coulomb's law."),
  ma(78, "Find the magnetic field strength 8.0 cm from a power cable carrying 25 A.", "B = μ₀I/2πr gives the field around a straight wire. The distractors need F = lIB, F = qvB and the force between parallel wires."),
  ma(79, "Find the force on a +4.0 µC dust particle in the 500 N C⁻¹ field of an electrostatic precipitator.", "F = qE gives the force on a charge in an electric field. The distractors need Coulomb's law, F = qvB and E = V/d."),
  ma(80, "Find the electrostatic force between two charged balloons, each carrying 2.0 µC, held 15 cm apart.", "Coulomb's law gives the force between two point charges. The distractors need F = qE, W = qV and E = V/d."),
  ma(81, "Find the current in a torch bulb's filament if 45 C of charge flows through it in 30 s.", "I = q/t defines current as charge per unit time. The distractors need V = IR, P = VI and W = qV."),
  ma(82, "Find the resistance of a heating element that draws 4.0 A when connected to 240 V mains.", "V = IR (Ohm's law) links voltage, current and resistance. The distractors need P = VI, I = q/t and F = qE."),
  ma(83, "Find the power delivered to a phone charger operating at 5.0 V and drawing 2.0 A.", "P = VI gives electrical power from voltage and current. The distractors need V = IR, I = q/t and W = qV."),
  ma(84, "Find the magnetic force on an alpha particle (charge +2e) moving at 5.0 × 10⁵ m s⁻¹ perpendicular to a 0.40 T field in a mass spectrometer.", "F = qvB sin θ gives the force on a moving charge in a magnetic field. The distractors need F = lIB, Coulomb's law and B = μ₀I/2πr."),
  ma(85, "Find the force on a 6.0 cm length of a loudspeaker voice coil carrying 0.80 A in a 0.50 T magnetic field.", "F = lIB sin θ gives the force on a current-carrying conductor. The distractors need F = qvB, the force between parallel wires and B = μ₀I/2πr."),
  ma(86, "Find the force per metre between two overhead power lines 2.0 m apart carrying 200 A and 150 A in the same direction.", "F/l = (μ₀/2π)(I₁I₂/r) gives the force per unit length between parallel currents. The distractors need B = μ₀I/2πr, F = lIB and F = qvB."),
  ma(87, "Find the depth of a well if a stone dropped from rest takes 2.5 s to reach the water.", "s = ut + ½at² gives displacement from rest under constant acceleration. The distractors need v = u + at, v² = u² + 2as and K = ½mv²."),
  ma(88, "Find the speed of a sledge at the bottom of a 40 m icy slope, starting from rest with a constant acceleration of 2.0 m s⁻².", "v² = u² + 2as gives final speed from u, a and s with no time. The distractors need s = ut + ½at², F = ma and p = mv."),
  ma(89, "Find the work done by a tugboat pulling a barge with a steady 5000 N force over 200 m.", "W = Fs cos θ gives work done by a force over a displacement. The distractors need P = Fv, F = ma and ΔU = mgΔh."),
  ma(90, "Find the power output of a cyclist pushing with 150 N at a steady 6.0 m s⁻¹ into a headwind.", "P = Fv cos θ gives power from force and velocity. The distractors need W = Fs, F = ma and P = ΔE/Δt."),
  ma(91, "Find the impulse delivered to a 0.058 kg tennis ball that leaves a racquet at 45 m s⁻¹ having arrived at 20 m s⁻¹ travelling the other way.", "Δp = F_net Δt gives the change in momentum directly from mass and velocity change. The distractors need F = ma, K = ½mv² and W = Fs."),
  ma(92, "Find the wavelength of a wave on a guitar string vibrating at 196 Hz, given waves travel along the string at 250 m s⁻¹.", "v = fλ links wave speed, frequency and wavelength. The distractors need f = 1/T, f_beat and the Doppler effect."),
  ma(93, "Find the temperature rise of a 0.50 kg aluminium block that absorbs 4500 J of heat, given its specific heat capacity.", "Q = mcΔT gives the temperature change for a given heat input. The distractors need Q/t = kAΔT/d, P = ΔE/Δt and ΔU = mgΔh."),
  ma(94, "Find the frequency heard by a driver approaching a stationary factory horn sounding at 500 Hz, moving at 15 m s⁻¹ toward it.", "The Doppler formula gives the observed frequency for a moving observer. The distractors need f_beat, f = 1/T and v = fλ."),
  ma(95, "Find the angle of refraction as light travels from glass (n = 1.50) into water (n = 1.33) at an angle of incidence of 35°.", "Snell's law relates the angles and refractive indices at a boundary. The distractors need the critical angle, n = c/v and v = fλ."),
  ma(96, "Find the critical angle for an optical fibre core of refractive index 1.52 surrounded by air-like cladding.", "sin θ_c = n₂/n₁ gives the critical angle. The distractors need Snell's law, n = c/v and v = fλ."),
  ma(97, "Find the electric field strength inside a parallel-plate demonstration, plates 2.0 cm apart, connected to a 20 kV supply.", "E = V/d gives the uniform field between plates. The distractors need F = qE, W = qV and Coulomb's law."),
  ma(98, "Find the work done on an ink droplet carrying −2.0 µC as it crosses 4.0 mm of a uniform 300 N C⁻¹ field in an inkjet printer's deflection plates.", "W = qEd gives the work on a charge crossing a uniform field. The distractors need F = qE, E = V/d and I = q/t."),
  ma(99, "Find the power rating of an electric jug that draws 8.0 A from a 240 V supply.", "P = VI gives electrical power from voltage and current. The distractors need V = IR, Q = mcΔT and I = q/t."),
  ma(100, "Find the force per metre between two switchboard busbars 3.0 cm apart carrying 400 A and 350 A.", "F/l = (μ₀/2π)(I₁I₂/r) gives the force per unit length between parallel currents. The distractors need B = μ₀I/2πr, F = lIB and F = qvB."),
];

export const answers: AnswerSet = Object.fromEntries([
  ...shortAnswers,
  ...mcAnswers,
]);
